package beans;
// Generated 29 Jan, 2020 5:25:13 PM by Hibernate Tools 4.0.1.Final

/**
 * ElectTestTransaction generated by hbm2java
 */
public class ElectTestTransaction implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private ElectTestTransactionId id;
	private String observedValue;
	private String remarks;

	public ElectTestTransaction() {
	}

	public ElectTestTransaction(ElectTestTransactionId id, String observedValue, String remarks) {
		this.id = id;
		this.observedValue = observedValue;
		this.remarks = remarks;
	}
	public ElectTestTransaction(ElectTestTransactionId id) {
		this.id = id;
		
	}

	public ElectTestTransactionId getId() {
		return this.id;
	}

	public void setId(ElectTestTransactionId id) {
		this.id = id;
	}

	public String getObservedValue() {
		return this.observedValue;
	}

	public void setObservedValue(String observedValue) {
		this.observedValue = observedValue;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
