package beans;
// Generated 29 Jan, 2020 4:21:34 PM by Hibernate Tools 4.0.1.Final

/**
 * ElectTestParaM generated by hbm2java
 */
public class ElectTestParaM implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ElectTestParaMId id;
	private Integer seqNo;
	private String srNo;
	private String specifiedDesc;
	private String listValueObserved;
	private String listValueRemark;
	private String defaultValueObserved;
	private String defaultValueRemark;
	private String headingFlag;
	private String validationRule;
	private String subPara;

	public ElectTestParaM() {
	}

	public ElectTestParaM(ElectTestParaMId id) {
		this.id = id;
	}

	public ElectTestParaM(ElectTestParaMId id, Integer seqNo, String srNo, String specifiedDesc, String listValueObserved,
			String listValueRemark, String defaultValueObserved,String defaultValueRemark, String headingFlag, String validationRule, String subPara) {
		this.id = id;
		this.seqNo = seqNo;
		this.srNo = srNo;
		this.specifiedDesc = specifiedDesc;
		this.listValueObserved = listValueObserved;
		this.listValueRemark=listValueRemark;
		this.defaultValueObserved = defaultValueObserved;
		this.defaultValueRemark=defaultValueRemark;
		this.headingFlag = headingFlag;
		this.validationRule=validationRule;
		this.subPara=subPara;
	}

	public ElectTestParaMId getId() {
		return this.id;
	}

	public void setId(ElectTestParaMId id) {
		this.id = id;
	}

	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	public String getSrNo() {
		return this.srNo;
	}

	public void setSrNo(String srNo) {
		this.srNo = srNo;
	}

	public String getSpecifiedDesc() {
		return this.specifiedDesc;
	}

	public void setSpecifiedDesc(String specifiedDesc) {
		this.specifiedDesc = specifiedDesc;
	}

	public String getListValueObserved() {
		return listValueObserved;
	}

	public void setListValueObserved(String listValueObserved) {
		this.listValueObserved = listValueObserved;
	}

	public String getListValueRemark() {
		return listValueRemark;
	}

	public void setListValueRemark(String listValueRemark) {
		this.listValueRemark = listValueRemark;
	}

	public String getDefaultValueObserved() {
		return defaultValueObserved;
	}

	public void setDefaultValueObserved(String defaultValueObserved) {
		this.defaultValueObserved = defaultValueObserved;
	}

	public String getDefaultValueRemark() {
		return defaultValueRemark;
	}

	public void setDefaultValueRemark(String defaultValueRemark) {
		this.defaultValueRemark = defaultValueRemark;
	}

	

	public String getHeadingFlag() {
		return this.headingFlag;
	}

	public void setHeadingFlag(String headingFlag) {
		this.headingFlag = headingFlag;
	}

	public String getValidationRule() {
		return validationRule;
	}

	public void setValidationRule(String validationRule) {
		this.validationRule = validationRule;
	}

	public String getSubPara() {
		return subPara;
	}

	public void setSubPara(String subPara) {
		this.subPara = subPara;
	}

}
