package beans;
// Generated 19 Feb, 2020 5:25:12 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * ElectBatteryTestTrans generated by hbm2java
 */
public class ElectBatteryTestTrans implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	private Integer furnishingAssetId;
	private String batteryBoxMake;
	private String batteryBoxMakeActual;
	private String mountingBatteryBoxActual;
	private String batteryCommisionedActual;
	private String battery1;
	private String battery2;
	private String battery3;
	private String battery4;
	private String battery5;
	private String battery6;
	private String battery7;
	private String battery8;
	private String battery9;
	private Date lugDate1;
	private Date lugDate2;
	private Date lugDate3;
	private Date lugDate4;
	private Date lugDate5;
	private Date lugDate6;
	private Date lugDate7;
	private Date lugDate8;
	private Date lugDate9;
	private String leadAcidBatteryMake;
	private String leadAcidBatteryMake1;
	private String leadAcidBatteryMake2;
	private String leadAcidBatteryMake3;
	private Date leadAcidBatteryLugDate1;
	private Date leadAcidBatteryLugDate2;
	private Date leadAcidBatteryLugDate3;
	private String leadAcidBatteryActual;
	private String batteryCommisionedMake;

	public ElectBatteryTestTrans() {
	}

	

	public ElectBatteryTestTrans(Integer furnishingAssetId, String batteryBoxMake, String batteryBoxMakeActual,
			String mountingBatteryBoxActual, String batteryCommisionedActual, String battery1, String battery2,
			String battery3, String battery4, String battery5, String battery6, String battery7, String battery8,
			String battery9, Date lugDate1, Date lugDate2, Date lugDate3, Date lugDate4, Date lugDate5, Date lugDate6,
			Date lugDate7, Date lugDate8, Date lugDate9, String leadAcidBatteryMake, String leadAcidBatteryMake1,
			String leadAcidBatteryMake2, String leadAcidBatteryMake3, Date leadAcidBatteryLugDate1,
			Date leadAcidBatteryLugDate2, Date leadAcidBatteryLugDate3, String leadAcidBatteryActual,
			String batteryCommisionedMake) {
		this.furnishingAssetId = furnishingAssetId;
		this.batteryBoxMake = batteryBoxMake;
		this.batteryBoxMakeActual = batteryBoxMakeActual;
		this.mountingBatteryBoxActual = mountingBatteryBoxActual;
		this.batteryCommisionedActual = batteryCommisionedActual;
		this.battery1 = battery1;
		this.battery2 = battery2;
		this.battery3 = battery3;
		this.battery4 = battery4;
		this.battery5 = battery5;
		this.battery6 = battery6;
		this.battery7 = battery7;
		this.battery8 = battery8;
		this.battery9 = battery9;
		this.lugDate1 = lugDate1;
		this.lugDate2 = lugDate2;
		this.lugDate3 = lugDate3;
		this.lugDate4 = lugDate4;
		this.lugDate5 = lugDate5;
		this.lugDate6 = lugDate6;
		this.lugDate7 = lugDate7;
		this.lugDate8 = lugDate8;
		this.lugDate9 = lugDate9;
		this.leadAcidBatteryMake = leadAcidBatteryMake;
		this.leadAcidBatteryMake1 = leadAcidBatteryMake1;
		this.leadAcidBatteryMake2 = leadAcidBatteryMake2;
		this.leadAcidBatteryMake3 = leadAcidBatteryMake3;
		this.leadAcidBatteryLugDate1 = leadAcidBatteryLugDate1;
		this.leadAcidBatteryLugDate2 = leadAcidBatteryLugDate2;
		this.leadAcidBatteryLugDate3 = leadAcidBatteryLugDate3;
		this.leadAcidBatteryActual = leadAcidBatteryActual;
		this.batteryCommisionedMake = batteryCommisionedMake;
	}

	

	public Integer getFurnishingAssetId() {
		return furnishingAssetId;
	}



	public void setFurnishingAssetId(Integer furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}



	public String getBatteryBoxMake() {
		return this.batteryBoxMake;
	}

	public void setBatteryBoxMake(String batteryBoxMake) {
		this.batteryBoxMake = batteryBoxMake;
	}

	public String getBatteryBoxMakeActual() {
		return this.batteryBoxMakeActual;
	}

	public void setBatteryBoxMakeActual(String batteryBoxMakeActual) {
		this.batteryBoxMakeActual = batteryBoxMakeActual;
	}

	public String getMountingBatteryBoxActual() {
		return this.mountingBatteryBoxActual;
	}

	public void setMountingBatteryBoxActual(String mountingBatteryBoxActual) {
		this.mountingBatteryBoxActual = mountingBatteryBoxActual;
	}

	public String getBatteryCommisionedActual() {
		return this.batteryCommisionedActual;
	}

	public void setBatteryCommisionedActual(String batteryCommisionedActual) {
		this.batteryCommisionedActual = batteryCommisionedActual;
	}

	public String getBattery1() {
		return this.battery1;
	}

	public void setBattery1(String battery1) {
		this.battery1 = battery1;
	}

	public String getBattery2() {
		return this.battery2;
	}

	public void setBattery2(String battery2) {
		this.battery2 = battery2;
	}

	public String getBattery3() {
		return this.battery3;
	}

	public void setBattery3(String battery3) {
		this.battery3 = battery3;
	}

	public String getBattery4() {
		return this.battery4;
	}

	public void setBattery4(String battery4) {
		this.battery4 = battery4;
	}

	public String getBattery5() {
		return this.battery5;
	}

	public void setBattery5(String battery5) {
		this.battery5 = battery5;
	}

	public String getBattery6() {
		return this.battery6;
	}

	public void setBattery6(String battery6) {
		this.battery6 = battery6;
	}

	public String getBattery7() {
		return this.battery7;
	}

	public void setBattery7(String battery7) {
		this.battery7 = battery7;
	}

	public String getBattery8() {
		return this.battery8;
	}

	public void setBattery8(String battery8) {
		this.battery8 = battery8;
	}

	public String getBattery9() {
		return this.battery9;
	}

	public void setBattery9(String battery9) {
		this.battery9 = battery9;
	}

	public Date getLugDate1() {
		return this.lugDate1;
	}

	public void setLugDate1(Date lugDate1) {
		this.lugDate1 = lugDate1;
	}

	public Date getLugDate2() {
		return this.lugDate2;
	}

	public void setLugDate2(Date lugDate2) {
		this.lugDate2 = lugDate2;
	}

	public Date getLugDate3() {
		return this.lugDate3;
	}

	public void setLugDate3(Date lugDate3) {
		this.lugDate3 = lugDate3;
	}

	public Date getLugDate4() {
		return this.lugDate4;
	}

	public void setLugDate4(Date lugDate4) {
		this.lugDate4 = lugDate4;
	}

	public Date getLugDate5() {
		return this.lugDate5;
	}

	public void setLugDate5(Date lugDate5) {
		this.lugDate5 = lugDate5;
	}

	public Date getLugDate6() {
		return this.lugDate6;
	}

	public void setLugDate6(Date lugDate6) {
		this.lugDate6 = lugDate6;
	}

	public Date getLugDate7() {
		return this.lugDate7;
	}

	public void setLugDate7(Date lugDate7) {
		this.lugDate7 = lugDate7;
	}

	public Date getLugDate8() {
		return this.lugDate8;
	}

	public void setLugDate8(Date lugDate8) {
		this.lugDate8 = lugDate8;
	}

	public Date getLugDate9() {
		return this.lugDate9;
	}

	public void setLugDate9(Date lugDate9) {
		this.lugDate9 = lugDate9;
	}

	public String getLeadAcidBatteryMake() {
		return this.leadAcidBatteryMake;
	}

	public void setLeadAcidBatteryMake(String leadAcidBatteryMake) {
		this.leadAcidBatteryMake = leadAcidBatteryMake;
	}

	public String getLeadAcidBatteryMake1() {
		return this.leadAcidBatteryMake1;
	}

	public void setLeadAcidBatteryMake1(String leadAcidBatteryMake1) {
		this.leadAcidBatteryMake1 = leadAcidBatteryMake1;
	}

	public String getLeadAcidBatteryMake2() {
		return this.leadAcidBatteryMake2;
	}

	public void setLeadAcidBatteryMake2(String leadAcidBatteryMake2) {
		this.leadAcidBatteryMake2 = leadAcidBatteryMake2;
	}

	public String getLeadAcidBatteryMake3() {
		return this.leadAcidBatteryMake3;
	}

	public void setLeadAcidBatteryMake3(String leadAcidBatteryMake3) {
		this.leadAcidBatteryMake3 = leadAcidBatteryMake3;
	}

	public Date getLeadAcidBatteryLugDate1() {
		return this.leadAcidBatteryLugDate1;
	}

	public void setLeadAcidBatteryLugDate1(Date leadAcidBatteryLugDate1) {
		this.leadAcidBatteryLugDate1 = leadAcidBatteryLugDate1;
	}

	public Date getLeadAcidBatteryLugDate2() {
		return this.leadAcidBatteryLugDate2;
	}

	public void setLeadAcidBatteryLugDate2(Date leadAcidBatteryLugDate2) {
		this.leadAcidBatteryLugDate2 = leadAcidBatteryLugDate2;
	}

	public Date getLeadAcidBatteryLugDate3() {
		return this.leadAcidBatteryLugDate3;
	}

	public void setLeadAcidBatteryLugDate3(Date leadAcidBatteryLugDate3) {
		this.leadAcidBatteryLugDate3 = leadAcidBatteryLugDate3;
	}

	public String getLeadAcidBatteryActual() {
		return this.leadAcidBatteryActual;
	}

	public void setLeadAcidBatteryActual(String leadAcidBatteryActual) {
		this.leadAcidBatteryActual = leadAcidBatteryActual;
	}

	public String getBatteryCommisionedMake() {
		return this.batteryCommisionedMake;
	}

	public void setBatteryCommisionedMake(String batteryCommisionedMake) {
		this.batteryCommisionedMake = batteryCommisionedMake;
	}

}
