package beans;
// Generated 29 Jan, 2020 4:21:34 PM by Hibernate Tools 4.0.1.Final

/**
 * ElectTestParaMId generated by hbm2java
 */
public class ElectTestParaMId implements java.io.Serializable {

	private String coachType;
	private String testingType;
	private String paraName;

	public ElectTestParaMId() {
	}

	public ElectTestParaMId(String coachType, String testingType, String paraName) {
		this.coachType = coachType;
		this.testingType = testingType;
		this.paraName = paraName;
	}

	public String getCoachType() {
		return this.coachType;
	}

	public void setCoachType(String coachType) {
		this.coachType = coachType;
	}

	public String getTestingType() {
		return this.testingType;
	}

	public void setTestingType(String testingType) {
		this.testingType = testingType;
	}

	public String getParaName() {
		return this.paraName;
	}

	public void setParaName(String paraName) {
		this.paraName = paraName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ElectTestParaMId))
			return false;
		ElectTestParaMId castOther = (ElectTestParaMId) other;

		return ((this.getCoachType() == castOther.getCoachType()) || (this.getCoachType() != null
				&& castOther.getCoachType() != null && this.getCoachType().equals(castOther.getCoachType())))
				&& ((this.getTestingType() == castOther.getTestingType())
						|| (this.getTestingType() != null && castOther.getTestingType() != null
								&& this.getTestingType().equals(castOther.getTestingType())))
				&& ((this.getParaName() == castOther.getParaName()) || (this.getParaName() != null
						&& castOther.getParaName() != null && this.getParaName().equals(castOther.getParaName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCoachType() == null ? 0 : this.getCoachType().hashCode());
		result = 37 * result + (getTestingType() == null ? 0 : this.getTestingType().hashCode());
		result = 37 * result + (getParaName() == null ? 0 : this.getParaName().hashCode());
		return result;
	}

}
