package beans;
// Generated 29 Jan, 2020 5:25:13 PM by Hibernate Tools 4.0.1.Final

/**
 * ElectTestTransactionId generated by hbm2java
 */
public class ElectTestTransactionId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int furnishingAssetId;
	private String coachType;
	private String testingType;
	private String paraName;
	private String subPara;

	public ElectTestTransactionId() {
	}

	public ElectTestTransactionId(int furnishingAssetId, String coachType, String testingType, String paraName,String subPara) {
		this.furnishingAssetId = furnishingAssetId;
		this.coachType = coachType;
		this.testingType = testingType;
		this.paraName = paraName;
		this.subPara=subPara;
	}

	public int getFurnishingAssetId() {
		return this.furnishingAssetId;
	}

	public void setFurnishingAssetId(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public String getCoachType() {
		return this.coachType;
	}

	public void setCoachType(String coachType) {
		this.coachType = coachType;
	}

	public String getTestingType() {
		return this.testingType;
	}

	public void setTestingType(String testingType) {
		this.testingType = testingType;
	}

	public String getParaName() {
		return paraName;
	}

	public void setParaName(String paraName) {
		this.paraName = paraName;
	}

	public String getSubPara() {
		return subPara;
	}

	public void setSubPara(String subPara) {
		this.subPara = subPara;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ElectTestTransactionId))
			return false;
		ElectTestTransactionId castOther = (ElectTestTransactionId) other;

		return (this.getFurnishingAssetId() == castOther.getFurnishingAssetId())
				&& ((this.getCoachType() == castOther.getCoachType()) || (this.getCoachType() != null
						&& castOther.getCoachType() != null && this.getCoachType().equals(castOther.getCoachType())))
				&& ((this.getTestingType() == castOther.getTestingType())
						|| (this.getTestingType() != null && castOther.getTestingType() != null
								&& this.getTestingType().equals(castOther.getTestingType())))
				&& ((this.getParaName() == castOther.getParaName()) || (this.getParaName() != null
						&& castOther.getParaName() != null && this.getParaName().equals(castOther.getParaName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFurnishingAssetId();
		result = 37 * result + (getCoachType() == null ? 0 : this.getCoachType().hashCode());
		result = 37 * result + (getTestingType() == null ? 0 : this.getTestingType().hashCode());
		result = 37 * result + (getParaName() == null ? 0 : this.getParaName().hashCode());
		return result;
	}

}
