package beans;
// Generated 8 May, 2018 6:15:33 PM by Hibernate Tools 4.0.1.Final

/**
 * IrwisHrPltCalidMapMId generated by hbm2java
 */
public class IrwisHrPltCalidMapMId implements java.io.Serializable {

	private String plant;
	private String pcalId;

	public IrwisHrPltCalidMapMId() {
	}

	public IrwisHrPltCalidMapMId(String plant, String pcalId) {
		this.plant = plant;
		this.pcalId = pcalId;
	}

	public String getPlant() {
		return this.plant;
	}

	public void setPlant(String plant) {
		this.plant = plant;
	}

	public String getPcalId() {
		return this.pcalId;
	}

	public void setPcalId(String pcalId) {
		this.pcalId = pcalId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IrwisHrPltCalidMapMId))
			return false;
		IrwisHrPltCalidMapMId castOther = (IrwisHrPltCalidMapMId) other;

		return ((this.getPlant() == castOther.getPlant()) || (this.getPlant() != null && castOther.getPlant() != null
				&& this.getPlant().equals(castOther.getPlant())))
				&& ((this.getPcalId() == castOther.getPcalId()) || (this.getPcalId() != null
						&& castOther.getPcalId() != null && this.getPcalId().equals(castOther.getPcalId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPlant() == null ? 0 : this.getPlant().hashCode());
		result = 37 * result + (getPcalId() == null ? 0 : this.getPcalId().hashCode());
		return result;
	}

}
