package beans;
// Generated 11 May, 2018 11:03:36 AM by Hibernate Tools 4.0.1.Final

/**
 * IrwisHrPltcalM generated by hbm2java
 */
public class IrwisHrPltcalM implements java.io.Serializable {

	private IrwisHrPltcalMId id;
	private String calMonthDesc;
	private Integer calMonthCode;
	private Integer hodyStatus;
	private String hodyDtype;

	public IrwisHrPltcalM() {
	}

	public IrwisHrPltcalM(IrwisHrPltcalMId id) {
		this.id = id;
	}

	public IrwisHrPltcalM(IrwisHrPltcalMId id, String calMonthDesc, Integer calMonthCode, Integer hodyStatus,
			String hodyDtype) {
		this.id = id;
		this.calMonthDesc = calMonthDesc;
		this.calMonthCode = calMonthCode;
		this.hodyStatus = hodyStatus;
		this.hodyDtype = hodyDtype;
	}

	public IrwisHrPltcalMId getId() {
		return this.id;
	}

	public void setId(IrwisHrPltcalMId id) {
		this.id = id;
	}

	public String getCalMonthDesc() {
		return this.calMonthDesc;
	}

	public void setCalMonthDesc(String calMonthDesc) {
		this.calMonthDesc = calMonthDesc;
	}

	public Integer getCalMonthCode() {
		return this.calMonthCode;
	}

	public void setCalMonthCode(Integer calMonthCode) {
		this.calMonthCode = calMonthCode;
	}

	public Integer getHodyStatus() {
		return this.hodyStatus;
	}

	public void setHodyStatus(Integer hodyStatus) {
		this.hodyStatus = hodyStatus;
	}

	public String getHodyDtype() {
		return this.hodyDtype;
	}

	public void setHodyDtype(String hodyDtype) {
		this.hodyDtype = hodyDtype;
	}

}
