package beans;
// Generated 11 May, 2018 11:03:36 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * IrwisHrPltLieuCalMId generated by hbm2java
 */
public class IrwisHrPltLieuCalMId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String pcalId;
	private String plant;
	private Date calHodyDate;
	private String hodyCode;
	private Date lieuDate;

	public IrwisHrPltLieuCalMId() {
	}

	public IrwisHrPltLieuCalMId(String pcalId, String plant, Date calHodyDate, String hodyCode, Date lieuDate) {
		this.pcalId = pcalId;
		this.plant = plant;
		this.calHodyDate = calHodyDate;
		this.hodyCode = hodyCode;
		this.lieuDate = lieuDate;
	}

	public String getPcalId() {
		return this.pcalId;
	}

	public void setPcalId(String pcalId) {
		this.pcalId = pcalId;
	}

	public String getPlant() {
		return this.plant;
	}

	public void setPlant(String plant) {
		this.plant = plant;
	}

	public Date getCalHodyDate() {
		return this.calHodyDate;
	}

	public void setCalHodyDate(Date calHodyDate) {
		this.calHodyDate = calHodyDate;
	}

	public String getHodyCode() {
		return this.hodyCode;
	}

	public void setHodyCode(String hodyCode) {
		this.hodyCode = hodyCode;
	}

	public Date getLieuDate() {
		return this.lieuDate;
	}

	public void setLieuDate(Date lieuDate) {
		this.lieuDate = lieuDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IrwisHrPltLieuCalMId))
			return false;
		IrwisHrPltLieuCalMId castOther = (IrwisHrPltLieuCalMId) other;

		return ((this.getPcalId() == castOther.getPcalId()) || (this.getPcalId() != null
				&& castOther.getPcalId() != null && this.getPcalId().equals(castOther.getPcalId())))
				&& ((this.getPlant() == castOther.getPlant()) || (this.getPlant() != null
						&& castOther.getPlant() != null && this.getPlant().equals(castOther.getPlant())))
				&& ((this.getCalHodyDate() == castOther.getCalHodyDate())
						|| (this.getCalHodyDate() != null && castOther.getCalHodyDate() != null
								&& this.getCalHodyDate().equals(castOther.getCalHodyDate())))
				&& ((this.getHodyCode() == castOther.getHodyCode()) || (this.getHodyCode() != null
						&& castOther.getHodyCode() != null && this.getHodyCode().equals(castOther.getHodyCode())))
				&& ((this.getLieuDate() == castOther.getLieuDate()) || (this.getLieuDate() != null
						&& castOther.getLieuDate() != null && this.getLieuDate().equals(castOther.getLieuDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPcalId() == null ? 0 : this.getPcalId().hashCode());
		result = 37 * result + (getPlant() == null ? 0 : this.getPlant().hashCode());
		result = 37 * result + (getCalHodyDate() == null ? 0 : this.getCalHodyDate().hashCode());
		result = 37 * result + (getHodyCode() == null ? 0 : this.getHodyCode().hashCode());
		result = 37 * result + (getLieuDate() == null ? 0 : this.getLieuDate().hashCode());
		return result;
	}

}
