package beans;
// Generated 8 May, 2018 6:15:33 PM by Hibernate Tools 4.0.1.Final

/**
 * IrwisHrPubhodyM generated by hbm2java
 */
public class IrwisHrPubhodyM implements java.io.Serializable {

	private String hodyCode;
	private String hodyType;
	private String hodyDesc;
	private String hodyDtype;
	private Character allowFlag;
	private Integer seq;
	

	public IrwisHrPubhodyM() {
	}

	public IrwisHrPubhodyM(String hodyCode, String hodyType, String hodyDesc) {
		this.hodyCode = hodyCode;
		this.hodyType = hodyType;
		this.hodyDesc = hodyDesc;
	}

	public IrwisHrPubhodyM(String hodyCode, String hodyType, String hodyDesc, String hodyDtype, Character allowFlag, Integer seq) {
		this.hodyCode = hodyCode;
		this.hodyType = hodyType;
		this.hodyDesc = hodyDesc;
		this.hodyDtype = hodyDtype;
		this.allowFlag = allowFlag;
		this.seq= seq;
		
	}

	public String getHodyCode() {
		return this.hodyCode;
	}

	public void setHodyCode(String hodyCode) {
		this.hodyCode = hodyCode;
	}

	public String getHodyType() {
		return this.hodyType;
	}

	public void setHodyType(String hodyType) {
		this.hodyType = hodyType;
	}

	public String getHodyDesc() {
		return this.hodyDesc;
	}

	public void setHodyDesc(String hodyDesc) {
		this.hodyDesc = hodyDesc;
	}

	public String getHodyDtype() {
		return this.hodyDtype;
	}

	public void setHodyDtype(String hodyDtype) {
		this.hodyDtype = hodyDtype;
	}

	public Character getAllowFlag() {
		return this.allowFlag;
	}

	public void setAllowFlag(Character allowFlag) {
		this.allowFlag = allowFlag;
	}

	public Integer getSeq() {
		return seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

		

}
