package beans;
// Generated 12 Mar, 2020 1:13:15 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * QciAirBrakeTrans generated by hbm2java
 */
public class QciAirBrakeTrans implements java.io.Serializable {

	private int furnishingAssetId;
	private String releasingDeviceChuckLoose;
	private String releasingDeviceRodFitted;
	private String brakeIndicatorFitted;
	private String airHosepipeAngleCookLoose;
	private String emergencyPullboxCoverFitted;
	private String lavatoryAirPipeClampFitted;
	private String alarmPipeClampFitted;
	private String testingObservationRemark;
	private String entryBy;
	private Date entryTime;

	public QciAirBrakeTrans() {
	}

	public QciAirBrakeTrans(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public QciAirBrakeTrans(int furnishingAssetId, String releasingDeviceChuckLoose, String releasingDeviceRodFitted,
			String brakeIndicatorFitted, String airHosepipeAngleCookLoose, String emergencyPullboxCoverFitted,
			String lavatoryAirPipeClampFitted, String alarmPipeClampFitted, String testingObservationRemark,
			String entryBy, Date entryTime) {
		this.furnishingAssetId = furnishingAssetId;
		this.releasingDeviceChuckLoose = releasingDeviceChuckLoose;
		this.releasingDeviceRodFitted = releasingDeviceRodFitted;
		this.brakeIndicatorFitted = brakeIndicatorFitted;
		this.airHosepipeAngleCookLoose = airHosepipeAngleCookLoose;
		this.emergencyPullboxCoverFitted = emergencyPullboxCoverFitted;
		this.lavatoryAirPipeClampFitted = lavatoryAirPipeClampFitted;
		this.alarmPipeClampFitted = alarmPipeClampFitted;
		this.testingObservationRemark = testingObservationRemark;
		this.entryBy = entryBy;
		this.entryTime = entryTime;
	}

	public int getFurnishingAssetId() {
		return this.furnishingAssetId;
	}

	public void setFurnishingAssetId(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public String getReleasingDeviceChuckLoose() {
		return this.releasingDeviceChuckLoose;
	}

	public void setReleasingDeviceChuckLoose(String releasingDeviceChuckLoose) {
		this.releasingDeviceChuckLoose = releasingDeviceChuckLoose;
	}

	public String getReleasingDeviceRodFitted() {
		return this.releasingDeviceRodFitted;
	}

	public void setReleasingDeviceRodFitted(String releasingDeviceRodFitted) {
		this.releasingDeviceRodFitted = releasingDeviceRodFitted;
	}

	public String getBrakeIndicatorFitted() {
		return this.brakeIndicatorFitted;
	}

	public void setBrakeIndicatorFitted(String brakeIndicatorFitted) {
		this.brakeIndicatorFitted = brakeIndicatorFitted;
	}

	public String getAirHosepipeAngleCookLoose() {
		return this.airHosepipeAngleCookLoose;
	}

	public void setAirHosepipeAngleCookLoose(String airHosepipeAngleCookLoose) {
		this.airHosepipeAngleCookLoose = airHosepipeAngleCookLoose;
	}

	public String getEmergencyPullboxCoverFitted() {
		return this.emergencyPullboxCoverFitted;
	}

	public void setEmergencyPullboxCoverFitted(String emergencyPullboxCoverFitted) {
		this.emergencyPullboxCoverFitted = emergencyPullboxCoverFitted;
	}

	public String getLavatoryAirPipeClampFitted() {
		return this.lavatoryAirPipeClampFitted;
	}

	public void setLavatoryAirPipeClampFitted(String lavatoryAirPipeClampFitted) {
		this.lavatoryAirPipeClampFitted = lavatoryAirPipeClampFitted;
	}

	public String getAlarmPipeClampFitted() {
		return this.alarmPipeClampFitted;
	}

	public void setAlarmPipeClampFitted(String alarmPipeClampFitted) {
		this.alarmPipeClampFitted = alarmPipeClampFitted;
	}

	public String getTestingObservationRemark() {
		return this.testingObservationRemark;
	}

	public void setTestingObservationRemark(String testingObservationRemark) {
		this.testingObservationRemark = testingObservationRemark;
	}

	public String getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(String entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

}
