package beans;
// Generated 12 Mar, 2020 1:06:30 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * QciCoachCleaningTrans generated by hbm2java
 */
public class QciCoachCleaningTrans implements java.io.Serializable {

	private int furnishingAssetId;
	private String floorDirty;
	private String lavatoryDirty;
	private String ceilingDirty;
	private String seatBerthDirty;
	private String panelDirty;
	private String storeroomPantryLinenDirty;
	private String railsSlidingDoorDirty;
	private String windowGlassDirty;
	private String plasticFilmRemoved;
	private String doorDirty;
	private String testingObservationRemark;
	private String entryBy;
	private Date entryTime;

	public QciCoachCleaningTrans() {
	}

	public QciCoachCleaningTrans(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public QciCoachCleaningTrans(int furnishingAssetId, String floorDirty, String lavatoryDirty, String ceilingDirty,
			String seatBerthDirty, String panelDirty, String storeroomPantryLinenDirty, String railsSlidingDoorDirty,
			String windowGlassDirty, String plasticFilmRemoved, String doorDirty, String testingObservationRemark,
			String entryBy, Date entryTime) {
		this.furnishingAssetId = furnishingAssetId;
		this.floorDirty = floorDirty;
		this.lavatoryDirty = lavatoryDirty;
		this.ceilingDirty = ceilingDirty;
		this.seatBerthDirty = seatBerthDirty;
		this.panelDirty = panelDirty;
		this.storeroomPantryLinenDirty = storeroomPantryLinenDirty;
		this.railsSlidingDoorDirty = railsSlidingDoorDirty;
		this.windowGlassDirty = windowGlassDirty;
		this.plasticFilmRemoved = plasticFilmRemoved;
		this.doorDirty = doorDirty;
		this.testingObservationRemark = testingObservationRemark;
		this.entryBy = entryBy;
		this.entryTime = entryTime;
	}

	public int getFurnishingAssetId() {
		return this.furnishingAssetId;
	}

	public void setFurnishingAssetId(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public String getFloorDirty() {
		return this.floorDirty;
	}

	public void setFloorDirty(String floorDirty) {
		this.floorDirty = floorDirty;
	}

	public String getLavatoryDirty() {
		return this.lavatoryDirty;
	}

	public void setLavatoryDirty(String lavatoryDirty) {
		this.lavatoryDirty = lavatoryDirty;
	}

	public String getCeilingDirty() {
		return this.ceilingDirty;
	}

	public void setCeilingDirty(String ceilingDirty) {
		this.ceilingDirty = ceilingDirty;
	}

	public String getSeatBerthDirty() {
		return this.seatBerthDirty;
	}

	public void setSeatBerthDirty(String seatBerthDirty) {
		this.seatBerthDirty = seatBerthDirty;
	}

	public String getPanelDirty() {
		return this.panelDirty;
	}

	public void setPanelDirty(String panelDirty) {
		this.panelDirty = panelDirty;
	}

	public String getStoreroomPantryLinenDirty() {
		return this.storeroomPantryLinenDirty;
	}

	public void setStoreroomPantryLinenDirty(String storeroomPantryLinenDirty) {
		this.storeroomPantryLinenDirty = storeroomPantryLinenDirty;
	}

	public String getRailsSlidingDoorDirty() {
		return this.railsSlidingDoorDirty;
	}

	public void setRailsSlidingDoorDirty(String railsSlidingDoorDirty) {
		this.railsSlidingDoorDirty = railsSlidingDoorDirty;
	}

	public String getWindowGlassDirty() {
		return this.windowGlassDirty;
	}

	public void setWindowGlassDirty(String windowGlassDirty) {
		this.windowGlassDirty = windowGlassDirty;
	}

	public String getPlasticFilmRemoved() {
		return this.plasticFilmRemoved;
	}

	public void setPlasticFilmRemoved(String plasticFilmRemoved) {
		this.plasticFilmRemoved = plasticFilmRemoved;
	}

	public String getDoorDirty() {
		return this.doorDirty;
	}

	public void setDoorDirty(String doorDirty) {
		this.doorDirty = doorDirty;
	}

	public String getTestingObservationRemark() {
		return this.testingObservationRemark;
	}

	public void setTestingObservationRemark(String testingObservationRemark) {
		this.testingObservationRemark = testingObservationRemark;
	}

	public String getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(String entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

}
