package beans;
// Generated 12 Mar, 2020 1:06:30 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * QciCoachLoweringTrans generated by hbm2java
 */
public class QciCoachLoweringTrans implements java.io.Serializable {

	private int furnishingAssetId;
	private String testingObservationRemark;
	private String entryBy;
	private Date entryTime;

	public QciCoachLoweringTrans() {
	}

	public QciCoachLoweringTrans(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public QciCoachLoweringTrans(int furnishingAssetId, String testingObservationRemark, String entryBy,
			Date entryTime) {
		this.furnishingAssetId = furnishingAssetId;
		this.testingObservationRemark = testingObservationRemark;
		this.entryBy = entryBy;
		this.entryTime = entryTime;
	}

	public int getFurnishingAssetId() {
		return this.furnishingAssetId;
	}

	public void setFurnishingAssetId(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public String getTestingObservationRemark() {
		return this.testingObservationRemark;
	}

	public void setTestingObservationRemark(String testingObservationRemark) {
		this.testingObservationRemark = testingObservationRemark;
	}

	public String getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(String entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

}
