package beans;
// Generated 6 Mar, 2020 3:39:33 PM by Hibernate Tools 4.0.1.Final
 
import java.util.Date;

/**
 * QciFPvcTrans generated by hbm2java
 */
public class QciFPvcTrans implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int furnishingAssetId;
	private String docNo;
	private String docRevNo;
	private Date docDate;
	private Date dateOfTesting;
	private String shiftOfTesting;
	private String footPlateJam;
	private String movementHard;
	private String footPlateSpringHardware;
	private String footPlateSideRubberLoose;
	private String footPlateSideRubberMissing;
	private String tailLampFitted;
	private String tailLampHardwareMissing;
	private String tailLampWelding;
	private String footStepLoose;
	private String footStepHardware;
	private String fitmentEntranceHandRail;
	private String footStepRusted;
	private String footStepTaperFitted;
	private String stepRailScrewSited;
	private String stepRailScrewMissing;
	private String chequerSheetNotSealed;
	private String chequerSheetRouglySealed;
	private String roughlyCuttingChequerSheet;
	private String chequerSheetNotSitedCorner;
	private String chequerSheetScrewSited;
	private String chequerSheetScrewMissing;
	private String chequerSheetScrewLoose;
	private String doorStopperNotFitted;
	private String endwallSafetyHandleFitted;
	private String endwallSafetyHandleLoose;
	private String endwallSafetyHandleMissing;
	private String pvcCuttingPastingEndwalldoor;
	private String pvcCuttingPastingLavatorydoor;
	private String pvcJointWeldingCabinSide;
	private String pvcJointWeldingNonCabinSide;
	private String airBubblePvc;
	private String floorLevelCorridorArea;
	private String uicVestibuleSited;
	private String uicVestibuleTaper;
	private String uicVestibuleCracked;
	private String foamFamSealingNotDone;
	private String foamFamSealingRoughlyDone;
	private String fitmentDoorHandle;
	private String testingObservationRemark;
	private Integer qcifpvcflag;
	private Integer qciPartitionFrameFlag;
	private Integer qciPanelFlag;
	private Integer qciWindowCellingFlag;
	private Integer qciMouldingFlag;
	private Integer qciSeatBerthFlag;
	private Integer qciLavatoryFlag;
	private Integer qciPlumbingFlag;
	private Integer qciAirBrakeFlag;
	private Integer qciCoachLoweringFlag;
	private Integer qciPaintFlag;
	private Integer qciCoachCleaningFlag;
	 

	public QciFPvcTrans() {
	}
		

	public QciFPvcTrans(int furnishingAssetId, String docNo) {
		this.furnishingAssetId = furnishingAssetId;
		/*this.docNo = docNo;*/
	}

	public QciFPvcTrans(int furnishingAssetId,String docNo, String docRevNo, Date docDate, Date dateOfTesting,
			String shiftOfTesting, String footPlateJam, String movementHard, String footPlateSpringHardware,
			String footPlateSideRubberLoose, String footPlateSideRubberMissing, String tailLampFitted,
			String tailLampHardwareMissing, String tailLampWelding, String footStepLoose, String footStepHardware,
			String fitmentEntranceHandRail, String footStepRusted, String footStepTaperFitted,
			String stepRailScrewSited, String stepRailScrewMissing, String chequerSheetNotSealed,
			String chequerSheetRouglySealed, String roughlyCuttingChequerSheet, String chequerSheetNotSitedCorner,
			String chequerSheetScrewSited, String chequerSheetScrewMissing, String chequerSheetScrewLoose,
			String doorStopperNotFitted, String endwallSafetyHandleFitted, String endwallSafetyHandleLoose,
			String endwallSafetyHandleMissing, String pvcCuttingPastingEndwalldoor,
			String pvcCuttingPastingLavatorydoor, String pvcJointWeldingCabinSide, String pvcJointWeldingNonCabinSide,
			String airBubblePvc, String floorLevelCorridorArea, String uicVestibuleSited, String uicVestibuleTaper,
			String uicVestibuleCracked, String foamFamSealingNotDone, String foamFamSealingRoughlyDone,
			String fitmentDoorHandle, String testingObservationRemark,Integer qcifpvcflag,Integer qciPartitionFrameFlag,Integer qciPanelFlag,
			Integer qciWindowCellingFlag,Integer qciMouldingFlag,Integer qciSeatBerthFlag,Integer qciLavatoryFlag,
			Integer qciPlumbingFlag,Integer qciAirBrakeFlag,Integer qciCoachLoweringFlag,Integer qciPaintFlag,Integer qciCoachCleaningFlag) {
		this.furnishingAssetId = furnishingAssetId;
		this.docNo = docNo;
		this.docRevNo = docRevNo;
		this.docDate = docDate;
		this.dateOfTesting = dateOfTesting;
		this.shiftOfTesting = shiftOfTesting;
		this.footPlateJam = footPlateJam;
		this.movementHard = movementHard;
		this.footPlateSpringHardware = footPlateSpringHardware;
		this.footPlateSideRubberLoose = footPlateSideRubberLoose;
		this.footPlateSideRubberMissing = footPlateSideRubberMissing;
		this.tailLampFitted = tailLampFitted;
		this.tailLampHardwareMissing = tailLampHardwareMissing;
		this.tailLampWelding = tailLampWelding;
		this.footStepLoose = footStepLoose;
		this.footStepHardware = footStepHardware;
		this.fitmentEntranceHandRail = fitmentEntranceHandRail;
		this.footStepRusted = footStepRusted;
		this.footStepTaperFitted = footStepTaperFitted;
		this.stepRailScrewSited = stepRailScrewSited;
		this.stepRailScrewMissing = stepRailScrewMissing;
		this.chequerSheetNotSealed = chequerSheetNotSealed;
		this.chequerSheetRouglySealed = chequerSheetRouglySealed;
		this.roughlyCuttingChequerSheet = roughlyCuttingChequerSheet;
		this.chequerSheetNotSitedCorner = chequerSheetNotSitedCorner;
		this.chequerSheetScrewSited = chequerSheetScrewSited;
		this.chequerSheetScrewMissing = chequerSheetScrewMissing;
		this.chequerSheetScrewLoose = chequerSheetScrewLoose;
		this.doorStopperNotFitted = doorStopperNotFitted;
		this.endwallSafetyHandleFitted = endwallSafetyHandleFitted;
		this.endwallSafetyHandleLoose = endwallSafetyHandleLoose;
		this.endwallSafetyHandleMissing = endwallSafetyHandleMissing;
		this.pvcCuttingPastingEndwalldoor = pvcCuttingPastingEndwalldoor;
		this.pvcCuttingPastingLavatorydoor = pvcCuttingPastingLavatorydoor;
		this.pvcJointWeldingCabinSide = pvcJointWeldingCabinSide;
		this.pvcJointWeldingNonCabinSide = pvcJointWeldingNonCabinSide;
		this.airBubblePvc = airBubblePvc;
		this.floorLevelCorridorArea = floorLevelCorridorArea;
		this.uicVestibuleSited = uicVestibuleSited;
		this.uicVestibuleTaper = uicVestibuleTaper;
		this.uicVestibuleCracked = uicVestibuleCracked;
		this.foamFamSealingNotDone = foamFamSealingNotDone;
		this.foamFamSealingRoughlyDone = foamFamSealingRoughlyDone;
		this.fitmentDoorHandle = fitmentDoorHandle;
		this.testingObservationRemark = testingObservationRemark;
		this.qcifpvcflag=qcifpvcflag;
		this.qciPartitionFrameFlag=qciPartitionFrameFlag;
		this.qciPanelFlag=qciPanelFlag;
		this.qciWindowCellingFlag=qciWindowCellingFlag;
		this.qciMouldingFlag=qciMouldingFlag;
		this.qciSeatBerthFlag=qciSeatBerthFlag;
		this.qciLavatoryFlag=qciLavatoryFlag;
		this.qciPlumbingFlag=qciPlumbingFlag;
		this.qciAirBrakeFlag=qciAirBrakeFlag;
		this.qciCoachLoweringFlag=qciCoachLoweringFlag;
		this.qciPaintFlag=qciPaintFlag;
		this.qciCoachCleaningFlag=qciCoachCleaningFlag;
	}

	public int getFurnishingAssetId() {
		return this.furnishingAssetId;
	}

	public void setFurnishingAssetId(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public String getDocNo() {
		return this.docNo;
	}

	public void setDocNo(String docNo) {
		this.docNo = docNo;
	}

	public String getDocRevNo() {
		return this.docRevNo;
	}

	public void setDocRevNo(String docRevNo) {
		this.docRevNo = docRevNo;
	}

	public Date getDocDate() {
		return this.docDate;
	}

	public void setDocDate(Date docDate) {
		this.docDate = docDate;
	}

	public Date getDateOfTesting() {
		return this.dateOfTesting;
	}

	public void setDateOfTesting(Date dateOfTesting) {
		this.dateOfTesting = dateOfTesting;
	}

	public String getShiftOfTesting() {
		return this.shiftOfTesting;
	}

	public void setShiftOfTesting(String shiftOfTesting) {
		this.shiftOfTesting = shiftOfTesting;
	}

	public String getFootPlateJam() {
		return this.footPlateJam;
	}

	public void setFootPlateJam(String footPlateJam) {
		this.footPlateJam = footPlateJam;
	}

	public String getMovementHard() {
		return this.movementHard;
	}

	public void setMovementHard(String movementHard) {
		this.movementHard = movementHard;
	}

	public String getFootPlateSpringHardware() {
		return this.footPlateSpringHardware;
	}

	public void setFootPlateSpringHardware(String footPlateSpringHardware) {
		this.footPlateSpringHardware = footPlateSpringHardware;
	}

	public String getFootPlateSideRubberLoose() {
		return this.footPlateSideRubberLoose;
	}

	public void setFootPlateSideRubberLoose(String footPlateSideRubberLoose) {
		this.footPlateSideRubberLoose = footPlateSideRubberLoose;
	}

	public String getFootPlateSideRubberMissing() {
		return this.footPlateSideRubberMissing;
	}

	public void setFootPlateSideRubberMissing(String footPlateSideRubberMissing) {
		this.footPlateSideRubberMissing = footPlateSideRubberMissing;
	}

	public String getTailLampFitted() {
		return this.tailLampFitted;
	}

	public void setTailLampFitted(String tailLampFitted) {
		this.tailLampFitted = tailLampFitted;
	}

	public String getTailLampHardwareMissing() {
		return this.tailLampHardwareMissing;
	}

	public void setTailLampHardwareMissing(String tailLampHardwareMissing) {
		this.tailLampHardwareMissing = tailLampHardwareMissing;
	}

	public String getTailLampWelding() {
		return this.tailLampWelding;
	}

	public void setTailLampWelding(String tailLampWelding) {
		this.tailLampWelding = tailLampWelding;
	}

	public String getFootStepLoose() {
		return this.footStepLoose;
	}

	public void setFootStepLoose(String footStepLoose) {
		this.footStepLoose = footStepLoose;
	}

	public String getFootStepHardware() {
		return this.footStepHardware;
	}

	public void setFootStepHardware(String footStepHardware) {
		this.footStepHardware = footStepHardware;
	}

	public String getFitmentEntranceHandRail() {
		return this.fitmentEntranceHandRail;
	}

	public void setFitmentEntranceHandRail(String fitmentEntranceHandRail) {
		this.fitmentEntranceHandRail = fitmentEntranceHandRail;
	}

	public String getFootStepRusted() {
		return this.footStepRusted;
	}

	public void setFootStepRusted(String footStepRusted) {
		this.footStepRusted = footStepRusted;
	}

	public String getFootStepTaperFitted() {
		return this.footStepTaperFitted;
	}

	public void setFootStepTaperFitted(String footStepTaperFitted) {
		this.footStepTaperFitted = footStepTaperFitted;
	}

	public String getStepRailScrewSited() {
		return this.stepRailScrewSited;
	}

	public void setStepRailScrewSited(String stepRailScrewSited) {
		this.stepRailScrewSited = stepRailScrewSited;
	}

	public String getStepRailScrewMissing() {
		return this.stepRailScrewMissing;
	}

	public void setStepRailScrewMissing(String stepRailScrewMissing) {
		this.stepRailScrewMissing = stepRailScrewMissing;
	}

	public String getChequerSheetNotSealed() {
		return this.chequerSheetNotSealed;
	}

	public void setChequerSheetNotSealed(String chequerSheetNotSealed) {
		this.chequerSheetNotSealed = chequerSheetNotSealed;
	}

	public String getChequerSheetRouglySealed() {
		return this.chequerSheetRouglySealed;
	}

	public void setChequerSheetRouglySealed(String chequerSheetRouglySealed) {
		this.chequerSheetRouglySealed = chequerSheetRouglySealed;
	}

	public String getRoughlyCuttingChequerSheet() {
		return this.roughlyCuttingChequerSheet;
	}

	public void setRoughlyCuttingChequerSheet(String roughlyCuttingChequerSheet) {
		this.roughlyCuttingChequerSheet = roughlyCuttingChequerSheet;
	}

	public String getChequerSheetNotSitedCorner() {
		return this.chequerSheetNotSitedCorner;
	}

	public void setChequerSheetNotSitedCorner(String chequerSheetNotSitedCorner) {
		this.chequerSheetNotSitedCorner = chequerSheetNotSitedCorner;
	}

	public String getChequerSheetScrewSited() {
		return this.chequerSheetScrewSited;
	}

	public void setChequerSheetScrewSited(String chequerSheetScrewSited) {
		this.chequerSheetScrewSited = chequerSheetScrewSited;
	}

	public String getChequerSheetScrewMissing() {
		return this.chequerSheetScrewMissing;
	}

	public void setChequerSheetScrewMissing(String chequerSheetScrewMissing) {
		this.chequerSheetScrewMissing = chequerSheetScrewMissing;
	}

	public String getChequerSheetScrewLoose() {
		return this.chequerSheetScrewLoose;
	}

	public void setChequerSheetScrewLoose(String chequerSheetScrewLoose) {
		this.chequerSheetScrewLoose = chequerSheetScrewLoose;
	}

	public String getDoorStopperNotFitted() {
		return this.doorStopperNotFitted;
	}

	public void setDoorStopperNotFitted(String doorStopperNotFitted) {
		this.doorStopperNotFitted = doorStopperNotFitted;
	}

	public String getEndwallSafetyHandleFitted() {
		return this.endwallSafetyHandleFitted;
	}

	public void setEndwallSafetyHandleFitted(String endwallSafetyHandleFitted) {
		this.endwallSafetyHandleFitted = endwallSafetyHandleFitted;
	}

	public String getEndwallSafetyHandleLoose() {
		return this.endwallSafetyHandleLoose;
	}

	public void setEndwallSafetyHandleLoose(String endwallSafetyHandleLoose) {
		this.endwallSafetyHandleLoose = endwallSafetyHandleLoose;
	}

	public String getEndwallSafetyHandleMissing() {
		return this.endwallSafetyHandleMissing;
	}

	public void setEndwallSafetyHandleMissing(String endwallSafetyHandleMissing) {
		this.endwallSafetyHandleMissing = endwallSafetyHandleMissing;
	}

	public String getPvcCuttingPastingEndwalldoor() {
		return this.pvcCuttingPastingEndwalldoor;
	}

	public void setPvcCuttingPastingEndwalldoor(String pvcCuttingPastingEndwalldoor) {
		this.pvcCuttingPastingEndwalldoor = pvcCuttingPastingEndwalldoor;
	}

	public String getPvcCuttingPastingLavatorydoor() {
		return this.pvcCuttingPastingLavatorydoor;
	}

	public void setPvcCuttingPastingLavatorydoor(String pvcCuttingPastingLavatorydoor) {
		this.pvcCuttingPastingLavatorydoor = pvcCuttingPastingLavatorydoor;
	}

	public String getPvcJointWeldingCabinSide() {
		return this.pvcJointWeldingCabinSide;
	}

	public void setPvcJointWeldingCabinSide(String pvcJointWeldingCabinSide) {
		this.pvcJointWeldingCabinSide = pvcJointWeldingCabinSide;
	}

	public String getPvcJointWeldingNonCabinSide() {
		return this.pvcJointWeldingNonCabinSide;
	}

	public void setPvcJointWeldingNonCabinSide(String pvcJointWeldingNonCabinSide) {
		this.pvcJointWeldingNonCabinSide = pvcJointWeldingNonCabinSide;
	}

	public String getAirBubblePvc() {
		return this.airBubblePvc;
	}

	public void setAirBubblePvc(String airBubblePvc) {
		this.airBubblePvc = airBubblePvc;
	}

	public String getFloorLevelCorridorArea() {
		return this.floorLevelCorridorArea;
	}

	public void setFloorLevelCorridorArea(String floorLevelCorridorArea) {
		this.floorLevelCorridorArea = floorLevelCorridorArea;
	}

	public String getUicVestibuleSited() {
		return this.uicVestibuleSited;
	}

	public void setUicVestibuleSited(String uicVestibuleSited) {
		this.uicVestibuleSited = uicVestibuleSited;
	}

	public String getUicVestibuleTaper() {
		return this.uicVestibuleTaper;
	}

	public void setUicVestibuleTaper(String uicVestibuleTaper) {
		this.uicVestibuleTaper = uicVestibuleTaper;
	}

	public String getUicVestibuleCracked() {
		return this.uicVestibuleCracked;
	}

	public void setUicVestibuleCracked(String uicVestibuleCracked) {
		this.uicVestibuleCracked = uicVestibuleCracked;
	}

	public String getFoamFamSealingNotDone() {
		return this.foamFamSealingNotDone;
	}

	public void setFoamFamSealingNotDone(String foamFamSealingNotDone) {
		this.foamFamSealingNotDone = foamFamSealingNotDone;
	}

	public String getFoamFamSealingRoughlyDone() {
		return this.foamFamSealingRoughlyDone;
	}

	public void setFoamFamSealingRoughlyDone(String foamFamSealingRoughlyDone) {
		this.foamFamSealingRoughlyDone = foamFamSealingRoughlyDone;
	}

	public String getFitmentDoorHandle() {
		return this.fitmentDoorHandle;
	}

	public void setFitmentDoorHandle(String fitmentDoorHandle) {
		this.fitmentDoorHandle = fitmentDoorHandle;
	}

	public String getTestingObservationRemark() {
		return this.testingObservationRemark;
	}

	public void setTestingObservationRemark(String testingObservationRemark) {
		this.testingObservationRemark = testingObservationRemark;
	}


	public Integer getQcifpvcflag() {
		return qcifpvcflag;
	}


	public void setQcifpvcflag(Integer qcifpvcflag) {
		this.qcifpvcflag = qcifpvcflag;
	}


	public Integer getQciPartitionFrameFlag() {
		return qciPartitionFrameFlag;
	}


	public void setQciPartitionFrameFlag(Integer qciPartitionFrameFlag) {
		this.qciPartitionFrameFlag = qciPartitionFrameFlag;
	}


	public Integer getQciPanelFlag() {
		return qciPanelFlag;
	}


	public void setQciPanelFlag(Integer qciPanelFlag) {
		this.qciPanelFlag = qciPanelFlag;
	}


	public Integer getQciWindowCellingFlag() {
		return qciWindowCellingFlag;
	}


	public void setQciWindowCellingFlag(Integer qciWindowCellingFlag) {
		this.qciWindowCellingFlag = qciWindowCellingFlag;
	}


	public Integer getQciMouldingFlag() {
		return qciMouldingFlag;
	}


	public void setQciMouldingFlag(Integer qciMouldingFlag) {
		this.qciMouldingFlag = qciMouldingFlag;
	}


	public Integer getQciSeatBerthFlag() {
		return qciSeatBerthFlag;
	}


	public void setQciSeatBerthFlag(Integer qciSeatBerthFlag) {
		this.qciSeatBerthFlag = qciSeatBerthFlag;
	}


	public Integer getQciLavatoryFlag() {
		return qciLavatoryFlag;
	}


	public void setQciLavatoryFlag(Integer qciLavatoryFlag) {
		this.qciLavatoryFlag = qciLavatoryFlag;
	}


	public Integer getQciPlumbingFlag() {
		return qciPlumbingFlag;
	}


	public void setQciPlumbingFlag(Integer qciPlumbingFlag) {
		this.qciPlumbingFlag = qciPlumbingFlag;
	}


	public Integer getQciAirBrakeFlag() {
		return qciAirBrakeFlag;
	}


	public void setQciAirBrakeFlag(Integer qciAirBrakeFlag) {
		this.qciAirBrakeFlag = qciAirBrakeFlag;
	}


	public Integer getQciCoachLoweringFlag() {
		return qciCoachLoweringFlag;
	}


	public void setQciCoachLoweringFlag(Integer qciCoachLoweringFlag) {
		this.qciCoachLoweringFlag = qciCoachLoweringFlag;
	}


	public Integer getQciPaintFlag() {
		return qciPaintFlag;
	}


	public void setQciPaintFlag(Integer qciPaintFlag) {
		this.qciPaintFlag = qciPaintFlag;
	}


	public Integer getQciCoachCleaningFlag() {
		return qciCoachCleaningFlag;
	}


	public void setQciCoachCleaningFlag(Integer qciCoachCleaningFlag) {
		this.qciCoachCleaningFlag = qciCoachCleaningFlag;
	}

	


	
}
