package beans;
// Generated 12 Mar, 2020 1:06:30 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * QciLavatoryTrans generated by hbm2java
 */
public class QciLavatoryTrans implements java.io.Serializable {

	private int furnishingAssetId;
	private String loroPipeLoose;
	private String loroPipeMissing;
	private String attachmentWailHingeLoose;
	private String attachmentWailHingeMissing;
	private String attachmentWailHingeDent;
	private String attachmentWallTowerScrewMissing;
	private String attachmentWallTowerBoltDamage;
	private String towerBoltFitted;
	private String towerBoltHole;
	private String soapCaseScrewMissing;
	private String soapCaseScrewLoose;
	private String soapCaseScrewTaper;
	private String lavWashBasinSealed;
	private String lavWashBasinOutside;
	private String avWashBasinInside;
	private String lavWashBasinRoughlySealed;
	private String lavWashBasinRoughlyOutside;
	private String lavWashBasinRoughlyInside;
	private String dustbinBoxProvided;
	private String dustbinBoxUnlocked;
	private String dustbinBktLoose;
	private String dustbikBktScrewMissing;
	private String steelDustbinBktLoose;
	private String wasteBinLoose;
	private String wasteBinScrewMissing;
	private String wasteBinScrewDent;
	private String wasteBinCoverPlateRusted;
	private String wasteBinCoverMagnet;
	private String lessScrewWasteBinCover;
	private String lessScrewWasteBinCoverGrazing;
	private String outsideWasteBinLoose;
	private String outsideWasteBinNotTighten;
	private String sleeveScrewMissing;
	private String sleeveScrewLevel;
	private String sleeveScrewSited;
	private String drainPipeLeakage;
	private String drainPipeSealed;
	private String outsideDrainPipeSleeveSited;
	private String loroPipehardwareLoose;
	private String lavatoryDoorPivotLoose;
	private String lavatoryDoorScrewMissing;
	private String lavatoryDoorScrewSited;
	private String lavatoryDoorTaperFitted;
	private String lavatoryDoorTaperSound;
	private String lavatoryDoorFrameCornerSited;
	private String lavatoryDoorFrameCornerGap;
	private String lavatoryDoorHandleLoose;
	private String lavatoryDoorHandleMissing;
	private String coathookLavatoryLoose;
	private String coathookLavatoryMissing;
	private String engageVacantLockWorking;
	private String engageVacantLockMaleFemaleMismatch;
	private String engageVacantLockFemaleLoose;
	private String engageVacantLockFemaleMissing;
	private String engageVacantLockMaleLoose;
	private String engageVacantLockMaleMissing;
	private String swingLockCatchLoose;
	private String swingLockCatchLatch;
	private String swingLockCatchHardwareExcessLength;
	private String swingLockCatchHardwareBurr;
	private String lavatoryDoorCloserScrewTighten;
	private String lavatoryDoorCloserScrewRusted;
	private String lavatoryDoorCloserScrewMovement;
	private String soapDispenserLoose;
	private String soapDispenserTaper;
	private String soapDispenserMissing;
	private String bracketSoapDispenser;
	private String lotahTapStrainerLevel;
	private String lotahTapStrainerSealed;
	private String lotahTapStrainerRoughlySealed;
	private String lotahTapStrainerScrewMissing;
	private String wallHandleCapPasted;
	private String wallHandleScrewLoose;
	private String panLevelFloorLevel;
	private String panLevelFloorLevelRoughlySealed;
	private String washBasinHardwareMissing;
	private String washBasinHardwareTighten;
	private String washBasinHardwareLoose;
	private String dentOnModule;
	private String dentOnHplSheet;
	private String moduleJointNotSealed;
	private String moduleJointRoughlySealed;
	private String commodeHardwareLoose;
	private String commodeHardwareMissing;
	private String plasticFilmRemovedCeilingDoor;
	private String ceilingNotLevel;
	private String ceilingHardwareLoose;
	private String ceilingHardwareDent;
	private String moduleHardwareSidewallLoose;
	private String mirrorHolderLoose;
	private String mirrorHolderTaper;
	private String mirrorHolderApdDone;
	private String hopperWindowFrameSited;
	private String hopperWindowFrameShort;
	private String hopperWindowFrameExcess;
	private String hopperWindowRubberUprooted;
	private String hopperWindowGlassCrack;
	private String conditionLavatoryFloorLevel;
	private String testingObservationRemark;
	private String entryBy;
	private Date entryTime;

	public QciLavatoryTrans() {
	}

	public QciLavatoryTrans(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public QciLavatoryTrans(int furnishingAssetId, String loroPipeLoose, String loroPipeMissing,
			String attachmentWailHingeLoose, String attachmentWailHingeMissing, String attachmentWailHingeDent,String attachmentWallTowerScrewMissing,
			String lavatoryDoorPivotLoose,String lavatoryDoorScrewMissing,String lavatoryDoorScrewSited,String attachmentWallTowerBoltDamage,String towerBoltFitted, String towerBoltHole, String soapCaseScrewMissing, String soapCaseScrewLoose,
			String soapCaseScrewTaper, String lavWashBasinSealed, String lavWashBasinOutside, String avWashBasinInside,
			String lavWashBasinRoughlySealed, String lavWashBasinRoughlyOutside, String lavWashBasinRoughlyInside,
			String dustbinBoxProvided, String dustbinBoxUnlocked, String dustbinBktLoose, String dustbikBktScrewMissing,
			String steelDustbinBktLoose, String wasteBinLoose, String wasteBinScrewMissing, String wasteBinScrewDent,
			String wasteBinCoverPlateRusted, String wasteBinCoverMagnet, String lessScrewWasteBinCover,
			String lessScrewWasteBinCoverGrazing, String outsideWasteBinLoose, String outsideWasteBinNotTighten,
			String sleeveScrewMissing, String sleeveScrewLevel, String sleeveScrewSited, String drainPipeLeakage,
			String drainPipeSealed, String outsideDrainPipeSleeveSited, String loroPipehardwareLoose,
			String lavatoryDoorTaperFitted, String lavatoryDoorTaperSound, String lavatoryDoorFrameCornerSited,
			String lavatoryDoorFrameCornerGap, String lavatoryDoorHandleLoose, String lavatoryDoorHandleMissing,
			String coathookLavatoryLoose, String coathookLavatoryMissing, String engageVacantLockWorking,
			String engageVacantLockMaleFemaleMismatch, String engageVacantLockFemaleLoose,
			String engageVacantLockFemaleMissing, String engageVacantLockMaleLoose, String engageVacantLockMaleMissing,
			String swingLockCatchLoose, String swingLockCatchLatch, String swingLockCatchHardwareExcessLength,
			String swingLockCatchHardwareBurr, String lavatoryDoorCloserScrewTighten,
			String lavatoryDoorCloserScrewRusted, String lavatoryDoorCloserScrewMovement, String soapDispenserLoose,
			String soapDispenserTaper, String soapDispenserMissing, String bracketSoapDispenser,
			String lotahTapStrainerLevel, String lotahTapStrainerSealed, String lotahTapStrainerRoughlySealed,
			String lotahTapStrainerScrewMissing, String wallHandleCapPasted, String wallHandleScrewLoose,
			String panLevelFloorLevel, String panLevelFloorLevelRoughlySealed, String washBasinHardwareMissing,
			String washBasinHardwareTighten, String washBasinHardwareLoose, String dentOnModule, String dentOnHplSheet,
			String moduleJointNotSealed, String moduleJointRoughlySealed, String commodeHardwareLoose,
			String commodeHardwareMissing, String plasticFilmRemovedCeilingDoor, String ceilingNotLevel,
			String ceilingHardwareLoose, String ceilingHardwareDent, String moduleHardwareSidewallLoose,
			String mirrorHolderLoose, String mirrorHolderTaper, String mirrorHolderApdDone,
			String hopperWindowFrameSited, String hopperWindowFrameShort, String hopperWindowFrameExcess,
			String hopperWindowRubberUprooted, String hopperWindowGlassCrack, String conditionLavatoryFloorLevel,
			String testingObservationRemark, String entryBy, Date entryTime) {
		this.furnishingAssetId = furnishingAssetId;
		this.loroPipeLoose = loroPipeLoose;
		this.loroPipeMissing = loroPipeMissing;
		this.attachmentWailHingeLoose = attachmentWailHingeLoose;
		this.attachmentWailHingeMissing = attachmentWailHingeMissing;
		this.attachmentWailHingeDent = attachmentWailHingeDent;
		this.attachmentWallTowerScrewMissing=attachmentWallTowerScrewMissing;
		this.attachmentWallTowerBoltDamage=attachmentWallTowerBoltDamage;
		this.towerBoltFitted = towerBoltFitted;
		this.towerBoltHole = towerBoltHole;
		this.soapCaseScrewMissing = soapCaseScrewMissing;
		this.soapCaseScrewLoose = soapCaseScrewLoose;
		this.soapCaseScrewTaper = soapCaseScrewTaper;
		this.lavWashBasinSealed = lavWashBasinSealed;
		this.lavWashBasinOutside = lavWashBasinOutside;
		this.avWashBasinInside = avWashBasinInside;
		this.lavWashBasinRoughlySealed = lavWashBasinRoughlySealed;
		this.lavWashBasinRoughlyOutside = lavWashBasinRoughlyOutside;
		this.lavWashBasinRoughlyInside = lavWashBasinRoughlyInside;
		this.dustbinBoxProvided = dustbinBoxProvided;
		this.dustbinBoxUnlocked = dustbinBoxUnlocked;
		this.dustbinBktLoose = dustbinBktLoose;
		this.dustbikBktScrewMissing = dustbikBktScrewMissing;
		this.steelDustbinBktLoose = steelDustbinBktLoose;
		this.wasteBinLoose = wasteBinLoose;
		this.wasteBinScrewMissing = wasteBinScrewMissing;
		this.wasteBinScrewDent = wasteBinScrewDent;
		this.wasteBinCoverPlateRusted = wasteBinCoverPlateRusted;
		this.wasteBinCoverMagnet = wasteBinCoverMagnet;
		this.lessScrewWasteBinCover = lessScrewWasteBinCover;
		this.lessScrewWasteBinCoverGrazing = lessScrewWasteBinCoverGrazing;
		this.outsideWasteBinLoose = outsideWasteBinLoose;
		this.outsideWasteBinNotTighten = outsideWasteBinNotTighten;
		this.sleeveScrewMissing = sleeveScrewMissing;
		this.sleeveScrewLevel = sleeveScrewLevel;
		this.sleeveScrewSited = sleeveScrewSited;
		this.drainPipeLeakage = drainPipeLeakage;
		this.drainPipeSealed = drainPipeSealed;
		this.outsideDrainPipeSleeveSited = outsideDrainPipeSleeveSited;
		this.loroPipehardwareLoose = loroPipehardwareLoose;
		this.lavatoryDoorPivotLoose=lavatoryDoorPivotLoose;
		this.lavatoryDoorScrewMissing=lavatoryDoorScrewMissing;
		this.lavatoryDoorScrewSited=lavatoryDoorScrewSited;
		this.lavatoryDoorTaperFitted = lavatoryDoorTaperFitted;
		this.lavatoryDoorTaperSound = lavatoryDoorTaperSound;
		this.lavatoryDoorFrameCornerSited = lavatoryDoorFrameCornerSited;
		this.lavatoryDoorFrameCornerGap = lavatoryDoorFrameCornerGap;
		this.lavatoryDoorHandleLoose = lavatoryDoorHandleLoose;
		this.lavatoryDoorHandleMissing = lavatoryDoorHandleMissing;
		this.coathookLavatoryLoose = coathookLavatoryLoose;
		this.coathookLavatoryMissing = coathookLavatoryMissing;
		this.engageVacantLockWorking = engageVacantLockWorking;
		this.engageVacantLockMaleFemaleMismatch = engageVacantLockMaleFemaleMismatch;
		this.engageVacantLockFemaleLoose = engageVacantLockFemaleLoose;
		this.engageVacantLockFemaleMissing = engageVacantLockFemaleMissing;
		this.engageVacantLockMaleLoose = engageVacantLockMaleLoose;
		this.engageVacantLockMaleMissing = engageVacantLockMaleMissing;
		this.swingLockCatchLoose = swingLockCatchLoose;
		this.swingLockCatchLatch = swingLockCatchLatch;
		this.swingLockCatchHardwareExcessLength = swingLockCatchHardwareExcessLength;
		this.swingLockCatchHardwareBurr = swingLockCatchHardwareBurr;
		this.lavatoryDoorCloserScrewTighten = lavatoryDoorCloserScrewTighten;
		this.lavatoryDoorCloserScrewRusted = lavatoryDoorCloserScrewRusted;
		this.lavatoryDoorCloserScrewMovement = lavatoryDoorCloserScrewMovement;
		this.soapDispenserLoose = soapDispenserLoose;
		this.soapDispenserTaper = soapDispenserTaper;
		this.soapDispenserMissing = soapDispenserMissing;
		this.bracketSoapDispenser = bracketSoapDispenser;
		this.lotahTapStrainerLevel = lotahTapStrainerLevel;
		this.lotahTapStrainerSealed = lotahTapStrainerSealed;
		this.lotahTapStrainerRoughlySealed = lotahTapStrainerRoughlySealed;
		this.lotahTapStrainerScrewMissing = lotahTapStrainerScrewMissing;
		this.wallHandleCapPasted = wallHandleCapPasted;
		this.wallHandleScrewLoose = wallHandleScrewLoose;
		this.panLevelFloorLevel = panLevelFloorLevel;
		this.panLevelFloorLevelRoughlySealed = panLevelFloorLevelRoughlySealed;
		this.washBasinHardwareMissing = washBasinHardwareMissing;
		this.washBasinHardwareTighten = washBasinHardwareTighten;
		this.washBasinHardwareLoose = washBasinHardwareLoose;
		this.dentOnModule = dentOnModule;
		this.dentOnHplSheet = dentOnHplSheet;
		this.moduleJointNotSealed = moduleJointNotSealed;
		this.moduleJointRoughlySealed = moduleJointRoughlySealed;
		this.commodeHardwareLoose = commodeHardwareLoose;
		this.commodeHardwareMissing = commodeHardwareMissing;
		this.plasticFilmRemovedCeilingDoor = plasticFilmRemovedCeilingDoor;
		this.ceilingNotLevel = ceilingNotLevel;
		this.ceilingHardwareLoose = ceilingHardwareLoose;
		this.ceilingHardwareDent = ceilingHardwareDent;
		this.moduleHardwareSidewallLoose = moduleHardwareSidewallLoose;
		this.mirrorHolderLoose = mirrorHolderLoose;
		this.mirrorHolderTaper = mirrorHolderTaper;
		this.mirrorHolderApdDone = mirrorHolderApdDone;
		this.hopperWindowFrameSited = hopperWindowFrameSited;
		this.hopperWindowFrameShort = hopperWindowFrameShort;
		this.hopperWindowFrameExcess = hopperWindowFrameExcess;
		this.hopperWindowRubberUprooted = hopperWindowRubberUprooted;
		this.hopperWindowGlassCrack = hopperWindowGlassCrack;
		this.conditionLavatoryFloorLevel = conditionLavatoryFloorLevel;
		this.testingObservationRemark = testingObservationRemark;
		this.entryBy = entryBy;
		this.entryTime = entryTime;
	}

	public int getFurnishingAssetId() {
		return this.furnishingAssetId;
	}

	public void setFurnishingAssetId(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public String getLoroPipeLoose() {
		return this.loroPipeLoose;
	}

	public void setLoroPipeLoose(String loroPipeLoose) {
		this.loroPipeLoose = loroPipeLoose;
	}

	public String getLoroPipeMissing() {
		return this.loroPipeMissing;
	}

	public void setLoroPipeMissing(String loroPipeMissing) {
		this.loroPipeMissing = loroPipeMissing;
	}

	public String getAttachmentWailHingeLoose() {
		return this.attachmentWailHingeLoose;
	}

	public void setAttachmentWailHingeLoose(String attachmentWailHingeLoose) {
		this.attachmentWailHingeLoose = attachmentWailHingeLoose;
	}

	public String getAttachmentWailHingeMissing() {
		return this.attachmentWailHingeMissing;
	}

	public void setAttachmentWailHingeMissing(String attachmentWailHingeMissing) {
		this.attachmentWailHingeMissing = attachmentWailHingeMissing;
	}

	public String getAttachmentWailHingeDent() {
		return this.attachmentWailHingeDent;
	}

	public void setAttachmentWailHingeDent(String attachmentWailHingeDent) {
		this.attachmentWailHingeDent = attachmentWailHingeDent;
	}

	public String getTowerBoltFitted() {
		return this.towerBoltFitted;
	}

	public void setTowerBoltFitted(String towerBoltFitted) {
		this.towerBoltFitted = towerBoltFitted;
	}

	public String getTowerBoltHole() {
		return this.towerBoltHole;
	}

	public void setTowerBoltHole(String towerBoltHole) {
		this.towerBoltHole = towerBoltHole;
	}

	public String getSoapCaseScrewMissing() {
		return this.soapCaseScrewMissing;
	}

	public void setSoapCaseScrewMissing(String soapCaseScrewMissing) {
		this.soapCaseScrewMissing = soapCaseScrewMissing;
	}

	public String getSoapCaseScrewLoose() {
		return this.soapCaseScrewLoose;
	}

	public void setSoapCaseScrewLoose(String soapCaseScrewLoose) {
		this.soapCaseScrewLoose = soapCaseScrewLoose;
	}

	public String getSoapCaseScrewTaper() {
		return this.soapCaseScrewTaper;
	}

	public void setSoapCaseScrewTaper(String soapCaseScrewTaper) {
		this.soapCaseScrewTaper = soapCaseScrewTaper;
	}

	public String getLavWashBasinSealed() {
		return this.lavWashBasinSealed;
	}

	public void setLavWashBasinSealed(String lavWashBasinSealed) {
		this.lavWashBasinSealed = lavWashBasinSealed;
	}

	public String getLavWashBasinOutside() {
		return this.lavWashBasinOutside;
	}

	public void setLavWashBasinOutside(String lavWashBasinOutside) {
		this.lavWashBasinOutside = lavWashBasinOutside;
	}

	public String getAvWashBasinInside() {
		return this.avWashBasinInside;
	}

	public void setAvWashBasinInside(String avWashBasinInside) {
		this.avWashBasinInside = avWashBasinInside;
	}

	public String getLavWashBasinRoughlySealed() {
		return this.lavWashBasinRoughlySealed;
	}

	public void setLavWashBasinRoughlySealed(String lavWashBasinRoughlySealed) {
		this.lavWashBasinRoughlySealed = lavWashBasinRoughlySealed;
	}

	public String getLavWashBasinRoughlyOutside() {
		return this.lavWashBasinRoughlyOutside;
	}

	public void setLavWashBasinRoughlyOutside(String lavWashBasinRoughlyOutside) {
		this.lavWashBasinRoughlyOutside = lavWashBasinRoughlyOutside;
	}

	public String getLavWashBasinRoughlyInside() {
		return this.lavWashBasinRoughlyInside;
	}

	public void setLavWashBasinRoughlyInside(String lavWashBasinRoughlyInside) {
		this.lavWashBasinRoughlyInside = lavWashBasinRoughlyInside;
	}

	public String getDustbinBoxProvided() {
		return this.dustbinBoxProvided;
	}

	public void setDustbinBoxProvided(String dustbinBoxProvided) {
		this.dustbinBoxProvided = dustbinBoxProvided;
	}

	public String getDustbinBoxUnlocked() {
		return this.dustbinBoxUnlocked;
	}

	public void setDustbinBoxUnlocked(String dustbinBoxUnlocked) {
		this.dustbinBoxUnlocked = dustbinBoxUnlocked;
	}

	public String getDustbinBktLoose() {
		return this.dustbinBktLoose;
	}

	public void setDustbinBktLoose(String dustbinBktLoose) {
		this.dustbinBktLoose = dustbinBktLoose;
	}

	public String getDustbikBktScrewMissing() {
		return this.dustbikBktScrewMissing;
	}

	public void setDustbikBktScrewMissing(String dustbikBktScrewMissing) {
		this.dustbikBktScrewMissing = dustbikBktScrewMissing;
	}

	public String getSteelDustbinBktLoose() {
		return this.steelDustbinBktLoose;
	}

	public void setSteelDustbinBktLoose(String steelDustbinBktLoose) {
		this.steelDustbinBktLoose = steelDustbinBktLoose;
	}

	public String getWasteBinLoose() {
		return this.wasteBinLoose;
	}

	public void setWasteBinLoose(String wasteBinLoose) {
		this.wasteBinLoose = wasteBinLoose;
	}

	public String getWasteBinScrewMissing() {
		return this.wasteBinScrewMissing;
	}

	public void setWasteBinScrewMissing(String wasteBinScrewMissing) {
		this.wasteBinScrewMissing = wasteBinScrewMissing;
	}

	public String getWasteBinScrewDent() {
		return this.wasteBinScrewDent;
	}

	public void setWasteBinScrewDent(String wasteBinScrewDent) {
		this.wasteBinScrewDent = wasteBinScrewDent;
	}

	public String getWasteBinCoverPlateRusted() {
		return this.wasteBinCoverPlateRusted;
	}

	public void setWasteBinCoverPlateRusted(String wasteBinCoverPlateRusted) {
		this.wasteBinCoverPlateRusted = wasteBinCoverPlateRusted;
	}

	public String getWasteBinCoverMagnet() {
		return this.wasteBinCoverMagnet;
	}

	public void setWasteBinCoverMagnet(String wasteBinCoverMagnet) {
		this.wasteBinCoverMagnet = wasteBinCoverMagnet;
	}

	public String getLessScrewWasteBinCover() {
		return this.lessScrewWasteBinCover;
	}

	public void setLessScrewWasteBinCover(String lessScrewWasteBinCover) {
		this.lessScrewWasteBinCover = lessScrewWasteBinCover;
	}

	public String getLessScrewWasteBinCoverGrazing() {
		return this.lessScrewWasteBinCoverGrazing;
	}

	public void setLessScrewWasteBinCoverGrazing(String lessScrewWasteBinCoverGrazing) {
		this.lessScrewWasteBinCoverGrazing = lessScrewWasteBinCoverGrazing;
	}

	public String getOutsideWasteBinLoose() {
		return this.outsideWasteBinLoose;
	}

	public void setOutsideWasteBinLoose(String outsideWasteBinLoose) {
		this.outsideWasteBinLoose = outsideWasteBinLoose;
	}

	public String getOutsideWasteBinNotTighten() {
		return this.outsideWasteBinNotTighten;
	}

	public void setOutsideWasteBinNotTighten(String outsideWasteBinNotTighten) {
		this.outsideWasteBinNotTighten = outsideWasteBinNotTighten;
	}

	public String getSleeveScrewMissing() {
		return this.sleeveScrewMissing;
	}

	public void setSleeveScrewMissing(String sleeveScrewMissing) {
		this.sleeveScrewMissing = sleeveScrewMissing;
	}

	public String getSleeveScrewLevel() {
		return this.sleeveScrewLevel;
	}

	public void setSleeveScrewLevel(String sleeveScrewLevel) {
		this.sleeveScrewLevel = sleeveScrewLevel;
	}

	public String getSleeveScrewSited() {
		return this.sleeveScrewSited;
	}

	public void setSleeveScrewSited(String sleeveScrewSited) {
		this.sleeveScrewSited = sleeveScrewSited;
	}

	public String getDrainPipeLeakage() {
		return this.drainPipeLeakage;
	}

	public void setDrainPipeLeakage(String drainPipeLeakage) {
		this.drainPipeLeakage = drainPipeLeakage;
	}

	public String getDrainPipeSealed() {
		return this.drainPipeSealed;
	}

	public void setDrainPipeSealed(String drainPipeSealed) {
		this.drainPipeSealed = drainPipeSealed;
	}

	public String getOutsideDrainPipeSleeveSited() {
		return this.outsideDrainPipeSleeveSited;
	}

	public void setOutsideDrainPipeSleeveSited(String outsideDrainPipeSleeveSited) {
		this.outsideDrainPipeSleeveSited = outsideDrainPipeSleeveSited;
	}

	public String getLoroPipehardwareLoose() {
		return this.loroPipehardwareLoose;
	}

	public void setLoroPipehardwareLoose(String loroPipehardwareLoose) {
		this.loroPipehardwareLoose = loroPipehardwareLoose;
	}

	public String getLavatoryDoorTaperFitted() {
		return this.lavatoryDoorTaperFitted;
	}

	public void setLavatoryDoorTaperFitted(String lavatoryDoorTaperFitted) {
		this.lavatoryDoorTaperFitted = lavatoryDoorTaperFitted;
	}

	public String getLavatoryDoorTaperSound() {
		return this.lavatoryDoorTaperSound;
	}

	public void setLavatoryDoorTaperSound(String lavatoryDoorTaperSound) {
		this.lavatoryDoorTaperSound = lavatoryDoorTaperSound;
	}

	public String getLavatoryDoorFrameCornerSited() {
		return this.lavatoryDoorFrameCornerSited;
	}

	public void setLavatoryDoorFrameCornerSited(String lavatoryDoorFrameCornerSited) {
		this.lavatoryDoorFrameCornerSited = lavatoryDoorFrameCornerSited;
	}

	public String getLavatoryDoorFrameCornerGap() {
		return this.lavatoryDoorFrameCornerGap;
	}

	public void setLavatoryDoorFrameCornerGap(String lavatoryDoorFrameCornerGap) {
		this.lavatoryDoorFrameCornerGap = lavatoryDoorFrameCornerGap;
	}

	public String getLavatoryDoorHandleLoose() {
		return this.lavatoryDoorHandleLoose;
	}

	public void setLavatoryDoorHandleLoose(String lavatoryDoorHandleLoose) {
		this.lavatoryDoorHandleLoose = lavatoryDoorHandleLoose;
	}

	public String getLavatoryDoorHandleMissing() {
		return this.lavatoryDoorHandleMissing;
	}

	public void setLavatoryDoorHandleMissing(String lavatoryDoorHandleMissing) {
		this.lavatoryDoorHandleMissing = lavatoryDoorHandleMissing;
	}

	public String getCoathookLavatoryLoose() {
		return this.coathookLavatoryLoose;
	}

	public void setCoathookLavatoryLoose(String coathookLavatoryLoose) {
		this.coathookLavatoryLoose = coathookLavatoryLoose;
	}

	public String getCoathookLavatoryMissing() {
		return this.coathookLavatoryMissing;
	}

	public void setCoathookLavatoryMissing(String coathookLavatoryMissing) {
		this.coathookLavatoryMissing = coathookLavatoryMissing;
	}

	public String getEngageVacantLockWorking() {
		return this.engageVacantLockWorking;
	}

	public void setEngageVacantLockWorking(String engageVacantLockWorking) {
		this.engageVacantLockWorking = engageVacantLockWorking;
	}

	public String getEngageVacantLockMaleFemaleMismatch() {
		return this.engageVacantLockMaleFemaleMismatch;
	}

	public void setEngageVacantLockMaleFemaleMismatch(String engageVacantLockMaleFemaleMismatch) {
		this.engageVacantLockMaleFemaleMismatch = engageVacantLockMaleFemaleMismatch;
	}

	public String getEngageVacantLockFemaleLoose() {
		return this.engageVacantLockFemaleLoose;
	}

	public void setEngageVacantLockFemaleLoose(String engageVacantLockFemaleLoose) {
		this.engageVacantLockFemaleLoose = engageVacantLockFemaleLoose;
	}

	public String getEngageVacantLockFemaleMissing() {
		return this.engageVacantLockFemaleMissing;
	}

	public void setEngageVacantLockFemaleMissing(String engageVacantLockFemaleMissing) {
		this.engageVacantLockFemaleMissing = engageVacantLockFemaleMissing;
	}

	public String getEngageVacantLockMaleLoose() {
		return this.engageVacantLockMaleLoose;
	}

	public void setEngageVacantLockMaleLoose(String engageVacantLockMaleLoose) {
		this.engageVacantLockMaleLoose = engageVacantLockMaleLoose;
	}

	public String getEngageVacantLockMaleMissing() {
		return this.engageVacantLockMaleMissing;
	}

	public void setEngageVacantLockMaleMissing(String engageVacantLockMaleMissing) {
		this.engageVacantLockMaleMissing = engageVacantLockMaleMissing;
	}

	public String getSwingLockCatchLoose() {
		return this.swingLockCatchLoose;
	}

	public void setSwingLockCatchLoose(String swingLockCatchLoose) {
		this.swingLockCatchLoose = swingLockCatchLoose;
	}

	public String getSwingLockCatchLatch() {
		return this.swingLockCatchLatch;
	}

	public void setSwingLockCatchLatch(String swingLockCatchLatch) {
		this.swingLockCatchLatch = swingLockCatchLatch;
	}

	public String getSwingLockCatchHardwareExcessLength() {
		return this.swingLockCatchHardwareExcessLength;
	}

	public void setSwingLockCatchHardwareExcessLength(String swingLockCatchHardwareExcessLength) {
		this.swingLockCatchHardwareExcessLength = swingLockCatchHardwareExcessLength;
	}

	public String getSwingLockCatchHardwareBurr() {
		return this.swingLockCatchHardwareBurr;
	}

	public void setSwingLockCatchHardwareBurr(String swingLockCatchHardwareBurr) {
		this.swingLockCatchHardwareBurr = swingLockCatchHardwareBurr;
	}

	public String getLavatoryDoorCloserScrewTighten() {
		return this.lavatoryDoorCloserScrewTighten;
	}

	public void setLavatoryDoorCloserScrewTighten(String lavatoryDoorCloserScrewTighten) {
		this.lavatoryDoorCloserScrewTighten = lavatoryDoorCloserScrewTighten;
	}

	public String getLavatoryDoorCloserScrewRusted() {
		return this.lavatoryDoorCloserScrewRusted;
	}

	public void setLavatoryDoorCloserScrewRusted(String lavatoryDoorCloserScrewRusted) {
		this.lavatoryDoorCloserScrewRusted = lavatoryDoorCloserScrewRusted;
	}

	public String getLavatoryDoorCloserScrewMovement() {
		return this.lavatoryDoorCloserScrewMovement;
	}

	public void setLavatoryDoorCloserScrewMovement(String lavatoryDoorCloserScrewMovement) {
		this.lavatoryDoorCloserScrewMovement = lavatoryDoorCloserScrewMovement;
	}

	public String getSoapDispenserLoose() {
		return this.soapDispenserLoose;
	}

	public void setSoapDispenserLoose(String soapDispenserLoose) {
		this.soapDispenserLoose = soapDispenserLoose;
	}

	public String getSoapDispenserTaper() {
		return this.soapDispenserTaper;
	}

	public void setSoapDispenserTaper(String soapDispenserTaper) {
		this.soapDispenserTaper = soapDispenserTaper;
	}

	public String getSoapDispenserMissing() {
		return this.soapDispenserMissing;
	}

	public void setSoapDispenserMissing(String soapDispenserMissing) {
		this.soapDispenserMissing = soapDispenserMissing;
	}

	public String getBracketSoapDispenser() {
		return this.bracketSoapDispenser;
	}

	public void setBracketSoapDispenser(String bracketSoapDispenser) {
		this.bracketSoapDispenser = bracketSoapDispenser;
	}

	public String getLotahTapStrainerLevel() {
		return this.lotahTapStrainerLevel;
	}

	public void setLotahTapStrainerLevel(String lotahTapStrainerLevel) {
		this.lotahTapStrainerLevel = lotahTapStrainerLevel;
	}

	public String getLotahTapStrainerSealed() {
		return this.lotahTapStrainerSealed;
	}

	public void setLotahTapStrainerSealed(String lotahTapStrainerSealed) {
		this.lotahTapStrainerSealed = lotahTapStrainerSealed;
	}

	public String getLotahTapStrainerRoughlySealed() {
		return this.lotahTapStrainerRoughlySealed;
	}

	public void setLotahTapStrainerRoughlySealed(String lotahTapStrainerRoughlySealed) {
		this.lotahTapStrainerRoughlySealed = lotahTapStrainerRoughlySealed;
	}

	public String getLotahTapStrainerScrewMissing() {
		return this.lotahTapStrainerScrewMissing;
	}

	public void setLotahTapStrainerScrewMissing(String lotahTapStrainerScrewMissing) {
		this.lotahTapStrainerScrewMissing = lotahTapStrainerScrewMissing;
	}

	public String getWallHandleCapPasted() {
		return this.wallHandleCapPasted;
	}

	public void setWallHandleCapPasted(String wallHandleCapPasted) {
		this.wallHandleCapPasted = wallHandleCapPasted;
	}

	public String getWallHandleScrewLoose() {
		return this.wallHandleScrewLoose;
	}

	public void setWallHandleScrewLoose(String wallHandleScrewLoose) {
		this.wallHandleScrewLoose = wallHandleScrewLoose;
	}

	public String getPanLevelFloorLevel() {
		return this.panLevelFloorLevel;
	}

	public void setPanLevelFloorLevel(String panLevelFloorLevel) {
		this.panLevelFloorLevel = panLevelFloorLevel;
	}

	public String getPanLevelFloorLevelRoughlySealed() {
		return this.panLevelFloorLevelRoughlySealed;
	}

	public void setPanLevelFloorLevelRoughlySealed(String panLevelFloorLevelRoughlySealed) {
		this.panLevelFloorLevelRoughlySealed = panLevelFloorLevelRoughlySealed;
	}

	public String getWashBasinHardwareMissing() {
		return this.washBasinHardwareMissing;
	}

	public void setWashBasinHardwareMissing(String washBasinHardwareMissing) {
		this.washBasinHardwareMissing = washBasinHardwareMissing;
	}

	public String getWashBasinHardwareTighten() {
		return this.washBasinHardwareTighten;
	}

	public void setWashBasinHardwareTighten(String washBasinHardwareTighten) {
		this.washBasinHardwareTighten = washBasinHardwareTighten;
	}

	public String getWashBasinHardwareLoose() {
		return this.washBasinHardwareLoose;
	}

	public void setWashBasinHardwareLoose(String washBasinHardwareLoose) {
		this.washBasinHardwareLoose = washBasinHardwareLoose;
	}

	public String getDentOnModule() {
		return this.dentOnModule;
	}

	public void setDentOnModule(String dentOnModule) {
		this.dentOnModule = dentOnModule;
	}

	public String getDentOnHplSheet() {
		return this.dentOnHplSheet;
	}

	public void setDentOnHplSheet(String dentOnHplSheet) {
		this.dentOnHplSheet = dentOnHplSheet;
	}

	public String getModuleJointNotSealed() {
		return this.moduleJointNotSealed;
	}

	public void setModuleJointNotSealed(String moduleJointNotSealed) {
		this.moduleJointNotSealed = moduleJointNotSealed;
	}

	public String getModuleJointRoughlySealed() {
		return this.moduleJointRoughlySealed;
	}

	public void setModuleJointRoughlySealed(String moduleJointRoughlySealed) {
		this.moduleJointRoughlySealed = moduleJointRoughlySealed;
	}

	public String getCommodeHardwareLoose() {
		return this.commodeHardwareLoose;
	}

	public void setCommodeHardwareLoose(String commodeHardwareLoose) {
		this.commodeHardwareLoose = commodeHardwareLoose;
	}

	public String getCommodeHardwareMissing() {
		return this.commodeHardwareMissing;
	}

	public void setCommodeHardwareMissing(String commodeHardwareMissing) {
		this.commodeHardwareMissing = commodeHardwareMissing;
	}

	public String getPlasticFilmRemovedCeilingDoor() {
		return this.plasticFilmRemovedCeilingDoor;
	}

	public void setPlasticFilmRemovedCeilingDoor(String plasticFilmRemovedCeilingDoor) {
		this.plasticFilmRemovedCeilingDoor = plasticFilmRemovedCeilingDoor;
	}

	public String getCeilingNotLevel() {
		return this.ceilingNotLevel;
	}

	public void setCeilingNotLevel(String ceilingNotLevel) {
		this.ceilingNotLevel = ceilingNotLevel;
	}

	public String getCeilingHardwareLoose() {
		return this.ceilingHardwareLoose;
	}

	public void setCeilingHardwareLoose(String ceilingHardwareLoose) {
		this.ceilingHardwareLoose = ceilingHardwareLoose;
	}

	public String getCeilingHardwareDent() {
		return this.ceilingHardwareDent;
	}

	public void setCeilingHardwareDent(String ceilingHardwareDent) {
		this.ceilingHardwareDent = ceilingHardwareDent;
	}

	public String getModuleHardwareSidewallLoose() {
		return this.moduleHardwareSidewallLoose;
	}

	public void setModuleHardwareSidewallLoose(String moduleHardwareSidewallLoose) {
		this.moduleHardwareSidewallLoose = moduleHardwareSidewallLoose;
	}

	public String getMirrorHolderLoose() {
		return this.mirrorHolderLoose;
	}

	public void setMirrorHolderLoose(String mirrorHolderLoose) {
		this.mirrorHolderLoose = mirrorHolderLoose;
	}

	public String getMirrorHolderTaper() {
		return this.mirrorHolderTaper;
	}

	public void setMirrorHolderTaper(String mirrorHolderTaper) {
		this.mirrorHolderTaper = mirrorHolderTaper;
	}

	public String getMirrorHolderApdDone() {
		return this.mirrorHolderApdDone;
	}

	public void setMirrorHolderApdDone(String mirrorHolderApdDone) {
		this.mirrorHolderApdDone = mirrorHolderApdDone;
	}

	public String getHopperWindowFrameSited() {
		return this.hopperWindowFrameSited;
	}

	public void setHopperWindowFrameSited(String hopperWindowFrameSited) {
		this.hopperWindowFrameSited = hopperWindowFrameSited;
	}

	public String getHopperWindowFrameShort() {
		return this.hopperWindowFrameShort;
	}

	public void setHopperWindowFrameShort(String hopperWindowFrameShort) {
		this.hopperWindowFrameShort = hopperWindowFrameShort;
	}

	public String getHopperWindowFrameExcess() {
		return this.hopperWindowFrameExcess;
	}

	public void setHopperWindowFrameExcess(String hopperWindowFrameExcess) {
		this.hopperWindowFrameExcess = hopperWindowFrameExcess;
	}

	public String getHopperWindowRubberUprooted() {
		return this.hopperWindowRubberUprooted;
	}

	public void setHopperWindowRubberUprooted(String hopperWindowRubberUprooted) {
		this.hopperWindowRubberUprooted = hopperWindowRubberUprooted;
	}

	public String getHopperWindowGlassCrack() {
		return this.hopperWindowGlassCrack;
	}

	public void setHopperWindowGlassCrack(String hopperWindowGlassCrack) {
		this.hopperWindowGlassCrack = hopperWindowGlassCrack;
	}

	public String getConditionLavatoryFloorLevel() {
		return this.conditionLavatoryFloorLevel;
	}

	public void setConditionLavatoryFloorLevel(String conditionLavatoryFloorLevel) {
		this.conditionLavatoryFloorLevel = conditionLavatoryFloorLevel;
	}

	public String getTestingObservationRemark() {
		return this.testingObservationRemark;
	}

	public void setTestingObservationRemark(String testingObservationRemark) {
		this.testingObservationRemark = testingObservationRemark;
	}

	public String getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(String entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

	public String getAttachmentWallTowerScrewMissing() {
		return attachmentWallTowerScrewMissing;
	}

	public void setAttachmentWallTowerScrewMissing(String attachmentWallTowerScrewMissing) {
		this.attachmentWallTowerScrewMissing = attachmentWallTowerScrewMissing;
	}

	public String getAttachmentWallTowerBoltDamage() {
		return attachmentWallTowerBoltDamage;
	}

	public void setAttachmentWallTowerBoltDamage(String attachmentWallTowerBoltDamage) {
		this.attachmentWallTowerBoltDamage = attachmentWallTowerBoltDamage;
	}

	public String getLavatoryDoorPivotLoose() {
		return lavatoryDoorPivotLoose;
	}

	public void setLavatoryDoorPivotLoose(String lavatoryDoorPivotLoose) {
		this.lavatoryDoorPivotLoose = lavatoryDoorPivotLoose;
	}

	public String getLavatoryDoorScrewMissing() {
		return lavatoryDoorScrewMissing;
	}

	public void setLavatoryDoorScrewMissing(String lavatoryDoorScrewMissing) {
		this.lavatoryDoorScrewMissing = lavatoryDoorScrewMissing;
	}

	public String getLavatoryDoorScrewSited() {
		return lavatoryDoorScrewSited;
	}

	public void setLavatoryDoorScrewSited(String lavatoryDoorScrewSited) {
		this.lavatoryDoorScrewSited = lavatoryDoorScrewSited;
	}
    
}
