package beans;
// Generated 6 Mar, 2020 3:39:33 PM by Hibernate Tools 4.0.1.Final

/**
 * QciMouldingTrans generated by hbm2java
 */
public class QciMouldingTrans implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int furnishingAssetId;
	private String endwallDoorCoverLoose;
	private String endwallDoorCoverMissing;
	private String endwallDoorCoverTighten;
	private String endwallDoorSliding;
	private String endwallRailscrewMissing;
	private String endwallLoose;
	private String endwallDoorlockAlign;
	private String endwallDoorlockBracketLoose;
	private String manualHandleMovementHard;
	private String manualHandleMovementLoose;
	private String manualHandleRusted;
	private String entranceDoorMovement;
	private String entranceDoorPivotLoose;
	private String entranceDoorPivotScrewSited;
	private String entranceDoorLockWorking;
	private String entranceDoorLatchMismatch;
	private String entranceDoorBottomExcessLength;
	private String entranceDoorGrazingChequerSheet;
	private String entranceDoorGrazingRubber;
	private String excessPlayEntranceDoorPivot;
	private String horizontalSteelStripScrewTighten;
	private String horizontalSteelStripScrewMissing;
	private String horizontalSteelStripScrewHole;
	private String verticalSteelStripScrewTighten;
	private String verticalSteelStripScrewMissing;
	private String verticalSteelStripScrewHole;
	private String horizontalVerticalRubberPasted;
	private String tilliPanelLooseFitted;
	private String tilliPanelBulge;
	private String tilliPanelHole;
	private String verticalFrpLooseFitted;
	private String verticalFrpScrewMissing;
	private String verticalFrpHole;
	private String verticalFrpScrewTighten;
	private String horizontalFrpLooseFitted;
	private String horizontalFrpScrewMissing;
	private String horizontalFrpHole;
	private String horizontalFrpScrewTighten;
	private String verticalfrpHorizontalfrpJointMismatch;
	private String horizontalVerticalFrpEdgeUneven;
	private String horizontalVerticalFrpPutty;
	private String gapSelfPartition;
	private String flapDoorMovementHard;
	private String ZMemberHardwareMissing;
	private String ZMemberHardwareBurr;
	private String linenRoomDoorScrewLoose;
	private String linenRoomBinjoScrewMissing;
	private String linenRoomBinjoScrewLoose;
	private String linenRoomHaspStapleMissing;
	private String compartmentDoorframeSited;
	private String compartmentDoorhingeScrewLoose;
	private String compartmentDoorhingeScrewMissing;
	private String compartmentDoorbrushMissing;
	private String compartmentDoorstopperWorking;
	private String compartmentDoorgrazing;
	private String properFitmentEndwallSaloondoor;
	private String maxOpeningForceEndwallSaloondoor;
	private String movementSlidingdoor;
	private String testingObservationRemark;

	public QciMouldingTrans() {
	}

	public QciMouldingTrans(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public QciMouldingTrans(int furnishingAssetId, String endwallDoorCoverLoose, String endwallDoorCoverMissing,
			String endwallDoorCoverTighten, String endwallDoorSliding, String endwallRailscrewMissing,String endwallLoose,
			String endwallDoorlockAlign, String endwallDoorlockBracketLoose, String manualHandleMovementHard,
			String manualHandleMovementLoose, String manualHandleRusted, String entranceDoorMovement,
			String entranceDoorPivotLoose, String entranceDoorPivotScrewSited, String entranceDoorLockWorking,
			String entranceDoorLatchMismatch, String entranceDoorBottomExcessLength,
			String entranceDoorGrazingChequerSheet, String entranceDoorGrazingRubber,
			String excessPlayEntranceDoorPivot, String horizontalSteelStripScrewTighten,
			String horizontalSteelStripScrewMissing, String horizontalSteelStripScrewHole,
			String verticalSteelStripScrewTighten, String verticalSteelStripScrewMissing,
			String verticalSteelStripScrewHole, String horizontalVerticalRubberPasted, String tilliPanelLooseFitted,
			String tilliPanelBulge, String tilliPanelHole, String verticalFrpLooseFitted,
			String verticalFrpScrewMissing, String verticalFrpHole, String verticalFrpScrewTighten,
			String horizontalFrpLooseFitted, String horizontalFrpScrewMissing, String horizontalFrpHole,
			String horizontalFrpScrewTighten, String verticalfrpHorizontalfrpJointMismatch,
			String horizontalVerticalFrpEdgeUneven, String horizontalVerticalFrpPutty, String gapSelfPartition,
			String flapDoorMovementHard, String ZMemberHardwareMissing, String ZMemberHardwareBurr,
			String linenRoomDoorScrewLoose, String linenRoomBinjoScrewMissing, String linenRoomBinjoScrewLoose,
			String linenRoomHaspStapleMissing, String compartmentDoorframeSited, String compartmentDoorhingeScrewLoose,
			String compartmentDoorhingeScrewMissing, String compartmentDoorbrushMissing,
			String compartmentDoorstopperWorking, String compartmentDoorgrazing, String properFitmentEndwallSaloondoor,
			String maxOpeningForceEndwallSaloondoor, String movementSlidingdoor, String testingObservationRemark) {
		this.furnishingAssetId = furnishingAssetId;
		this.endwallDoorCoverLoose = endwallDoorCoverLoose;
		this.endwallDoorCoverMissing = endwallDoorCoverMissing;
		this.endwallDoorCoverTighten = endwallDoorCoverTighten;
		this.endwallDoorSliding = endwallDoorSliding;
		this.endwallRailscrewMissing = endwallRailscrewMissing;
		this.endwallLoose = endwallLoose;
		this.endwallDoorlockAlign = endwallDoorlockAlign;
		this.endwallDoorlockBracketLoose = endwallDoorlockBracketLoose;
		this.manualHandleMovementHard = manualHandleMovementHard;
		this.manualHandleMovementLoose = manualHandleMovementLoose;
		this.manualHandleRusted = manualHandleRusted;
		this.entranceDoorMovement = entranceDoorMovement;
		this.entranceDoorPivotLoose = entranceDoorPivotLoose;
		this.entranceDoorPivotScrewSited = entranceDoorPivotScrewSited;
		this.entranceDoorLockWorking = entranceDoorLockWorking;
		this.entranceDoorLatchMismatch = entranceDoorLatchMismatch;
		this.entranceDoorBottomExcessLength = entranceDoorBottomExcessLength;
		this.entranceDoorGrazingChequerSheet = entranceDoorGrazingChequerSheet;
		this.entranceDoorGrazingRubber = entranceDoorGrazingRubber;
		this.excessPlayEntranceDoorPivot = excessPlayEntranceDoorPivot;
		this.horizontalSteelStripScrewTighten = horizontalSteelStripScrewTighten;
		this.horizontalSteelStripScrewMissing = horizontalSteelStripScrewMissing;
		this.horizontalSteelStripScrewHole = horizontalSteelStripScrewHole;
		this.verticalSteelStripScrewTighten = verticalSteelStripScrewTighten;
		this.verticalSteelStripScrewMissing = verticalSteelStripScrewMissing;
		this.verticalSteelStripScrewHole = verticalSteelStripScrewHole;
		this.horizontalVerticalRubberPasted = horizontalVerticalRubberPasted;
		this.tilliPanelLooseFitted = tilliPanelLooseFitted;
		this.tilliPanelBulge = tilliPanelBulge;
		this.tilliPanelHole = tilliPanelHole;
		this.verticalFrpLooseFitted = verticalFrpLooseFitted;
		this.verticalFrpScrewMissing = verticalFrpScrewMissing;
		this.verticalFrpHole = verticalFrpHole;
		this.verticalFrpScrewTighten = verticalFrpScrewTighten;
		this.horizontalFrpLooseFitted = horizontalFrpLooseFitted;
		this.horizontalFrpScrewMissing = horizontalFrpScrewMissing;
		this.horizontalFrpHole = horizontalFrpHole;
		this.horizontalFrpScrewTighten = horizontalFrpScrewTighten;
		this.verticalfrpHorizontalfrpJointMismatch = verticalfrpHorizontalfrpJointMismatch;
		this.horizontalVerticalFrpEdgeUneven = horizontalVerticalFrpEdgeUneven;
		this.horizontalVerticalFrpPutty = horizontalVerticalFrpPutty;
		this.gapSelfPartition = gapSelfPartition;
		this.flapDoorMovementHard = flapDoorMovementHard;
		this.ZMemberHardwareMissing = ZMemberHardwareMissing;
		this.ZMemberHardwareBurr = ZMemberHardwareBurr;
		this.linenRoomDoorScrewLoose = linenRoomDoorScrewLoose;
		this.linenRoomBinjoScrewMissing = linenRoomBinjoScrewMissing;
		this.linenRoomBinjoScrewLoose = linenRoomBinjoScrewLoose;
		this.linenRoomHaspStapleMissing = linenRoomHaspStapleMissing;
		this.compartmentDoorframeSited = compartmentDoorframeSited;
		this.compartmentDoorhingeScrewLoose = compartmentDoorhingeScrewLoose;
		this.compartmentDoorhingeScrewMissing = compartmentDoorhingeScrewMissing;
		this.compartmentDoorbrushMissing = compartmentDoorbrushMissing;
		this.compartmentDoorstopperWorking = compartmentDoorstopperWorking;
		this.compartmentDoorgrazing = compartmentDoorgrazing;
		this.properFitmentEndwallSaloondoor = properFitmentEndwallSaloondoor;
		this.maxOpeningForceEndwallSaloondoor = maxOpeningForceEndwallSaloondoor;
		this.movementSlidingdoor = movementSlidingdoor;
		this.testingObservationRemark = testingObservationRemark;
	}

	public int getFurnishingAssetId() {
		return this.furnishingAssetId;
	}

	public void setFurnishingAssetId(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public String getEndwallDoorCoverLoose() {
		return this.endwallDoorCoverLoose;
	}

	public void setEndwallDoorCoverLoose(String endwallDoorCoverLoose) {
		this.endwallDoorCoverLoose = endwallDoorCoverLoose;
	}

	public String getEndwallDoorCoverMissing() {
		return this.endwallDoorCoverMissing;
	}

	public void setEndwallDoorCoverMissing(String endwallDoorCoverMissing) {
		this.endwallDoorCoverMissing = endwallDoorCoverMissing;
	}

	public String getEndwallDoorCoverTighten() {
		return this.endwallDoorCoverTighten;
	}

	public void setEndwallDoorCoverTighten(String endwallDoorCoverTighten) {
		this.endwallDoorCoverTighten = endwallDoorCoverTighten;
	}

	public String getEndwallDoorSliding() {
		return this.endwallDoorSliding;
	}

	public void setEndwallDoorSliding(String endwallDoorSliding) {
		this.endwallDoorSliding = endwallDoorSliding;
	}

	public String getEndwallRailscrewMissing() {
		return this.endwallRailscrewMissing;
	}

	public void setEndwallRailscrewMissing(String endwallRailscrewMissing) {
		this.endwallRailscrewMissing = endwallRailscrewMissing;
	}

	public String getEndwallLoose() {
		return endwallLoose;
	}

	public void setEndwallLoose(String endwallLoose) {
		this.endwallLoose = endwallLoose;
	}

	public String getEndwallDoorlockAlign() {
		return this.endwallDoorlockAlign;
	}

	public void setEndwallDoorlockAlign(String endwallDoorlockAlign) {
		this.endwallDoorlockAlign = endwallDoorlockAlign;
	}

	public String getEndwallDoorlockBracketLoose() {
		return this.endwallDoorlockBracketLoose;
	}

	public void setEndwallDoorlockBracketLoose(String endwallDoorlockBracketLoose) {
		this.endwallDoorlockBracketLoose = endwallDoorlockBracketLoose;
	}

	public String getManualHandleMovementHard() {
		return this.manualHandleMovementHard;
	}

	public void setManualHandleMovementHard(String manualHandleMovementHard) {
		this.manualHandleMovementHard = manualHandleMovementHard;
	}

	public String getManualHandleMovementLoose() {
		return this.manualHandleMovementLoose;
	}

	public void setManualHandleMovementLoose(String manualHandleMovementLoose) {
		this.manualHandleMovementLoose = manualHandleMovementLoose;
	}

	public String getManualHandleRusted() {
		return this.manualHandleRusted;
	}

	public void setManualHandleRusted(String manualHandleRusted) {
		this.manualHandleRusted = manualHandleRusted;
	}

	public String getEntranceDoorMovement() {
		return this.entranceDoorMovement;
	}

	public void setEntranceDoorMovement(String entranceDoorMovement) {
		this.entranceDoorMovement = entranceDoorMovement;
	}

	public String getEntranceDoorPivotLoose() {
		return this.entranceDoorPivotLoose;
	}

	public void setEntranceDoorPivotLoose(String entranceDoorPivotLoose) {
		this.entranceDoorPivotLoose = entranceDoorPivotLoose;
	}

	public String getEntranceDoorPivotScrewSited() {
		return this.entranceDoorPivotScrewSited;
	}

	public void setEntranceDoorPivotScrewSited(String entranceDoorPivotScrewSited) {
		this.entranceDoorPivotScrewSited = entranceDoorPivotScrewSited;
	}

	public String getEntranceDoorLockWorking() {
		return this.entranceDoorLockWorking;
	}

	public void setEntranceDoorLockWorking(String entranceDoorLockWorking) {
		this.entranceDoorLockWorking = entranceDoorLockWorking;
	}

	public String getEntranceDoorLatchMismatch() {
		return this.entranceDoorLatchMismatch;
	}

	public void setEntranceDoorLatchMismatch(String entranceDoorLatchMismatch) {
		this.entranceDoorLatchMismatch = entranceDoorLatchMismatch;
	}

	public String getEntranceDoorBottomExcessLength() {
		return this.entranceDoorBottomExcessLength;
	}

	public void setEntranceDoorBottomExcessLength(String entranceDoorBottomExcessLength) {
		this.entranceDoorBottomExcessLength = entranceDoorBottomExcessLength;
	}

	public String getEntranceDoorGrazingChequerSheet() {
		return this.entranceDoorGrazingChequerSheet;
	}

	public void setEntranceDoorGrazingChequerSheet(String entranceDoorGrazingChequerSheet) {
		this.entranceDoorGrazingChequerSheet = entranceDoorGrazingChequerSheet;
	}

	public String getEntranceDoorGrazingRubber() {
		return this.entranceDoorGrazingRubber;
	}

	public void setEntranceDoorGrazingRubber(String entranceDoorGrazingRubber) {
		this.entranceDoorGrazingRubber = entranceDoorGrazingRubber;
	}

	public String getExcessPlayEntranceDoorPivot() {
		return this.excessPlayEntranceDoorPivot;
	}

	public void setExcessPlayEntranceDoorPivot(String excessPlayEntranceDoorPivot) {
		this.excessPlayEntranceDoorPivot = excessPlayEntranceDoorPivot;
	}

	public String getHorizontalSteelStripScrewTighten() {
		return this.horizontalSteelStripScrewTighten;
	}

	public void setHorizontalSteelStripScrewTighten(String horizontalSteelStripScrewTighten) {
		this.horizontalSteelStripScrewTighten = horizontalSteelStripScrewTighten;
	}

	public String getHorizontalSteelStripScrewMissing() {
		return this.horizontalSteelStripScrewMissing;
	}

	public void setHorizontalSteelStripScrewMissing(String horizontalSteelStripScrewMissing) {
		this.horizontalSteelStripScrewMissing = horizontalSteelStripScrewMissing;
	}

	public String getHorizontalSteelStripScrewHole() {
		return this.horizontalSteelStripScrewHole;
	}

	public void setHorizontalSteelStripScrewHole(String horizontalSteelStripScrewHole) {
		this.horizontalSteelStripScrewHole = horizontalSteelStripScrewHole;
	}

	public String getVerticalSteelStripScrewTighten() {
		return this.verticalSteelStripScrewTighten;
	}

	public void setVerticalSteelStripScrewTighten(String verticalSteelStripScrewTighten) {
		this.verticalSteelStripScrewTighten = verticalSteelStripScrewTighten;
	}

	public String getVerticalSteelStripScrewMissing() {
		return this.verticalSteelStripScrewMissing;
	}

	public void setVerticalSteelStripScrewMissing(String verticalSteelStripScrewMissing) {
		this.verticalSteelStripScrewMissing = verticalSteelStripScrewMissing;
	}

	public String getVerticalSteelStripScrewHole() {
		return this.verticalSteelStripScrewHole;
	}

	public void setVerticalSteelStripScrewHole(String verticalSteelStripScrewHole) {
		this.verticalSteelStripScrewHole = verticalSteelStripScrewHole;
	}

	public String getHorizontalVerticalRubberPasted() {
		return this.horizontalVerticalRubberPasted;
	}

	public void setHorizontalVerticalRubberPasted(String horizontalVerticalRubberPasted) {
		this.horizontalVerticalRubberPasted = horizontalVerticalRubberPasted;
	}

	public String getTilliPanelLooseFitted() {
		return this.tilliPanelLooseFitted;
	}

	public void setTilliPanelLooseFitted(String tilliPanelLooseFitted) {
		this.tilliPanelLooseFitted = tilliPanelLooseFitted;
	}

	public String getTilliPanelBulge() {
		return this.tilliPanelBulge;
	}

	public void setTilliPanelBulge(String tilliPanelBulge) {
		this.tilliPanelBulge = tilliPanelBulge;
	}

	public String getTilliPanelHole() {
		return this.tilliPanelHole;
	}

	public void setTilliPanelHole(String tilliPanelHole) {
		this.tilliPanelHole = tilliPanelHole;
	}

	public String getVerticalFrpLooseFitted() {
		return this.verticalFrpLooseFitted;
	}

	public void setVerticalFrpLooseFitted(String verticalFrpLooseFitted) {
		this.verticalFrpLooseFitted = verticalFrpLooseFitted;
	}

	public String getVerticalFrpScrewMissing() {
		return this.verticalFrpScrewMissing;
	}

	public void setVerticalFrpScrewMissing(String verticalFrpScrewMissing) {
		this.verticalFrpScrewMissing = verticalFrpScrewMissing;
	}

	public String getVerticalFrpHole() {
		return this.verticalFrpHole;
	}

	public void setVerticalFrpHole(String verticalFrpHole) {
		this.verticalFrpHole = verticalFrpHole;
	}

	public String getVerticalFrpScrewTighten() {
		return this.verticalFrpScrewTighten;
	}

	public void setVerticalFrpScrewTighten(String verticalFrpScrewTighten) {
		this.verticalFrpScrewTighten = verticalFrpScrewTighten;
	}

	public String getHorizontalFrpLooseFitted() {
		return this.horizontalFrpLooseFitted;
	}

	public void setHorizontalFrpLooseFitted(String horizontalFrpLooseFitted) {
		this.horizontalFrpLooseFitted = horizontalFrpLooseFitted;
	}

	public String getHorizontalFrpScrewMissing() {
		return this.horizontalFrpScrewMissing;
	}

	public void setHorizontalFrpScrewMissing(String horizontalFrpScrewMissing) {
		this.horizontalFrpScrewMissing = horizontalFrpScrewMissing;
	}

	public String getHorizontalFrpHole() {
		return this.horizontalFrpHole;
	}

	public void setHorizontalFrpHole(String horizontalFrpHole) {
		this.horizontalFrpHole = horizontalFrpHole;
	}

	public String getHorizontalFrpScrewTighten() {
		return this.horizontalFrpScrewTighten;
	}

	public void setHorizontalFrpScrewTighten(String horizontalFrpScrewTighten) {
		this.horizontalFrpScrewTighten = horizontalFrpScrewTighten;
	}

	public String getVerticalfrpHorizontalfrpJointMismatch() {
		return this.verticalfrpHorizontalfrpJointMismatch;
	}

	public void setVerticalfrpHorizontalfrpJointMismatch(String verticalfrpHorizontalfrpJointMismatch) {
		this.verticalfrpHorizontalfrpJointMismatch = verticalfrpHorizontalfrpJointMismatch;
	}

	public String getHorizontalVerticalFrpEdgeUneven() {
		return this.horizontalVerticalFrpEdgeUneven;
	}

	public void setHorizontalVerticalFrpEdgeUneven(String horizontalVerticalFrpEdgeUneven) {
		this.horizontalVerticalFrpEdgeUneven = horizontalVerticalFrpEdgeUneven;
	}

	public String getHorizontalVerticalFrpPutty() {
		return this.horizontalVerticalFrpPutty;
	}

	public void setHorizontalVerticalFrpPutty(String horizontalVerticalFrpPutty) {
		this.horizontalVerticalFrpPutty = horizontalVerticalFrpPutty;
	}

	public String getGapSelfPartition() {
		return this.gapSelfPartition;
	}

	public void setGapSelfPartition(String gapSelfPartition) {
		this.gapSelfPartition = gapSelfPartition;
	}

	public String getFlapDoorMovementHard() {
		return this.flapDoorMovementHard;
	}

	public void setFlapDoorMovementHard(String flapDoorMovementHard) {
		this.flapDoorMovementHard = flapDoorMovementHard;
	}

	public String getZMemberHardwareMissing() {
		return this.ZMemberHardwareMissing;
	}

	public void setZMemberHardwareMissing(String ZMemberHardwareMissing) {
		this.ZMemberHardwareMissing = ZMemberHardwareMissing;
	}

	public String getZMemberHardwareBurr() {
		return this.ZMemberHardwareBurr;
	}

	public void setZMemberHardwareBurr(String ZMemberHardwareBurr) {
		this.ZMemberHardwareBurr = ZMemberHardwareBurr;
	}

	public String getLinenRoomDoorScrewLoose() {
		return this.linenRoomDoorScrewLoose;
	}

	public void setLinenRoomDoorScrewLoose(String linenRoomDoorScrewLoose) {
		this.linenRoomDoorScrewLoose = linenRoomDoorScrewLoose;
	}

	public String getLinenRoomBinjoScrewMissing() {
		return this.linenRoomBinjoScrewMissing;
	}

	public void setLinenRoomBinjoScrewMissing(String linenRoomBinjoScrewMissing) {
		this.linenRoomBinjoScrewMissing = linenRoomBinjoScrewMissing;
	}

	public String getLinenRoomBinjoScrewLoose() {
		return this.linenRoomBinjoScrewLoose;
	}

	public void setLinenRoomBinjoScrewLoose(String linenRoomBinjoScrewLoose) {
		this.linenRoomBinjoScrewLoose = linenRoomBinjoScrewLoose;
	}

	public String getLinenRoomHaspStapleMissing() {
		return this.linenRoomHaspStapleMissing;
	}

	public void setLinenRoomHaspStapleMissing(String linenRoomHaspStapleMissing) {
		this.linenRoomHaspStapleMissing = linenRoomHaspStapleMissing;
	}

	public String getCompartmentDoorframeSited() {
		return this.compartmentDoorframeSited;
	}

	public void setCompartmentDoorframeSited(String compartmentDoorframeSited) {
		this.compartmentDoorframeSited = compartmentDoorframeSited;
	}

	public String getCompartmentDoorhingeScrewLoose() {
		return this.compartmentDoorhingeScrewLoose;
	}

	public void setCompartmentDoorhingeScrewLoose(String compartmentDoorhingeScrewLoose) {
		this.compartmentDoorhingeScrewLoose = compartmentDoorhingeScrewLoose;
	}

	public String getCompartmentDoorhingeScrewMissing() {
		return this.compartmentDoorhingeScrewMissing;
	}

	public void setCompartmentDoorhingeScrewMissing(String compartmentDoorhingeScrewMissing) {
		this.compartmentDoorhingeScrewMissing = compartmentDoorhingeScrewMissing;
	}

	public String getCompartmentDoorbrushMissing() {
		return this.compartmentDoorbrushMissing;
	}

	public void setCompartmentDoorbrushMissing(String compartmentDoorbrushMissing) {
		this.compartmentDoorbrushMissing = compartmentDoorbrushMissing;
	}

	public String getCompartmentDoorstopperWorking() {
		return this.compartmentDoorstopperWorking;
	}

	public void setCompartmentDoorstopperWorking(String compartmentDoorstopperWorking) {
		this.compartmentDoorstopperWorking = compartmentDoorstopperWorking;
	}

	public String getCompartmentDoorgrazing() {
		return this.compartmentDoorgrazing;
	}

	public void setCompartmentDoorgrazing(String compartmentDoorgrazing) {
		this.compartmentDoorgrazing = compartmentDoorgrazing;
	}

	public String getProperFitmentEndwallSaloondoor() {
		return this.properFitmentEndwallSaloondoor;
	}

	public void setProperFitmentEndwallSaloondoor(String properFitmentEndwallSaloondoor) {
		this.properFitmentEndwallSaloondoor = properFitmentEndwallSaloondoor;
	}

	public String getMaxOpeningForceEndwallSaloondoor() {
		return this.maxOpeningForceEndwallSaloondoor;
	}

	public void setMaxOpeningForceEndwallSaloondoor(String maxOpeningForceEndwallSaloondoor) {
		this.maxOpeningForceEndwallSaloondoor = maxOpeningForceEndwallSaloondoor;
	}

	public String getMovementSlidingdoor() {
		return this.movementSlidingdoor;
	}

	public void setMovementSlidingdoor(String movementSlidingdoor) {
		this.movementSlidingdoor = movementSlidingdoor;
	}

	public String getTestingObservationRemark() {
		return this.testingObservationRemark;
	}

	public void setTestingObservationRemark(String testingObservationRemark) {
		this.testingObservationRemark = testingObservationRemark;
	}

}
