package beans;
// Generated 6 Mar, 2020 3:39:33 PM by Hibernate Tools 4.0.1.Final

/**
 * QciPanelTrans generated by hbm2java
 */
public class QciPanelTrans implements java.io.Serializable {

	private int furnishingAssetId;
	private String acAirGrillScrewTighten;
	private String acAirGrillScrewMissing;
	private String gapPartitionPanel;
	private String cutMarkPanelCorner;
	private String panelCrackNear;
	private String panelDentNear;
	private String magazineBagScrewLoose;
	private String magazineBagScrewNotFitted;
	private String magazineTaperFitted;
	private String magazineTaperBulged;
	private String magazineTaperDamage;
	private String holePanelPartition;
	private String panelNotLocked;
	private String excessGapPanelPartition;
	private String windowRubberExcessLength;
	private String windowRubberShortLength;
	private String windowRubberUprooted;
	private String testingObservationRemark;

	public QciPanelTrans() {
	}

	public QciPanelTrans(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public QciPanelTrans(int furnishingAssetId, String acAirGrillScrewTighten, String acAirGrillScrewMissing,
			String gapPartitionPanel, String cutMarkPanelCorner, String panelCrackNear, String panelDentNear,
			String magazineBagScrewLoose, String magazineBagScrewNotFitted, String magazineTaperFitted,
			String magazineTaperBulged, String magazineTaperDamage, String holePanelPartition, String panelNotLocked,
			String excessGapPanelPartition, String windowRubberExcessLength, String windowRubberShortLength,
			String windowRubberUprooted, String testingObservationRemark) {
		this.furnishingAssetId = furnishingAssetId;
		this.acAirGrillScrewTighten = acAirGrillScrewTighten;
		this.acAirGrillScrewMissing = acAirGrillScrewMissing;
		this.gapPartitionPanel = gapPartitionPanel;
		this.cutMarkPanelCorner = cutMarkPanelCorner;
		this.panelCrackNear = panelCrackNear;
		this.panelDentNear = panelDentNear;
		this.magazineBagScrewLoose = magazineBagScrewLoose;
		this.magazineBagScrewNotFitted = magazineBagScrewNotFitted;
		this.magazineTaperFitted = magazineTaperFitted;
		this.magazineTaperBulged = magazineTaperBulged;
		this.magazineTaperDamage = magazineTaperDamage;
		this.holePanelPartition = holePanelPartition;
		this.panelNotLocked = panelNotLocked;
		this.excessGapPanelPartition = excessGapPanelPartition;
		this.windowRubberExcessLength = windowRubberExcessLength;
		this.windowRubberShortLength = windowRubberShortLength;
		this.windowRubberUprooted = windowRubberUprooted;
		this.testingObservationRemark = testingObservationRemark;
	}

	public int getFurnishingAssetId() {
		return this.furnishingAssetId;
	}

	public void setFurnishingAssetId(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public String getAcAirGrillScrewTighten() {
		return this.acAirGrillScrewTighten;
	}

	public void setAcAirGrillScrewTighten(String acAirGrillScrewTighten) {
		this.acAirGrillScrewTighten = acAirGrillScrewTighten;
	}

	public String getAcAirGrillScrewMissing() {
		return this.acAirGrillScrewMissing;
	}

	public void setAcAirGrillScrewMissing(String acAirGrillScrewMissing) {
		this.acAirGrillScrewMissing = acAirGrillScrewMissing;
	}

	public String getGapPartitionPanel() {
		return this.gapPartitionPanel;
	}

	public void setGapPartitionPanel(String gapPartitionPanel) {
		this.gapPartitionPanel = gapPartitionPanel;
	}

	public String getCutMarkPanelCorner() {
		return this.cutMarkPanelCorner;
	}

	public void setCutMarkPanelCorner(String cutMarkPanelCorner) {
		this.cutMarkPanelCorner = cutMarkPanelCorner;
	}

	public String getPanelCrackNear() {
		return this.panelCrackNear;
	}

	public void setPanelCrackNear(String panelCrackNear) {
		this.panelCrackNear = panelCrackNear;
	}

	public String getPanelDentNear() {
		return this.panelDentNear;
	}

	public void setPanelDentNear(String panelDentNear) {
		this.panelDentNear = panelDentNear;
	}

	public String getMagazineBagScrewLoose() {
		return this.magazineBagScrewLoose;
	}

	public void setMagazineBagScrewLoose(String magazineBagScrewLoose) {
		this.magazineBagScrewLoose = magazineBagScrewLoose;
	}

	public String getMagazineBagScrewNotFitted() {
		return this.magazineBagScrewNotFitted;
	}

	public void setMagazineBagScrewNotFitted(String magazineBagScrewNotFitted) {
		this.magazineBagScrewNotFitted = magazineBagScrewNotFitted;
	}

	public String getMagazineTaperFitted() {
		return this.magazineTaperFitted;
	}

	public void setMagazineTaperFitted(String magazineTaperFitted) {
		this.magazineTaperFitted = magazineTaperFitted;
	}

	public String getMagazineTaperBulged() {
		return this.magazineTaperBulged;
	}

	public void setMagazineTaperBulged(String magazineTaperBulged) {
		this.magazineTaperBulged = magazineTaperBulged;
	}

	public String getMagazineTaperDamage() {
		return this.magazineTaperDamage;
	}

	public void setMagazineTaperDamage(String magazineTaperDamage) {
		this.magazineTaperDamage = magazineTaperDamage;
	}

	public String getHolePanelPartition() {
		return this.holePanelPartition;
	}

	public void setHolePanelPartition(String holePanelPartition) {
		this.holePanelPartition = holePanelPartition;
	}

	public String getPanelNotLocked() {
		return this.panelNotLocked;
	}

	public void setPanelNotLocked(String panelNotLocked) {
		this.panelNotLocked = panelNotLocked;
	}

	public String getExcessGapPanelPartition() {
		return this.excessGapPanelPartition;
	}

	public void setExcessGapPanelPartition(String excessGapPanelPartition) {
		this.excessGapPanelPartition = excessGapPanelPartition;
	}

	public String getWindowRubberExcessLength() {
		return this.windowRubberExcessLength;
	}

	public void setWindowRubberExcessLength(String windowRubberExcessLength) {
		this.windowRubberExcessLength = windowRubberExcessLength;
	}

	public String getWindowRubberShortLength() {
		return this.windowRubberShortLength;
	}

	public void setWindowRubberShortLength(String windowRubberShortLength) {
		this.windowRubberShortLength = windowRubberShortLength;
	}

	public String getWindowRubberUprooted() {
		return this.windowRubberUprooted;
	}

	public void setWindowRubberUprooted(String windowRubberUprooted) {
		this.windowRubberUprooted = windowRubberUprooted;
	}

	public String getTestingObservationRemark() {
		return this.testingObservationRemark;
	}

	public void setTestingObservationRemark(String testingObservationRemark) {
		this.testingObservationRemark = testingObservationRemark;
	}

}
