package beans;
// Generated 12 Mar, 2020 1:13:15 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * QciPaintTrans generated by hbm2java
 */
public class QciPaintTrans implements java.io.Serializable {

	private int furnishingAssetId;
	private String fitmentDestinationboardNoPlate;
	private String properStencillingLettering;
	private String burrBraileSticker;
	private String testingObservationRemark;
	private String entryBy;
	private Date entryTime;

	public QciPaintTrans() {
	}

	public QciPaintTrans(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public QciPaintTrans(int furnishingAssetId, String fitmentDestinationboardNoPlate,
			String properStencillingLettering, String burrBraileSticker, String testingObservationRemark,
			String entryBy, Date entryTime) {
		this.furnishingAssetId = furnishingAssetId;
		this.fitmentDestinationboardNoPlate = fitmentDestinationboardNoPlate;
		this.properStencillingLettering = properStencillingLettering;
		this.burrBraileSticker = burrBraileSticker;
		this.testingObservationRemark = testingObservationRemark;
		this.entryBy = entryBy;
		this.entryTime = entryTime;
	}

	public int getFurnishingAssetId() {
		return this.furnishingAssetId;
	}

	public void setFurnishingAssetId(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public String getFitmentDestinationboardNoPlate() {
		return this.fitmentDestinationboardNoPlate;
	}

	public void setFitmentDestinationboardNoPlate(String fitmentDestinationboardNoPlate) {
		this.fitmentDestinationboardNoPlate = fitmentDestinationboardNoPlate;
	}

	public String getProperStencillingLettering() {
		return this.properStencillingLettering;
	}

	public void setProperStencillingLettering(String properStencillingLettering) {
		this.properStencillingLettering = properStencillingLettering;
	}

	public String getBurrBraileSticker() {
		return this.burrBraileSticker;
	}

	public void setBurrBraileSticker(String burrBraileSticker) {
		this.burrBraileSticker = burrBraileSticker;
	}

	public String getTestingObservationRemark() {
		return this.testingObservationRemark;
	}

	public void setTestingObservationRemark(String testingObservationRemark) {
		this.testingObservationRemark = testingObservationRemark;
	}

	public String getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(String entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

}
