package beans;
// Generated 6 Mar, 2020 3:39:33 PM by Hibernate Tools 4.0.1.Final

/**
 * QciPartitionFrameTrans generated by hbm2java
 */
public class QciPartitionFrameTrans implements java.io.Serializable {

	private int furnishingAssetId;
	private String dentMarkPartitionBn;
	private String dentMarkPartitionExceesCut;
	private String excessGapUmouldingPartitionpillar;
	private String middleBearthStopperMissing;
	private String middleBearthStopperLoose;
	private String middleBearthStopperRubberPad;
	private String partitionPillarHardwareLoose;
	private String partitionPillarHardwareMissing;
	private String partitionPillarHardwareTaper;
	private String unwantedHolesPartitionBn;
	private String plasticFilmRemovedPartition;
	private String roughlyPuttyPartition;
	private String partitionPillarZigzag;
	private String partitionPillarProperlySited;
	private String burrFoundPartitionPillar;
	private String burrFoundBerthHoldingBkt;
	private String testingObservationRemark;

	public QciPartitionFrameTrans() {
	}

	public QciPartitionFrameTrans(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public QciPartitionFrameTrans(int furnishingAssetId, String dentMarkPartitionBn, String dentMarkPartitionExceesCut,
			String excessGapUmouldingPartitionpillar, String middleBearthStopperMissing,
			String middleBearthStopperLoose, String middleBearthStopperRubberPad, String partitionPillarHardwareLoose,
			String partitionPillarHardwareMissing, String partitionPillarHardwareTaper, String unwantedHolesPartitionBn,
			String plasticFilmRemovedPartition, String roughlyPuttyPartition, String partitionPillarZigzag,
			String partitionPillarProperlySited, String burrFoundPartitionPillar, String burrFoundBerthHoldingBkt,
			String testingObservationRemark) {
		this.furnishingAssetId = furnishingAssetId;
		this.dentMarkPartitionBn = dentMarkPartitionBn;
		this.dentMarkPartitionExceesCut = dentMarkPartitionExceesCut;
		this.excessGapUmouldingPartitionpillar = excessGapUmouldingPartitionpillar;
		this.middleBearthStopperMissing = middleBearthStopperMissing;
		this.middleBearthStopperLoose = middleBearthStopperLoose;
		this.middleBearthStopperRubberPad = middleBearthStopperRubberPad;
		this.partitionPillarHardwareLoose = partitionPillarHardwareLoose;
		this.partitionPillarHardwareMissing = partitionPillarHardwareMissing;
		this.partitionPillarHardwareTaper = partitionPillarHardwareTaper;
		this.unwantedHolesPartitionBn = unwantedHolesPartitionBn;
		this.plasticFilmRemovedPartition = plasticFilmRemovedPartition;
		this.roughlyPuttyPartition = roughlyPuttyPartition;
		this.partitionPillarZigzag = partitionPillarZigzag;
		this.partitionPillarProperlySited = partitionPillarProperlySited;
		this.burrFoundPartitionPillar = burrFoundPartitionPillar;
		this.burrFoundBerthHoldingBkt = burrFoundBerthHoldingBkt;
		this.testingObservationRemark = testingObservationRemark;
	}

	public int getFurnishingAssetId() {
		return this.furnishingAssetId;
	}

	public void setFurnishingAssetId(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public String getDentMarkPartitionBn() {
		return this.dentMarkPartitionBn;
	}

	public void setDentMarkPartitionBn(String dentMarkPartitionBn) {
		this.dentMarkPartitionBn = dentMarkPartitionBn;
	}

	public String getDentMarkPartitionExceesCut() {
		return this.dentMarkPartitionExceesCut;
	}

	public void setDentMarkPartitionExceesCut(String dentMarkPartitionExceesCut) {
		this.dentMarkPartitionExceesCut = dentMarkPartitionExceesCut;
	}

	public String getExcessGapUmouldingPartitionpillar() {
		return this.excessGapUmouldingPartitionpillar;
	}

	public void setExcessGapUmouldingPartitionpillar(String excessGapUmouldingPartitionpillar) {
		this.excessGapUmouldingPartitionpillar = excessGapUmouldingPartitionpillar;
	}

	public String getMiddleBearthStopperMissing() {
		return this.middleBearthStopperMissing;
	}

	public void setMiddleBearthStopperMissing(String middleBearthStopperMissing) {
		this.middleBearthStopperMissing = middleBearthStopperMissing;
	}

	public String getMiddleBearthStopperLoose() {
		return this.middleBearthStopperLoose;
	}

	public void setMiddleBearthStopperLoose(String middleBearthStopperLoose) {
		this.middleBearthStopperLoose = middleBearthStopperLoose;
	}

	public String getMiddleBearthStopperRubberPad() {
		return this.middleBearthStopperRubberPad;
	}

	public void setMiddleBearthStopperRubberPad(String middleBearthStopperRubberPad) {
		this.middleBearthStopperRubberPad = middleBearthStopperRubberPad;
	}

	public String getPartitionPillarHardwareLoose() {
		return this.partitionPillarHardwareLoose;
	}

	public void setPartitionPillarHardwareLoose(String partitionPillarHardwareLoose) {
		this.partitionPillarHardwareLoose = partitionPillarHardwareLoose;
	}

	public String getPartitionPillarHardwareMissing() {
		return this.partitionPillarHardwareMissing;
	}

	public void setPartitionPillarHardwareMissing(String partitionPillarHardwareMissing) {
		this.partitionPillarHardwareMissing = partitionPillarHardwareMissing;
	}

	public String getPartitionPillarHardwareTaper() {
		return this.partitionPillarHardwareTaper;
	}

	public void setPartitionPillarHardwareTaper(String partitionPillarHardwareTaper) {
		this.partitionPillarHardwareTaper = partitionPillarHardwareTaper;
	}

	public String getUnwantedHolesPartitionBn() {
		return this.unwantedHolesPartitionBn;
	}

	public void setUnwantedHolesPartitionBn(String unwantedHolesPartitionBn) {
		this.unwantedHolesPartitionBn = unwantedHolesPartitionBn;
	}

	public String getPlasticFilmRemovedPartition() {
		return this.plasticFilmRemovedPartition;
	}

	public void setPlasticFilmRemovedPartition(String plasticFilmRemovedPartition) {
		this.plasticFilmRemovedPartition = plasticFilmRemovedPartition;
	}

	public String getRoughlyPuttyPartition() {
		return this.roughlyPuttyPartition;
	}

	public void setRoughlyPuttyPartition(String roughlyPuttyPartition) {
		this.roughlyPuttyPartition = roughlyPuttyPartition;
	}

	public String getPartitionPillarZigzag() {
		return this.partitionPillarZigzag;
	}

	public void setPartitionPillarZigzag(String partitionPillarZigzag) {
		this.partitionPillarZigzag = partitionPillarZigzag;
	}

	public String getPartitionPillarProperlySited() {
		return this.partitionPillarProperlySited;
	}

	public void setPartitionPillarProperlySited(String partitionPillarProperlySited) {
		this.partitionPillarProperlySited = partitionPillarProperlySited;
	}

	public String getBurrFoundPartitionPillar() {
		return this.burrFoundPartitionPillar;
	}

	public void setBurrFoundPartitionPillar(String burrFoundPartitionPillar) {
		this.burrFoundPartitionPillar = burrFoundPartitionPillar;
	}

	public String getBurrFoundBerthHoldingBkt() {
		return this.burrFoundBerthHoldingBkt;
	}

	public void setBurrFoundBerthHoldingBkt(String burrFoundBerthHoldingBkt) {
		this.burrFoundBerthHoldingBkt = burrFoundBerthHoldingBkt;
	}

	public String getTestingObservationRemark() {
		return this.testingObservationRemark;
	}

	public void setTestingObservationRemark(String testingObservationRemark) {
		this.testingObservationRemark = testingObservationRemark;
	}

}
