package beans;
// Generated 12 Mar, 2020 1:06:30 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * QciPlumbingTrans generated by hbm2java
 */
public class QciPlumbingTrans implements java.io.Serializable {

	private int furnishingAssetId;
	private String readingWaterLevelGauge;
	private String isOsWashbasinTapLoose;
	private String showerHandleLoose;
	private String showerHandleBroken;
	private String showerHandleStandScrewLoose;
	private String upperTankUclampRubberMissingLoose;
	private String testingObservationRemark;
	private String entryBy;
	private Date entryTime;

	public QciPlumbingTrans() {
	}

	public QciPlumbingTrans(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public QciPlumbingTrans(int furnishingAssetId, String readingWaterLevelGauge, String isOsWashbasinTapLoose,
			String showerHandleLoose, String showerHandleBroken, String showerHandleStandScrewLoose,
			String upperTankUclampRubberMissingLoose, String testingObservationRemark, String entryBy, Date entryTime) {
		this.furnishingAssetId = furnishingAssetId;
		this.readingWaterLevelGauge = readingWaterLevelGauge;
		this.isOsWashbasinTapLoose = isOsWashbasinTapLoose;
		this.showerHandleLoose = showerHandleLoose;
		this.showerHandleBroken = showerHandleBroken;
		this.showerHandleStandScrewLoose = showerHandleStandScrewLoose;
		this.upperTankUclampRubberMissingLoose = upperTankUclampRubberMissingLoose;
		this.testingObservationRemark = testingObservationRemark;
		this.entryBy = entryBy;
		this.entryTime = entryTime;
	}

	public int getFurnishingAssetId() {
		return this.furnishingAssetId;
	}

	public void setFurnishingAssetId(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public String getReadingWaterLevelGauge() {
		return this.readingWaterLevelGauge;
	}

	public void setReadingWaterLevelGauge(String readingWaterLevelGauge) {
		this.readingWaterLevelGauge = readingWaterLevelGauge;
	}

	public String getIsOsWashbasinTapLoose() {
		return this.isOsWashbasinTapLoose;
	}

	public void setIsOsWashbasinTapLoose(String isOsWashbasinTapLoose) {
		this.isOsWashbasinTapLoose = isOsWashbasinTapLoose;
	}

	public String getShowerHandleLoose() {
		return this.showerHandleLoose;
	}

	public void setShowerHandleLoose(String showerHandleLoose) {
		this.showerHandleLoose = showerHandleLoose;
	}

	public String getShowerHandleBroken() {
		return this.showerHandleBroken;
	}

	public void setShowerHandleBroken(String showerHandleBroken) {
		this.showerHandleBroken = showerHandleBroken;
	}

	public String getShowerHandleStandScrewLoose() {
		return this.showerHandleStandScrewLoose;
	}

	public void setShowerHandleStandScrewLoose(String showerHandleStandScrewLoose) {
		this.showerHandleStandScrewLoose = showerHandleStandScrewLoose;
	}

	public String getUpperTankUclampRubberMissingLoose() {
		return this.upperTankUclampRubberMissingLoose;
	}

	public void setUpperTankUclampRubberMissingLoose(String upperTankUclampRubberMissingLoose) {
		this.upperTankUclampRubberMissingLoose = upperTankUclampRubberMissingLoose;
	}

	public String getTestingObservationRemark() {
		return this.testingObservationRemark;
	}

	public void setTestingObservationRemark(String testingObservationRemark) {
		this.testingObservationRemark = testingObservationRemark;
	}

	public String getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(String entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

}
