package beans;
// Generated 6 Mar, 2020 3:41:29 PM by Hibernate Tools 4.0.1.Final

/**
 * QciSeatBerthTrans generated by hbm2java
 */
public class QciSeatBerthTrans implements java.io.Serializable {

	private int furnishingAssetId;
	private String protectionWallHardwareLoose;
	private String protectionWallHardwareMissing;
	private String luggageRackLoose;
	private String luggageRackTaper;
	private String luggageRackMissing;
	private String mirrorNotPasted;
	private String mirrorRubberUprooted;
	private String coatHookLoose;
	private String coatHookMissing;
	private String coatHookApdDone;
	private String coatHookApdRoughly;
	private String curtainMovementSmooth;
	private String curtainRunnerCameOut;
	private String curtainRunnerStopperFitted;
	private String snackTableLoose;
	private String snackTableTapper;
	private String snackTableScrewMissing;
	private String safetyRailTaper;
	private String safetyRailLoose;
	private String safetyRailBktLoose;
	private String safetyRailBktTighten;
	private String safetyRailBktTaper;
	private String berthChainLoose;
	private String berthChainHardwareLoose;
	private String berthChainHardwareMissing;
	private String bottleHolderLoose;
	private String bottleHolderTaper;
	private String bottoleHolderScrewMissing;
	private String bottoleHolderScrewDamage;
	private String berthMountingHardwareSidewallLoose;
	private String berthMountingHardwareSidewallTaper;
	private String berthMountingHardwareSidewallMissing;
	private String berthMountingHardwarePillarLoose;
	private String berthMountingHardwarePillarTaper;
	private String berthMountingHardwarePillarMissing;
	private String berthTapper;
	private String berthFlapLoose;
	private String berthFlapBulge;
	private String flapAlStripExcessLength;
	private String flapAlHardwareExcessLength;
	private String transverseBerthLevel;
	private String gapBackrestBerth;
	private String backrestMovement;
	private String backrestGrazingLadder;
	private String backrestGrazingPanelseat;
	private String latchCatchMissmatch;
	private String burrLatchSeat;
	private String burrCatchSeat;
	private String holePartitionLatchSeat;
	private String rexineTornBackrestSeat;
	private String rexineTornBerth;
	private String almirahHardwareLoose;
	private String almirahHardwareMissing;
	private String towerWorking;
	private String almirahWorking;
	private String almirahHole;
	private String holeNearBottleHolder;
	private String holeNearLatchSeat;
	private String holeNearCatchSeat;
	private String rexineTornBerthArmrest;
	private String builderPlateScrewMissing;
	private String builderPlateScrewMissmatch;
	private String rexenePastedBacksideBerth;
	private String testingObservationRemark;

	public QciSeatBerthTrans() {
	}

	public QciSeatBerthTrans(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public QciSeatBerthTrans(int furnishingAssetId, String protectionWallHardwareLoose,
			String protectionWallHardwareMissing, String luggageRackLoose, String luggageRackTaper,
			String luggageRackMissing, String mirrorNotPasted, String mirrorRubberUprooted, String coatHookLoose,
			String coatHookMissing, String coatHookApdDone, String coatHookApdRoughly, String curtainMovementSmooth,
			String curtainRunnerCameOut, String curtainRunnerStopperFitted, String snackTableLoose,
			String snackTableTapper, String snackTableScrewMissing, String safetyRailTaper, String safetyRailLoose,
			String safetyRailBktLoose, String safetyRailBktTighten, String safetyRailBktTaper, String berthChainLoose,
			String berthChainHardwareLoose, String berthChainHardwareMissing, String bottleHolderLoose,
			String bottleHolderTaper, String bottoleHolderScrewMissing, String bottoleHolderScrewDamage,
			String berthMountingHardwareSidewallLoose, String berthMountingHardwareSidewallTaper,
			String berthMountingHardwareSidewallMissing, String berthMountingHardwarePillarLoose,
			String berthMountingHardwarePillarTaper, String berthMountingHardwarePillarMissing, String berthTapper,
			String berthFlapLoose, String berthFlapBulge, String flapAlStripExcessLength,
			String flapAlHardwareExcessLength, String transverseBerthLevel, String gapBackrestBerth,
			String backrestMovement, String backrestGrazingLadder, String backrestGrazingPanelseat,
			String latchCatchMissmatch, String burrLatchSeat, String burrCatchSeat, String holePartitionLatchSeat,
			String rexineTornBackrestSeat, String rexineTornBerth, String almirahHardwareLoose,
			String almirahHardwareMissing, String towerWorking, String almirahWorking, String almirahHole,
			String holeNearBottleHolder, String holeNearLatchSeat, String holeNearCatchSeat,
			String rexineTornBerthArmrest, String builderPlateScrewMissing, String builderPlateScrewMissmatch,
			String rexenePastedBacksideBerth, String testingObservationRemark) {
		this.furnishingAssetId = furnishingAssetId;
		this.protectionWallHardwareLoose = protectionWallHardwareLoose;
		this.protectionWallHardwareMissing = protectionWallHardwareMissing;
		this.luggageRackLoose = luggageRackLoose;
		this.luggageRackTaper = luggageRackTaper;
		this.luggageRackMissing = luggageRackMissing;
		this.mirrorNotPasted = mirrorNotPasted;
		this.mirrorRubberUprooted = mirrorRubberUprooted;
		this.coatHookLoose = coatHookLoose;
		this.coatHookMissing = coatHookMissing;
		this.coatHookApdDone = coatHookApdDone;
		this.coatHookApdRoughly = coatHookApdRoughly;
		this.curtainMovementSmooth = curtainMovementSmooth;
		this.curtainRunnerCameOut = curtainRunnerCameOut;
		this.curtainRunnerStopperFitted = curtainRunnerStopperFitted;
		this.snackTableLoose = snackTableLoose;
		this.snackTableTapper = snackTableTapper;
		this.snackTableScrewMissing = snackTableScrewMissing;
		this.safetyRailTaper = safetyRailTaper;
		this.safetyRailLoose = safetyRailLoose;
		this.safetyRailBktLoose = safetyRailBktLoose;
		this.safetyRailBktTighten = safetyRailBktTighten;
		this.safetyRailBktTaper = safetyRailBktTaper;
		this.berthChainLoose = berthChainLoose;
		this.berthChainHardwareLoose = berthChainHardwareLoose;
		this.berthChainHardwareMissing = berthChainHardwareMissing;
		this.bottleHolderLoose = bottleHolderLoose;
		this.bottleHolderTaper = bottleHolderTaper;
		this.bottoleHolderScrewMissing = bottoleHolderScrewMissing;
		this.bottoleHolderScrewDamage = bottoleHolderScrewDamage;
		this.berthMountingHardwareSidewallLoose = berthMountingHardwareSidewallLoose;
		this.berthMountingHardwareSidewallTaper = berthMountingHardwareSidewallTaper;
		this.berthMountingHardwareSidewallMissing = berthMountingHardwareSidewallMissing;
		this.berthMountingHardwarePillarLoose = berthMountingHardwarePillarLoose;
		this.berthMountingHardwarePillarTaper = berthMountingHardwarePillarTaper;
		this.berthMountingHardwarePillarMissing = berthMountingHardwarePillarMissing;
		this.berthTapper = berthTapper;
		this.berthFlapLoose = berthFlapLoose;
		this.berthFlapBulge = berthFlapBulge;
		this.flapAlStripExcessLength = flapAlStripExcessLength;
		this.flapAlHardwareExcessLength = flapAlHardwareExcessLength;
		this.transverseBerthLevel = transverseBerthLevel;
		this.gapBackrestBerth = gapBackrestBerth;
		this.backrestMovement = backrestMovement;
		this.backrestGrazingLadder = backrestGrazingLadder;
		this.backrestGrazingPanelseat = backrestGrazingPanelseat;
		this.latchCatchMissmatch = latchCatchMissmatch;
		this.burrLatchSeat = burrLatchSeat;
		this.burrCatchSeat = burrCatchSeat;
		this.holePartitionLatchSeat = holePartitionLatchSeat;
		this.rexineTornBackrestSeat = rexineTornBackrestSeat;
		this.rexineTornBerth = rexineTornBerth;
		this.almirahHardwareLoose = almirahHardwareLoose;
		this.almirahHardwareMissing = almirahHardwareMissing;
		this.towerWorking = towerWorking;
		this.almirahWorking = almirahWorking;
		this.almirahHole = almirahHole;
		this.holeNearBottleHolder = holeNearBottleHolder;
		this.holeNearLatchSeat = holeNearLatchSeat;
		this.holeNearCatchSeat = holeNearCatchSeat;
		this.rexineTornBerthArmrest = rexineTornBerthArmrest;
		this.builderPlateScrewMissing = builderPlateScrewMissing;
		this.builderPlateScrewMissmatch = builderPlateScrewMissmatch;
		this.rexenePastedBacksideBerth = rexenePastedBacksideBerth;
		this.testingObservationRemark = testingObservationRemark;
	}

	public int getFurnishingAssetId() {
		return this.furnishingAssetId;
	}

	public void setFurnishingAssetId(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public String getProtectionWallHardwareLoose() {
		return this.protectionWallHardwareLoose;
	}

	public void setProtectionWallHardwareLoose(String protectionWallHardwareLoose) {
		this.protectionWallHardwareLoose = protectionWallHardwareLoose;
	}

	public String getProtectionWallHardwareMissing() {
		return this.protectionWallHardwareMissing;
	}

	public void setProtectionWallHardwareMissing(String protectionWallHardwareMissing) {
		this.protectionWallHardwareMissing = protectionWallHardwareMissing;
	}

	public String getLuggageRackLoose() {
		return this.luggageRackLoose;
	}

	public void setLuggageRackLoose(String luggageRackLoose) {
		this.luggageRackLoose = luggageRackLoose;
	}

	public String getLuggageRackTaper() {
		return this.luggageRackTaper;
	}

	public void setLuggageRackTaper(String luggageRackTaper) {
		this.luggageRackTaper = luggageRackTaper;
	}

	public String getLuggageRackMissing() {
		return this.luggageRackMissing;
	}

	public void setLuggageRackMissing(String luggageRackMissing) {
		this.luggageRackMissing = luggageRackMissing;
	}

	public String getMirrorNotPasted() {
		return this.mirrorNotPasted;
	}

	public void setMirrorNotPasted(String mirrorNotPasted) {
		this.mirrorNotPasted = mirrorNotPasted;
	}

	public String getMirrorRubberUprooted() {
		return this.mirrorRubberUprooted;
	}

	public void setMirrorRubberUprooted(String mirrorRubberUprooted) {
		this.mirrorRubberUprooted = mirrorRubberUprooted;
	}

	public String getCoatHookLoose() {
		return this.coatHookLoose;
	}

	public void setCoatHookLoose(String coatHookLoose) {
		this.coatHookLoose = coatHookLoose;
	}

	public String getCoatHookMissing() {
		return this.coatHookMissing;
	}

	public void setCoatHookMissing(String coatHookMissing) {
		this.coatHookMissing = coatHookMissing;
	}

	public String getCoatHookApdDone() {
		return this.coatHookApdDone;
	}

	public void setCoatHookApdDone(String coatHookApdDone) {
		this.coatHookApdDone = coatHookApdDone;
	}

	public String getCoatHookApdRoughly() {
		return this.coatHookApdRoughly;
	}

	public void setCoatHookApdRoughly(String coatHookApdRoughly) {
		this.coatHookApdRoughly = coatHookApdRoughly;
	}

	public String getCurtainMovementSmooth() {
		return this.curtainMovementSmooth;
	}

	public void setCurtainMovementSmooth(String curtainMovementSmooth) {
		this.curtainMovementSmooth = curtainMovementSmooth;
	}

	public String getCurtainRunnerCameOut() {
		return this.curtainRunnerCameOut;
	}

	public void setCurtainRunnerCameOut(String curtainRunnerCameOut) {
		this.curtainRunnerCameOut = curtainRunnerCameOut;
	}

	public String getCurtainRunnerStopperFitted() {
		return this.curtainRunnerStopperFitted;
	}

	public void setCurtainRunnerStopperFitted(String curtainRunnerStopperFitted) {
		this.curtainRunnerStopperFitted = curtainRunnerStopperFitted;
	}

	public String getSnackTableLoose() {
		return this.snackTableLoose;
	}

	public void setSnackTableLoose(String snackTableLoose) {
		this.snackTableLoose = snackTableLoose;
	}

	public String getSnackTableTapper() {
		return this.snackTableTapper;
	}

	public void setSnackTableTapper(String snackTableTapper) {
		this.snackTableTapper = snackTableTapper;
	}

	public String getSnackTableScrewMissing() {
		return this.snackTableScrewMissing;
	}

	public void setSnackTableScrewMissing(String snackTableScrewMissing) {
		this.snackTableScrewMissing = snackTableScrewMissing;
	}

	public String getSafetyRailTaper() {
		return this.safetyRailTaper;
	}

	public void setSafetyRailTaper(String safetyRailTaper) {
		this.safetyRailTaper = safetyRailTaper;
	}

	public String getSafetyRailLoose() {
		return this.safetyRailLoose;
	}

	public void setSafetyRailLoose(String safetyRailLoose) {
		this.safetyRailLoose = safetyRailLoose;
	}

	public String getSafetyRailBktLoose() {
		return this.safetyRailBktLoose;
	}

	public void setSafetyRailBktLoose(String safetyRailBktLoose) {
		this.safetyRailBktLoose = safetyRailBktLoose;
	}

	public String getSafetyRailBktTighten() {
		return this.safetyRailBktTighten;
	}

	public void setSafetyRailBktTighten(String safetyRailBktTighten) {
		this.safetyRailBktTighten = safetyRailBktTighten;
	}

	public String getSafetyRailBktTaper() {
		return this.safetyRailBktTaper;
	}

	public void setSafetyRailBktTaper(String safetyRailBktTaper) {
		this.safetyRailBktTaper = safetyRailBktTaper;
	}

	public String getBerthChainLoose() {
		return this.berthChainLoose;
	}

	public void setBerthChainLoose(String berthChainLoose) {
		this.berthChainLoose = berthChainLoose;
	}

	public String getBerthChainHardwareLoose() {
		return this.berthChainHardwareLoose;
	}

	public void setBerthChainHardwareLoose(String berthChainHardwareLoose) {
		this.berthChainHardwareLoose = berthChainHardwareLoose;
	}

	public String getBerthChainHardwareMissing() {
		return this.berthChainHardwareMissing;
	}

	public void setBerthChainHardwareMissing(String berthChainHardwareMissing) {
		this.berthChainHardwareMissing = berthChainHardwareMissing;
	}

	public String getBottleHolderLoose() {
		return this.bottleHolderLoose;
	}

	public void setBottleHolderLoose(String bottleHolderLoose) {
		this.bottleHolderLoose = bottleHolderLoose;
	}

	public String getBottleHolderTaper() {
		return this.bottleHolderTaper;
	}

	public void setBottleHolderTaper(String bottleHolderTaper) {
		this.bottleHolderTaper = bottleHolderTaper;
	}

	public String getBottoleHolderScrewMissing() {
		return this.bottoleHolderScrewMissing;
	}

	public void setBottoleHolderScrewMissing(String bottoleHolderScrewMissing) {
		this.bottoleHolderScrewMissing = bottoleHolderScrewMissing;
	}

	public String getBottoleHolderScrewDamage() {
		return this.bottoleHolderScrewDamage;
	}

	public void setBottoleHolderScrewDamage(String bottoleHolderScrewDamage) {
		this.bottoleHolderScrewDamage = bottoleHolderScrewDamage;
	}

	public String getBerthMountingHardwareSidewallLoose() {
		return this.berthMountingHardwareSidewallLoose;
	}

	public void setBerthMountingHardwareSidewallLoose(String berthMountingHardwareSidewallLoose) {
		this.berthMountingHardwareSidewallLoose = berthMountingHardwareSidewallLoose;
	}

	public String getBerthMountingHardwareSidewallTaper() {
		return this.berthMountingHardwareSidewallTaper;
	}

	public void setBerthMountingHardwareSidewallTaper(String berthMountingHardwareSidewallTaper) {
		this.berthMountingHardwareSidewallTaper = berthMountingHardwareSidewallTaper;
	}

	public String getBerthMountingHardwareSidewallMissing() {
		return this.berthMountingHardwareSidewallMissing;
	}

	public void setBerthMountingHardwareSidewallMissing(String berthMountingHardwareSidewallMissing) {
		this.berthMountingHardwareSidewallMissing = berthMountingHardwareSidewallMissing;
	}

	public String getBerthMountingHardwarePillarLoose() {
		return this.berthMountingHardwarePillarLoose;
	}

	public void setBerthMountingHardwarePillarLoose(String berthMountingHardwarePillarLoose) {
		this.berthMountingHardwarePillarLoose = berthMountingHardwarePillarLoose;
	}

	public String getBerthMountingHardwarePillarTaper() {
		return this.berthMountingHardwarePillarTaper;
	}

	public void setBerthMountingHardwarePillarTaper(String berthMountingHardwarePillarTaper) {
		this.berthMountingHardwarePillarTaper = berthMountingHardwarePillarTaper;
	}

	public String getBerthMountingHardwarePillarMissing() {
		return this.berthMountingHardwarePillarMissing;
	}

	public void setBerthMountingHardwarePillarMissing(String berthMountingHardwarePillarMissing) {
		this.berthMountingHardwarePillarMissing = berthMountingHardwarePillarMissing;
	}

	public String getBerthTapper() {
		return this.berthTapper;
	}

	public void setBerthTapper(String berthTapper) {
		this.berthTapper = berthTapper;
	}

	public String getBerthFlapLoose() {
		return this.berthFlapLoose;
	}

	public void setBerthFlapLoose(String berthFlapLoose) {
		this.berthFlapLoose = berthFlapLoose;
	}

	public String getBerthFlapBulge() {
		return this.berthFlapBulge;
	}

	public void setBerthFlapBulge(String berthFlapBulge) {
		this.berthFlapBulge = berthFlapBulge;
	}

	public String getFlapAlStripExcessLength() {
		return this.flapAlStripExcessLength;
	}

	public void setFlapAlStripExcessLength(String flapAlStripExcessLength) {
		this.flapAlStripExcessLength = flapAlStripExcessLength;
	}

	public String getFlapAlHardwareExcessLength() {
		return this.flapAlHardwareExcessLength;
	}

	public void setFlapAlHardwareExcessLength(String flapAlHardwareExcessLength) {
		this.flapAlHardwareExcessLength = flapAlHardwareExcessLength;
	}

	public String getTransverseBerthLevel() {
		return this.transverseBerthLevel;
	}

	public void setTransverseBerthLevel(String transverseBerthLevel) {
		this.transverseBerthLevel = transverseBerthLevel;
	}

	public String getGapBackrestBerth() {
		return this.gapBackrestBerth;
	}

	public void setGapBackrestBerth(String gapBackrestBerth) {
		this.gapBackrestBerth = gapBackrestBerth;
	}

	public String getBackrestMovement() {
		return this.backrestMovement;
	}

	public void setBackrestMovement(String backrestMovement) {
		this.backrestMovement = backrestMovement;
	}

	public String getBackrestGrazingLadder() {
		return this.backrestGrazingLadder;
	}

	public void setBackrestGrazingLadder(String backrestGrazingLadder) {
		this.backrestGrazingLadder = backrestGrazingLadder;
	}

	public String getBackrestGrazingPanelseat() {
		return this.backrestGrazingPanelseat;
	}

	public void setBackrestGrazingPanelseat(String backrestGrazingPanelseat) {
		this.backrestGrazingPanelseat = backrestGrazingPanelseat;
	}

	public String getLatchCatchMissmatch() {
		return this.latchCatchMissmatch;
	}

	public void setLatchCatchMissmatch(String latchCatchMissmatch) {
		this.latchCatchMissmatch = latchCatchMissmatch;
	}

	public String getBurrLatchSeat() {
		return this.burrLatchSeat;
	}

	public void setBurrLatchSeat(String burrLatchSeat) {
		this.burrLatchSeat = burrLatchSeat;
	}

	public String getBurrCatchSeat() {
		return this.burrCatchSeat;
	}

	public void setBurrCatchSeat(String burrCatchSeat) {
		this.burrCatchSeat = burrCatchSeat;
	}

	public String getHolePartitionLatchSeat() {
		return this.holePartitionLatchSeat;
	}

	public void setHolePartitionLatchSeat(String holePartitionLatchSeat) {
		this.holePartitionLatchSeat = holePartitionLatchSeat;
	}

	public String getRexineTornBackrestSeat() {
		return this.rexineTornBackrestSeat;
	}

	public void setRexineTornBackrestSeat(String rexineTornBackrestSeat) {
		this.rexineTornBackrestSeat = rexineTornBackrestSeat;
	}

	public String getRexineTornBerth() {
		return this.rexineTornBerth;
	}

	public void setRexineTornBerth(String rexineTornBerth) {
		this.rexineTornBerth = rexineTornBerth;
	}

	public String getAlmirahHardwareLoose() {
		return this.almirahHardwareLoose;
	}

	public void setAlmirahHardwareLoose(String almirahHardwareLoose) {
		this.almirahHardwareLoose = almirahHardwareLoose;
	}

	public String getAlmirahHardwareMissing() {
		return this.almirahHardwareMissing;
	}

	public void setAlmirahHardwareMissing(String almirahHardwareMissing) {
		this.almirahHardwareMissing = almirahHardwareMissing;
	}

	public String getTowerWorking() {
		return this.towerWorking;
	}

	public void setTowerWorking(String towerWorking) {
		this.towerWorking = towerWorking;
	}

	public String getAlmirahWorking() {
		return this.almirahWorking;
	}

	public void setAlmirahWorking(String almirahWorking) {
		this.almirahWorking = almirahWorking;
	}

	public String getAlmirahHole() {
		return this.almirahHole;
	}

	public void setAlmirahHole(String almirahHole) {
		this.almirahHole = almirahHole;
	}

	public String getHoleNearBottleHolder() {
		return this.holeNearBottleHolder;
	}

	public void setHoleNearBottleHolder(String holeNearBottleHolder) {
		this.holeNearBottleHolder = holeNearBottleHolder;
	}

	public String getHoleNearLatchSeat() {
		return this.holeNearLatchSeat;
	}

	public void setHoleNearLatchSeat(String holeNearLatchSeat) {
		this.holeNearLatchSeat = holeNearLatchSeat;
	}

	public String getHoleNearCatchSeat() {
		return this.holeNearCatchSeat;
	}

	public void setHoleNearCatchSeat(String holeNearCatchSeat) {
		this.holeNearCatchSeat = holeNearCatchSeat;
	}

	public String getRexineTornBerthArmrest() {
		return this.rexineTornBerthArmrest;
	}

	public void setRexineTornBerthArmrest(String rexineTornBerthArmrest) {
		this.rexineTornBerthArmrest = rexineTornBerthArmrest;
	}

	public String getBuilderPlateScrewMissing() {
		return this.builderPlateScrewMissing;
	}

	public void setBuilderPlateScrewMissing(String builderPlateScrewMissing) {
		this.builderPlateScrewMissing = builderPlateScrewMissing;
	}

	public String getBuilderPlateScrewMissmatch() {
		return this.builderPlateScrewMissmatch;
	}

	public void setBuilderPlateScrewMissmatch(String builderPlateScrewMissmatch) {
		this.builderPlateScrewMissmatch = builderPlateScrewMissmatch;
	}

	public String getRexenePastedBacksideBerth() {
		return this.rexenePastedBacksideBerth;
	}

	public void setRexenePastedBacksideBerth(String rexenePastedBacksideBerth) {
		this.rexenePastedBacksideBerth = rexenePastedBacksideBerth;
	}

	public String getTestingObservationRemark() {
		return this.testingObservationRemark;
	}

	public void setTestingObservationRemark(String testingObservationRemark) {
		this.testingObservationRemark = testingObservationRemark;
	}

}
