package beans;
// Generated 6 Mar, 2020 3:39:33 PM by Hibernate Tools 4.0.1.Final

/**
 * QciWindowCeilingTrans generated by hbm2java
 */
public class QciWindowCeilingTrans implements java.io.Serializable {

	private int furnishingAssetId;
	private String screwMissingLtypeCeiling;
	private String screwMissingChipUp;
	private String doorwayGangwayCeilingAlign;
	private String doorwayGangwayCeilingDent;
	private String chipupDoorwayGangwayCeiling;
	private String excessGapDoorwayLinenroomCeiling;
	private String taperGapCorridorPartition;
	private String nylonRopeDoorwayCeiling;
	private String nylonRopeDoorwayCeilingUnlock;
	private String doorwayGangwayCeilingKnotted;
	private String gapWallceilingPartition;
	private String dentWallceilingPartition;
	private String epSheetWallceilingPartition;
	private String excessCutCeiling;
	private String dentMarkNearB;
	private String screwMissingCeiling;
	private String screwMissingSideCeiling;
	private String screwLooseSideCeiling;
	private String screwUnwantedHole;
	private String screwCeilingLevel;
	private String centreDiffuserLevelMismatch;
	private String centreDiffuserLevelBulge;
	private String centreDiffuserLockedPrperly;
	private String centreDiffuserLockedMissing;
	private String emergencyPullhandlerubbberSited;
	private String windowGlassCracked;
	private String gapCentreDiffuserSideceiling;
	private String gapSidewalceilingCentrediffuser;
	private String testingObservationRemark;

	public QciWindowCeilingTrans() {
	}

	public QciWindowCeilingTrans(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public QciWindowCeilingTrans(int furnishingAssetId, String screwMissingLtypeCeiling, String screwMissingChipUp,
			String doorwayGangwayCeilingAlign, String doorwayGangwayCeilingDent, String chipupDoorwayGangwayCeiling,
			String excessGapDoorwayLinenroomCeiling, String taperGapCorridorPartition, String nylonRopeDoorwayCeiling,
			String nylonRopeDoorwayCeilingUnlock, String doorwayGangwayCeilingKnotted, String gapWallceilingPartition,
			String dentWallceilingPartition, String epSheetWallceilingPartition, String excessCutCeiling,
			String dentMarkNearB, String screwMissingCeiling, String screwMissingSideCeiling,
			String screwLooseSideCeiling, String screwUnwantedHole, String screwCeilingLevel,
			String centreDiffuserLevelMismatch, String centreDiffuserLevelBulge, String centreDiffuserLockedPrperly,
			String centreDiffuserLockedMissing, String emergencyPullhandlerubbberSited, String windowGlassCracked,
			String gapCentreDiffuserSideceiling, String gapSidewalceilingCentrediffuser,
			String testingObservationRemark) {
		this.furnishingAssetId = furnishingAssetId;
		this.screwMissingLtypeCeiling = screwMissingLtypeCeiling;
		this.screwMissingChipUp = screwMissingChipUp;
		this.doorwayGangwayCeilingAlign = doorwayGangwayCeilingAlign;
		this.doorwayGangwayCeilingDent = doorwayGangwayCeilingDent;
		this.chipupDoorwayGangwayCeiling = chipupDoorwayGangwayCeiling;
		this.excessGapDoorwayLinenroomCeiling = excessGapDoorwayLinenroomCeiling;
		this.taperGapCorridorPartition = taperGapCorridorPartition;
		this.nylonRopeDoorwayCeiling = nylonRopeDoorwayCeiling;
		this.nylonRopeDoorwayCeilingUnlock = nylonRopeDoorwayCeilingUnlock;
		this.doorwayGangwayCeilingKnotted = doorwayGangwayCeilingKnotted;
		this.gapWallceilingPartition = gapWallceilingPartition;
		this.dentWallceilingPartition = dentWallceilingPartition;
		this.epSheetWallceilingPartition = epSheetWallceilingPartition;
		this.excessCutCeiling = excessCutCeiling;
		this.dentMarkNearB = dentMarkNearB;
		this.screwMissingCeiling = screwMissingCeiling;
		this.screwMissingSideCeiling = screwMissingSideCeiling;
		this.screwLooseSideCeiling = screwLooseSideCeiling;
		this.screwUnwantedHole = screwUnwantedHole;
		this.screwCeilingLevel = screwCeilingLevel;
		this.centreDiffuserLevelMismatch = centreDiffuserLevelMismatch;
		this.centreDiffuserLevelBulge = centreDiffuserLevelBulge;
		this.centreDiffuserLockedPrperly = centreDiffuserLockedPrperly;
		this.centreDiffuserLockedMissing = centreDiffuserLockedMissing;
		this.emergencyPullhandlerubbberSited = emergencyPullhandlerubbberSited;
		this.windowGlassCracked = windowGlassCracked;
		this.gapCentreDiffuserSideceiling = gapCentreDiffuserSideceiling;
		this.gapSidewalceilingCentrediffuser = gapSidewalceilingCentrediffuser;
		this.testingObservationRemark = testingObservationRemark;
	}

	public int getFurnishingAssetId() {
		return this.furnishingAssetId;
	}

	public void setFurnishingAssetId(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public String getScrewMissingLtypeCeiling() {
		return this.screwMissingLtypeCeiling;
	}

	public void setScrewMissingLtypeCeiling(String screwMissingLtypeCeiling) {
		this.screwMissingLtypeCeiling = screwMissingLtypeCeiling;
	}

	public String getScrewMissingChipUp() {
		return this.screwMissingChipUp;
	}

	public void setScrewMissingChipUp(String screwMissingChipUp) {
		this.screwMissingChipUp = screwMissingChipUp;
	}

	public String getDoorwayGangwayCeilingAlign() {
		return this.doorwayGangwayCeilingAlign;
	}

	public void setDoorwayGangwayCeilingAlign(String doorwayGangwayCeilingAlign) {
		this.doorwayGangwayCeilingAlign = doorwayGangwayCeilingAlign;
	}

	public String getDoorwayGangwayCeilingDent() {
		return this.doorwayGangwayCeilingDent;
	}

	public void setDoorwayGangwayCeilingDent(String doorwayGangwayCeilingDent) {
		this.doorwayGangwayCeilingDent = doorwayGangwayCeilingDent;
	}

	public String getChipupDoorwayGangwayCeiling() {
		return this.chipupDoorwayGangwayCeiling;
	}

	public void setChipupDoorwayGangwayCeiling(String chipupDoorwayGangwayCeiling) {
		this.chipupDoorwayGangwayCeiling = chipupDoorwayGangwayCeiling;
	}

	public String getExcessGapDoorwayLinenroomCeiling() {
		return this.excessGapDoorwayLinenroomCeiling;
	}

	public void setExcessGapDoorwayLinenroomCeiling(String excessGapDoorwayLinenroomCeiling) {
		this.excessGapDoorwayLinenroomCeiling = excessGapDoorwayLinenroomCeiling;
	}

	public String getTaperGapCorridorPartition() {
		return this.taperGapCorridorPartition;
	}

	public void setTaperGapCorridorPartition(String taperGapCorridorPartition) {
		this.taperGapCorridorPartition = taperGapCorridorPartition;
	}

	public String getNylonRopeDoorwayCeiling() {
		return this.nylonRopeDoorwayCeiling;
	}

	public void setNylonRopeDoorwayCeiling(String nylonRopeDoorwayCeiling) {
		this.nylonRopeDoorwayCeiling = nylonRopeDoorwayCeiling;
	}

	public String getNylonRopeDoorwayCeilingUnlock() {
		return this.nylonRopeDoorwayCeilingUnlock;
	}

	public void setNylonRopeDoorwayCeilingUnlock(String nylonRopeDoorwayCeilingUnlock) {
		this.nylonRopeDoorwayCeilingUnlock = nylonRopeDoorwayCeilingUnlock;
	}

	public String getDoorwayGangwayCeilingKnotted() {
		return this.doorwayGangwayCeilingKnotted;
	}

	public void setDoorwayGangwayCeilingKnotted(String doorwayGangwayCeilingKnotted) {
		this.doorwayGangwayCeilingKnotted = doorwayGangwayCeilingKnotted;
	}

	public String getGapWallceilingPartition() {
		return this.gapWallceilingPartition;
	}

	public void setGapWallceilingPartition(String gapWallceilingPartition) {
		this.gapWallceilingPartition = gapWallceilingPartition;
	}

	public String getDentWallceilingPartition() {
		return this.dentWallceilingPartition;
	}

	public void setDentWallceilingPartition(String dentWallceilingPartition) {
		this.dentWallceilingPartition = dentWallceilingPartition;
	}

	public String getEpSheetWallceilingPartition() {
		return this.epSheetWallceilingPartition;
	}

	public void setEpSheetWallceilingPartition(String epSheetWallceilingPartition) {
		this.epSheetWallceilingPartition = epSheetWallceilingPartition;
	}

	public String getExcessCutCeiling() {
		return this.excessCutCeiling;
	}

	public void setExcessCutCeiling(String excessCutCeiling) {
		this.excessCutCeiling = excessCutCeiling;
	}

	public String getDentMarkNearB() {
		return this.dentMarkNearB;
	}

	public void setDentMarkNearB(String dentMarkNearB) {
		this.dentMarkNearB = dentMarkNearB;
	}

	public String getScrewMissingCeiling() {
		return this.screwMissingCeiling;
	}

	public void setScrewMissingCeiling(String screwMissingCeiling) {
		this.screwMissingCeiling = screwMissingCeiling;
	}

	public String getScrewMissingSideCeiling() {
		return this.screwMissingSideCeiling;
	}

	public void setScrewMissingSideCeiling(String screwMissingSideCeiling) {
		this.screwMissingSideCeiling = screwMissingSideCeiling;
	}

	public String getScrewLooseSideCeiling() {
		return this.screwLooseSideCeiling;
	}

	public void setScrewLooseSideCeiling(String screwLooseSideCeiling) {
		this.screwLooseSideCeiling = screwLooseSideCeiling;
	}

	public String getScrewUnwantedHole() {
		return this.screwUnwantedHole;
	}

	public void setScrewUnwantedHole(String screwUnwantedHole) {
		this.screwUnwantedHole = screwUnwantedHole;
	}

	public String getScrewCeilingLevel() {
		return this.screwCeilingLevel;
	}

	public void setScrewCeilingLevel(String screwCeilingLevel) {
		this.screwCeilingLevel = screwCeilingLevel;
	}

	public String getCentreDiffuserLevelMismatch() {
		return this.centreDiffuserLevelMismatch;
	}

	public void setCentreDiffuserLevelMismatch(String centreDiffuserLevelMismatch) {
		this.centreDiffuserLevelMismatch = centreDiffuserLevelMismatch;
	}

	public String getCentreDiffuserLevelBulge() {
		return this.centreDiffuserLevelBulge;
	}

	public void setCentreDiffuserLevelBulge(String centreDiffuserLevelBulge) {
		this.centreDiffuserLevelBulge = centreDiffuserLevelBulge;
	}

	public String getCentreDiffuserLockedPrperly() {
		return this.centreDiffuserLockedPrperly;
	}

	public void setCentreDiffuserLockedPrperly(String centreDiffuserLockedPrperly) {
		this.centreDiffuserLockedPrperly = centreDiffuserLockedPrperly;
	}

	public String getCentreDiffuserLockedMissing() {
		return this.centreDiffuserLockedMissing;
	}

	public void setCentreDiffuserLockedMissing(String centreDiffuserLockedMissing) {
		this.centreDiffuserLockedMissing = centreDiffuserLockedMissing;
	}

	public String getEmergencyPullhandlerubbberSited() {
		return this.emergencyPullhandlerubbberSited;
	}

	public void setEmergencyPullhandlerubbberSited(String emergencyPullhandlerubbberSited) {
		this.emergencyPullhandlerubbberSited = emergencyPullhandlerubbberSited;
	}

	public String getWindowGlassCracked() {
		return this.windowGlassCracked;
	}

	public void setWindowGlassCracked(String windowGlassCracked) {
		this.windowGlassCracked = windowGlassCracked;
	}

	public String getGapCentreDiffuserSideceiling() {
		return this.gapCentreDiffuserSideceiling;
	}

	public void setGapCentreDiffuserSideceiling(String gapCentreDiffuserSideceiling) {
		this.gapCentreDiffuserSideceiling = gapCentreDiffuserSideceiling;
	}

	public String getGapSidewalceilingCentrediffuser() {
		return this.gapSidewalceilingCentrediffuser;
	}

	public void setGapSidewalceilingCentrediffuser(String gapSidewalceilingCentrediffuser) {
		this.gapSidewalceilingCentrediffuser = gapSidewalceilingCentrediffuser;
	}

	public String getTestingObservationRemark() {
		return this.testingObservationRemark;
	}

	public void setTestingObservationRemark(String testingObservationRemark) {
		this.testingObservationRemark = testingObservationRemark;
	}

}
