package beans;
// Generated 20 Mar, 2020 5:30:42 PM by Hibernate Tools 4.0.1.Final

/**
 * QcraTransId generated by hbm2java
 */
public class QcraTransId implements java.io.Serializable {

	private int furnishingAssetId;
	private String furnishingTestStage;

	public QcraTransId() {
	}

	public QcraTransId(int furnishingAssetId, String furnishingTestStage) {
		this.furnishingAssetId = furnishingAssetId;
		this.furnishingTestStage = furnishingTestStage;
	}

	public int getFurnishingAssetId() {
		return this.furnishingAssetId;
	}

	public void setFurnishingAssetId(int furnishingAssetId) {
		this.furnishingAssetId = furnishingAssetId;
	}

	public String getFurnishingTestStage() {
		return this.furnishingTestStage;
	}

	public void setFurnishingTestStage(String furnishingTestStage) {
		this.furnishingTestStage = furnishingTestStage;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QcraTransId))
			return false;
		QcraTransId castOther = (QcraTransId) other;

		return (this.getFurnishingAssetId() == castOther.getFurnishingAssetId())
				&& ((this.getFurnishingTestStage() == castOther.getFurnishingTestStage())
						|| (this.getFurnishingTestStage() != null && castOther.getFurnishingTestStage() != null
								&& this.getFurnishingTestStage().equals(castOther.getFurnishingTestStage())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFurnishingAssetId();
		result = 37 * result + (getFurnishingTestStage() == null ? 0 : this.getFurnishingTestStage().hashCode());
		return result;
	}

}
