package beans;
// Generated 23 Jan, 2020 5:20:00 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * ShellCheckListSip generated by hbm2java
 */
public class ShellCheckListSip implements java.io.Serializable {

	private int shellAssetId;
	private String waterTankBracket;
	private String crossBrace;
	private String sidewallAssembly;
	private String stiffingPlate;
	private String loroPipeBracket;
	private String footStepBracket;
	private String liftingPad;
	private String curveRollBracket;
	private String waterTankLiner;
	private String sideLavMountingBracket;
	private String sideHoseCouplingBracket;
	private String groundingFlapBracket;
	private String powerPanelBracket;
	private String entryBy;
	private Date entryTime;

	public ShellCheckListSip() {
	}

	public ShellCheckListSip(int shellAssetId) {
		this.shellAssetId = shellAssetId;
	}

	public ShellCheckListSip(int shellAssetId, String waterTankBracket, String crossBrace, String sidewallAssembly,
			String stiffingPlate, String loroPipeBracket, String footStepBracket, String liftingPad,
			String curveRollBracket, String waterTankLiner, String sideLavMountingBracket,
			String sideHoseCouplingBracket, String groundingFlapBracket, String powerPanelBracket, String entryBy,
			Date entryTime) {
		this.shellAssetId = shellAssetId;
		this.waterTankBracket = waterTankBracket;
		this.crossBrace = crossBrace;
		this.sidewallAssembly = sidewallAssembly;
		this.stiffingPlate = stiffingPlate;
		this.loroPipeBracket = loroPipeBracket;
		this.footStepBracket = footStepBracket;
		this.liftingPad = liftingPad;
		this.curveRollBracket = curveRollBracket;
		this.waterTankLiner = waterTankLiner;
		this.sideLavMountingBracket = sideLavMountingBracket;
		this.sideHoseCouplingBracket = sideHoseCouplingBracket;
		this.groundingFlapBracket = groundingFlapBracket;
		this.powerPanelBracket = powerPanelBracket;
		this.entryBy = entryBy;
		this.entryTime = entryTime;
	}

	public int getShellAssetId() {
		return this.shellAssetId;
	}

	public void setShellAssetId(int shellAssetId) {
		this.shellAssetId = shellAssetId;
	}

	public String getWaterTankBracket() {
		return this.waterTankBracket;
	}

	public void setWaterTankBracket(String waterTankBracket) {
		this.waterTankBracket = waterTankBracket;
	}

	public String getCrossBrace() {
		return this.crossBrace;
	}

	public void setCrossBrace(String crossBrace) {
		this.crossBrace = crossBrace;
	}

	public String getSidewallAssembly() {
		return this.sidewallAssembly;
	}

	public void setSidewallAssembly(String sidewallAssembly) {
		this.sidewallAssembly = sidewallAssembly;
	}

	public String getStiffingPlate() {
		return this.stiffingPlate;
	}

	public void setStiffingPlate(String stiffingPlate) {
		this.stiffingPlate = stiffingPlate;
	}

	public String getLoroPipeBracket() {
		return this.loroPipeBracket;
	}

	public void setLoroPipeBracket(String loroPipeBracket) {
		this.loroPipeBracket = loroPipeBracket;
	}

	public String getFootStepBracket() {
		return this.footStepBracket;
	}

	public void setFootStepBracket(String footStepBracket) {
		this.footStepBracket = footStepBracket;
	}

	public String getLiftingPad() {
		return this.liftingPad;
	}

	public void setLiftingPad(String liftingPad) {
		this.liftingPad = liftingPad;
	}

	public String getCurveRollBracket() {
		return this.curveRollBracket;
	}

	public void setCurveRollBracket(String curveRollBracket) {
		this.curveRollBracket = curveRollBracket;
	}

	public String getWaterTankLiner() {
		return this.waterTankLiner;
	}

	public void setWaterTankLiner(String waterTankLiner) {
		this.waterTankLiner = waterTankLiner;
	}

	public String getSideLavMountingBracket() {
		return this.sideLavMountingBracket;
	}

	public void setSideLavMountingBracket(String sideLavMountingBracket) {
		this.sideLavMountingBracket = sideLavMountingBracket;
	}

	public String getSideHoseCouplingBracket() {
		return this.sideHoseCouplingBracket;
	}

	public void setSideHoseCouplingBracket(String sideHoseCouplingBracket) {
		this.sideHoseCouplingBracket = sideHoseCouplingBracket;
	}

	public String getGroundingFlapBracket() {
		return this.groundingFlapBracket;
	}

	public void setGroundingFlapBracket(String groundingFlapBracket) {
		this.groundingFlapBracket = groundingFlapBracket;
	}

	public String getPowerPanelBracket() {
		return this.powerPanelBracket;
	}

	public void setPowerPanelBracket(String powerPanelBracket) {
		this.powerPanelBracket = powerPanelBracket;
	}

	public String getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(String entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

}
