package beans;
// Generated 23 Jan, 2020 5:23:01 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * ShellFinalSipTran generated by hbm2java
 */
public class ShellFinalSipTran implements java.io.Serializable {

	private int shellAssetId;
	private String docNo;
	private String docNoRev;
	private Date docNoDate;
	private String shiftOfTesting;
	private Date dateOfTesting;
	private String alignmentRoofarchCarline;
	private String weldingGrindingRwg;
	private String doorCutBackPiece;
	private String carlineRoofsheetLeakageTest;
	private String weldingAttachmentWallHolding;
	private String weldingAuxiliaryWatertankBkt;
	private String weldingGrindingSidewall;
	private String weldingStiffeningPlate;
	private String diagonalRmpuMountingStud;
	private String roofelementEndwallJoint;
	private String dimensionAcOpeningRmpu;
	private String lavMountingBracketDistance;
	private String carlineRoofsheetWelding;
	private String roofarchCarlineWelding;
	private String sidewallVerticalpillarCoveringPlateWeld;
	private String doorCutoutWelding;
	private String roofelementLavsidewallWelding;
	private String lavsidewallSidewallWelding;
	private String endwallLavsidewallRoofUfWelding;
	private String shellAssemblyGrinding;
	private String roofelementRmpuHoleDieAlignment;
	private String roofBktFitmentStage4;
	private String bodyWidth;
	private String insulatingPin;
	private String crossBraceHeightL3t;
	private String crossBraceHeightL2t;
	private String roofHeightTroughSheet;
	private String dbCnBkt;
	private String parameterRemark;
	private String finalTestingObservation;
	private String entryBy;
	private Date entryTime;

	public ShellFinalSipTran() {
	}

	public ShellFinalSipTran(int shellAssetId) {
		this.shellAssetId = shellAssetId;
	}

	public ShellFinalSipTran(int shellAssetId, String docNo, String docNoRev, Date docNoDate, String shiftOfTesting,
			Date dateOfTesting, String alignmentRoofarchCarline, String weldingGrindingRwg, String doorCutBackPiece,
			String carlineRoofsheetLeakageTest, String weldingAttachmentWallHolding,
			String weldingAuxiliaryWatertankBkt, String weldingGrindingSidewall, String weldingStiffeningPlate,
			String diagonalRmpuMountingStud, String roofelementEndwallJoint, String dimensionAcOpeningRmpu,
			String lavMountingBracketDistance, String carlineRoofsheetWelding, String roofarchCarlineWelding,
			String sidewallVerticalpillarCoveringPlateWeld, String doorCutoutWelding,
			String roofelementLavsidewallWelding, String lavsidewallSidewallWelding,
			String endwallLavsidewallRoofUfWelding, String shellAssemblyGrinding,
			String roofelementRmpuHoleDieAlignment, String roofBktFitmentStage4, String bodyWidth, String insulatingPin,
			String crossBraceHeightL3t, String crossBraceHeightL2t, String roofHeightTroughSheet, String dbCnBkt,
			String parameterRemark, String finalTestingObservation, String entryBy, Date entryTime) {
		this.shellAssetId = shellAssetId;
		this.docNo = docNo;
		this.docNoRev = docNoRev;
		this.docNoDate = docNoDate;
		this.shiftOfTesting = shiftOfTesting;
		this.dateOfTesting = dateOfTesting;
		this.alignmentRoofarchCarline = alignmentRoofarchCarline;
		this.weldingGrindingRwg = weldingGrindingRwg;
		this.doorCutBackPiece = doorCutBackPiece;
		this.carlineRoofsheetLeakageTest = carlineRoofsheetLeakageTest;
		this.weldingAttachmentWallHolding = weldingAttachmentWallHolding;
		this.weldingAuxiliaryWatertankBkt = weldingAuxiliaryWatertankBkt;
		this.weldingGrindingSidewall = weldingGrindingSidewall;
		this.weldingStiffeningPlate = weldingStiffeningPlate;
		this.diagonalRmpuMountingStud = diagonalRmpuMountingStud;
		this.roofelementEndwallJoint = roofelementEndwallJoint;
		this.dimensionAcOpeningRmpu = dimensionAcOpeningRmpu;
		this.lavMountingBracketDistance = lavMountingBracketDistance;
		this.carlineRoofsheetWelding = carlineRoofsheetWelding;
		this.roofarchCarlineWelding = roofarchCarlineWelding;
		this.sidewallVerticalpillarCoveringPlateWeld = sidewallVerticalpillarCoveringPlateWeld;
		this.doorCutoutWelding = doorCutoutWelding;
		this.roofelementLavsidewallWelding = roofelementLavsidewallWelding;
		this.lavsidewallSidewallWelding = lavsidewallSidewallWelding;
		this.endwallLavsidewallRoofUfWelding = endwallLavsidewallRoofUfWelding;
		this.shellAssemblyGrinding = shellAssemblyGrinding;
		this.roofelementRmpuHoleDieAlignment = roofelementRmpuHoleDieAlignment;
		this.roofBktFitmentStage4 = roofBktFitmentStage4;
		this.bodyWidth = bodyWidth;
		this.insulatingPin = insulatingPin;
		this.crossBraceHeightL3t = crossBraceHeightL3t;
		this.crossBraceHeightL2t = crossBraceHeightL2t;
		this.roofHeightTroughSheet = roofHeightTroughSheet;
		this.dbCnBkt = dbCnBkt;
		this.parameterRemark = parameterRemark;
		this.finalTestingObservation = finalTestingObservation;
		this.entryBy = entryBy;
		this.entryTime = entryTime;
	}

	public int getShellAssetId() {
		return this.shellAssetId;
	}

	public void setShellAssetId(int shellAssetId) {
		this.shellAssetId = shellAssetId;
	}

	public String getDocNo() {
		return this.docNo;
	}

	public void setDocNo(String docNo) {
		this.docNo = docNo;
	}

	public String getDocNoRev() {
		return this.docNoRev;
	}

	public void setDocNoRev(String docNoRev) {
		this.docNoRev = docNoRev;
	}

	public Date getDocNoDate() {
		return this.docNoDate;
	}

	public void setDocNoDate(Date docNoDate) {
		this.docNoDate = docNoDate;
	}

	public String getShiftOfTesting() {
		return this.shiftOfTesting;
	}

	public void setShiftOfTesting(String shiftOfTesting) {
		this.shiftOfTesting = shiftOfTesting;
	}

	public Date getDateOfTesting() {
		return this.dateOfTesting;
	}

	public void setDateOfTesting(Date dateOfTesting) {
		this.dateOfTesting = dateOfTesting;
	}

	public String getAlignmentRoofarchCarline() {
		return this.alignmentRoofarchCarline;
	}

	public void setAlignmentRoofarchCarline(String alignmentRoofarchCarline) {
		this.alignmentRoofarchCarline = alignmentRoofarchCarline;
	}

	public String getWeldingGrindingRwg() {
		return this.weldingGrindingRwg;
	}

	public void setWeldingGrindingRwg(String weldingGrindingRwg) {
		this.weldingGrindingRwg = weldingGrindingRwg;
	}

	public String getDoorCutBackPiece() {
		return this.doorCutBackPiece;
	}

	public void setDoorCutBackPiece(String doorCutBackPiece) {
		this.doorCutBackPiece = doorCutBackPiece;
	}

	public String getCarlineRoofsheetLeakageTest() {
		return this.carlineRoofsheetLeakageTest;
	}

	public void setCarlineRoofsheetLeakageTest(String carlineRoofsheetLeakageTest) {
		this.carlineRoofsheetLeakageTest = carlineRoofsheetLeakageTest;
	}

	public String getWeldingAttachmentWallHolding() {
		return this.weldingAttachmentWallHolding;
	}

	public void setWeldingAttachmentWallHolding(String weldingAttachmentWallHolding) {
		this.weldingAttachmentWallHolding = weldingAttachmentWallHolding;
	}

	public String getWeldingAuxiliaryWatertankBkt() {
		return this.weldingAuxiliaryWatertankBkt;
	}

	public void setWeldingAuxiliaryWatertankBkt(String weldingAuxiliaryWatertankBkt) {
		this.weldingAuxiliaryWatertankBkt = weldingAuxiliaryWatertankBkt;
	}

	public String getWeldingGrindingSidewall() {
		return this.weldingGrindingSidewall;
	}

	public void setWeldingGrindingSidewall(String weldingGrindingSidewall) {
		this.weldingGrindingSidewall = weldingGrindingSidewall;
	}

	public String getWeldingStiffeningPlate() {
		return this.weldingStiffeningPlate;
	}

	public void setWeldingStiffeningPlate(String weldingStiffeningPlate) {
		this.weldingStiffeningPlate = weldingStiffeningPlate;
	}

	public String getDiagonalRmpuMountingStud() {
		return this.diagonalRmpuMountingStud;
	}

	public void setDiagonalRmpuMountingStud(String diagonalRmpuMountingStud) {
		this.diagonalRmpuMountingStud = diagonalRmpuMountingStud;
	}

	public String getRoofelementEndwallJoint() {
		return this.roofelementEndwallJoint;
	}

	public void setRoofelementEndwallJoint(String roofelementEndwallJoint) {
		this.roofelementEndwallJoint = roofelementEndwallJoint;
	}

	public String getDimensionAcOpeningRmpu() {
		return this.dimensionAcOpeningRmpu;
	}

	public void setDimensionAcOpeningRmpu(String dimensionAcOpeningRmpu) {
		this.dimensionAcOpeningRmpu = dimensionAcOpeningRmpu;
	}

	public String getLavMountingBracketDistance() {
		return this.lavMountingBracketDistance;
	}

	public void setLavMountingBracketDistance(String lavMountingBracketDistance) {
		this.lavMountingBracketDistance = lavMountingBracketDistance;
	}

	public String getCarlineRoofsheetWelding() {
		return this.carlineRoofsheetWelding;
	}

	public void setCarlineRoofsheetWelding(String carlineRoofsheetWelding) {
		this.carlineRoofsheetWelding = carlineRoofsheetWelding;
	}

	public String getRoofarchCarlineWelding() {
		return this.roofarchCarlineWelding;
	}

	public void setRoofarchCarlineWelding(String roofarchCarlineWelding) {
		this.roofarchCarlineWelding = roofarchCarlineWelding;
	}

	public String getSidewallVerticalpillarCoveringPlateWeld() {
		return this.sidewallVerticalpillarCoveringPlateWeld;
	}

	public void setSidewallVerticalpillarCoveringPlateWeld(String sidewallVerticalpillarCoveringPlateWeld) {
		this.sidewallVerticalpillarCoveringPlateWeld = sidewallVerticalpillarCoveringPlateWeld;
	}

	public String getDoorCutoutWelding() {
		return this.doorCutoutWelding;
	}

	public void setDoorCutoutWelding(String doorCutoutWelding) {
		this.doorCutoutWelding = doorCutoutWelding;
	}

	public String getRoofelementLavsidewallWelding() {
		return this.roofelementLavsidewallWelding;
	}

	public void setRoofelementLavsidewallWelding(String roofelementLavsidewallWelding) {
		this.roofelementLavsidewallWelding = roofelementLavsidewallWelding;
	}

	public String getLavsidewallSidewallWelding() {
		return this.lavsidewallSidewallWelding;
	}

	public void setLavsidewallSidewallWelding(String lavsidewallSidewallWelding) {
		this.lavsidewallSidewallWelding = lavsidewallSidewallWelding;
	}

	public String getEndwallLavsidewallRoofUfWelding() {
		return this.endwallLavsidewallRoofUfWelding;
	}

	public void setEndwallLavsidewallRoofUfWelding(String endwallLavsidewallRoofUfWelding) {
		this.endwallLavsidewallRoofUfWelding = endwallLavsidewallRoofUfWelding;
	}

	public String getShellAssemblyGrinding() {
		return this.shellAssemblyGrinding;
	}

	public void setShellAssemblyGrinding(String shellAssemblyGrinding) {
		this.shellAssemblyGrinding = shellAssemblyGrinding;
	}

	public String getRoofelementRmpuHoleDieAlignment() {
		return this.roofelementRmpuHoleDieAlignment;
	}

	public void setRoofelementRmpuHoleDieAlignment(String roofelementRmpuHoleDieAlignment) {
		this.roofelementRmpuHoleDieAlignment = roofelementRmpuHoleDieAlignment;
	}

	public String getRoofBktFitmentStage4() {
		return this.roofBktFitmentStage4;
	}

	public void setRoofBktFitmentStage4(String roofBktFitmentStage4) {
		this.roofBktFitmentStage4 = roofBktFitmentStage4;
	}

	public String getBodyWidth() {
		return this.bodyWidth;
	}

	public void setBodyWidth(String bodyWidth) {
		this.bodyWidth = bodyWidth;
	}

	public String getInsulatingPin() {
		return this.insulatingPin;
	}

	public void setInsulatingPin(String insulatingPin) {
		this.insulatingPin = insulatingPin;
	}

	public String getCrossBraceHeightL3t() {
		return this.crossBraceHeightL3t;
	}

	public void setCrossBraceHeightL3t(String crossBraceHeightL3t) {
		this.crossBraceHeightL3t = crossBraceHeightL3t;
	}

	public String getCrossBraceHeightL2t() {
		return this.crossBraceHeightL2t;
	}

	public void setCrossBraceHeightL2t(String crossBraceHeightL2t) {
		this.crossBraceHeightL2t = crossBraceHeightL2t;
	}

	public String getRoofHeightTroughSheet() {
		return this.roofHeightTroughSheet;
	}

	public void setRoofHeightTroughSheet(String roofHeightTroughSheet) {
		this.roofHeightTroughSheet = roofHeightTroughSheet;
	}

	public String getDbCnBkt() {
		return this.dbCnBkt;
	}

	public void setDbCnBkt(String dbCnBkt) {
		this.dbCnBkt = dbCnBkt;
	}

	public String getParameterRemark() {
		return this.parameterRemark;
	}

	public void setParameterRemark(String parameterRemark) {
		this.parameterRemark = parameterRemark;
	}

	public String getFinalTestingObservation() {
		return this.finalTestingObservation;
	}

	public void setFinalTestingObservation(String finalTestingObservation) {
		this.finalTestingObservation = finalTestingObservation;
	}

	public String getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(String entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

}
