package beans;
// Generated 21 Jan, 2020 3:00:06 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * ShellStage4SipTran generated by hbm2java
 */
public class ShellStage4SipTran implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
	private int shellAssetId;
	private String stage4SipDocNo;
	private String stage4SipShift;
	private Date stage4SipDate;
	private String stage4WorkBy;
	private String stage4DrawingNo;
	private String stage4WiNo;
	private String distancePartitionFrameSingleLh;
	private String distancePartitionFrameCabinRh;
	private String widthCorridorPartitionFrame;
	private String distanceDoorcutoutSlidingdoor;
	private String distanceMiddleDoorPullboxbkt;
	private String distancePullboxbktCenterlinePp;
	private String distancePullboxbktCenterlineNpp;
	private String fitmentWatertankbracketBothside;
	private String heightChannelcomplete;
	private String distanceSidewallPartitionpillar;
	private String heightBackpieceLuggageracke;
	private String distanceDestinationBoard;
	private String diatanceSidewallpillarPrtmember;
	private String heightRoofflangeFramepart;
	private String ductInternallogitudinalLateral;
	private String distanceDoorwayCrewcompGenroom;
	private String distanceAuxWatertankbktCentre;
	private String disableLavDoor;
	private String disableLavDoorWidth;
	private String heightBottomroofCrossbracesbottom;
	private String passengerLavArea;
	private String distanceLavPrtframeEnd;
	private String distanceLavPrtframeLavPrtframe;
	private Integer berthbktLowerLh;
	private Integer berthbktMiddleLh;
	private Integer berthbktUpperLh;
	private Integer berthbktLowerRh;
	private Integer berthbktUpperRh;
	private String dogBoxArea;
	private String controlRoomArea;
	private String stretcherRoomArea;
	private String distanceSlidingDoorStopper;
	private String distanceLavMountingbkt;
	private String distanceAuxWatertankbkt;
	private String heightBktcompleteRoofflange;
	private String distancePowerpanelmountingCenterline;
	private String distanceCoachcenterlineAuxiliarybkt;
	private String heightLowerberthUpperberth;
	private String distancePullboxPullbox;
	private String distanceLuggagerackRoofflangetop;
	private String distanceDoorAttachmentbkt;
	private String distancePullboxCarlinearch;
	private String heightCrossbraceRoofflange;
	private String mountingangleLowerluggagerackBottomsidewall;
	private String fitmentCrossBraces;
	private String fitmentStiffeningPlate;
	private String fitmentPowerPanelFrame;
	private String fitmentWeldingPartitionFrame;
	private String roofbktWireclamping;
	private String detailsModification;
	private String detailsTrialItem;
	private String remarks;
	private String stage4TestingStatus;
	private String shellAssembly4ObervationRmk;
	private String entryBy;
	private Date entryTime;

	public ShellStage4SipTran() {
	}

	public ShellStage4SipTran(int shellAssetId) {
		this.shellAssetId = shellAssetId;
	}

	public ShellStage4SipTran(int shellAssetId, String stage4SipDocNo, String stage4SipShift, Date stage4SipDate,
			String stage4WorkBy, String stage4DrawingNo, String stage4WiNo, String distancePartitionFrameSingleLh,
			String distancePartitionFrameCabinRh, String widthCorridorPartitionFrame,
			String distanceDoorcutoutSlidingdoor, String distanceMiddleDoorPullboxbkt,
			String distancePullboxbktCenterlinePp, String distancePullboxbktCenterlineNpp,
			String fitmentWatertankbracketBothside, String heightChannelcomplete,
			String distanceSidewallPartitionpillar, String heightBackpieceLuggageracke, String distanceDestinationBoard,
			String diatanceSidewallpillarPrtmember, String heightRoofflangeFramepart,
			String ductInternallogitudinalLateral, String distanceDoorwayCrewcompGenroom,
			String distanceAuxWatertankbktCentre, String disableLavDoor, String disableLavDoorWidth,
			String heightBottomroofCrossbracesbottom, String passengerLavArea, String distanceLavPrtframeEnd,
			String distanceLavPrtframeLavPrtframe, Integer berthbktLowerLh, Integer berthbktMiddleLh,
			Integer berthbktUpperLh, Integer berthbktLowerRh, Integer berthbktUpperRh, String dogBoxArea,
			String controlRoomArea, String stretcherRoomArea, String distanceSlidingDoorStopper,
			String distanceLavMountingbkt, String distanceAuxWatertankbkt, String heightBktcompleteRoofflange,
			String distancePowerpanelmountingCenterline, String distanceCoachcenterlineAuxiliarybkt,
			String heightLowerberthUpperberth, String distancePullboxPullbox, String distanceLuggagerackRoofflangetop,
			String distanceDoorAttachmentbkt, String distancePullboxCarlinearch, String heightCrossbraceRoofflange,
			String mountingangleLowerluggagerackBottomsidewall, String fitmentCrossBraces,
			String fitmentStiffeningPlate, String fitmentPowerPanelFrame, String fitmentWeldingPartitionFrame,
			String roofbktWireclamping, String detailsModification, String detailsTrialItem, String remarks,
			String stage4TestingStatus,String shellAssembly4ObervationRmk, String entryBy, Date entryTime) {
		this.shellAssetId = shellAssetId;
		this.stage4SipDocNo = stage4SipDocNo;
		this.stage4SipShift = stage4SipShift;
		this.stage4SipDate = stage4SipDate;
		this.stage4WorkBy = stage4WorkBy;
		this.stage4DrawingNo = stage4DrawingNo;
		this.stage4WiNo = stage4WiNo;
		this.distancePartitionFrameSingleLh = distancePartitionFrameSingleLh;
		this.distancePartitionFrameCabinRh = distancePartitionFrameCabinRh;
		this.widthCorridorPartitionFrame = widthCorridorPartitionFrame;
		this.distanceDoorcutoutSlidingdoor = distanceDoorcutoutSlidingdoor;
		this.distanceMiddleDoorPullboxbkt = distanceMiddleDoorPullboxbkt;
		this.distancePullboxbktCenterlinePp = distancePullboxbktCenterlinePp;
		this.distancePullboxbktCenterlineNpp = distancePullboxbktCenterlineNpp;
		this.fitmentWatertankbracketBothside = fitmentWatertankbracketBothside;
		this.heightChannelcomplete = heightChannelcomplete;
		this.distanceSidewallPartitionpillar = distanceSidewallPartitionpillar;
		this.heightBackpieceLuggageracke = heightBackpieceLuggageracke;
		this.distanceDestinationBoard = distanceDestinationBoard;
		this.diatanceSidewallpillarPrtmember = diatanceSidewallpillarPrtmember;
		this.heightRoofflangeFramepart = heightRoofflangeFramepart;
		this.ductInternallogitudinalLateral = ductInternallogitudinalLateral;
		this.distanceDoorwayCrewcompGenroom = distanceDoorwayCrewcompGenroom;
		this.distanceAuxWatertankbktCentre = distanceAuxWatertankbktCentre;
		this.disableLavDoor = disableLavDoor;
		this.disableLavDoorWidth = disableLavDoorWidth;
		this.heightBottomroofCrossbracesbottom = heightBottomroofCrossbracesbottom;
		this.passengerLavArea = passengerLavArea;
		this.distanceLavPrtframeEnd = distanceLavPrtframeEnd;
		this.distanceLavPrtframeLavPrtframe = distanceLavPrtframeLavPrtframe;
		this.berthbktLowerLh = berthbktLowerLh;
		this.berthbktMiddleLh = berthbktMiddleLh;
		this.berthbktUpperLh = berthbktUpperLh;
		this.berthbktLowerRh = berthbktLowerRh;
		this.berthbktUpperRh = berthbktUpperRh;
		this.dogBoxArea = dogBoxArea;
		this.controlRoomArea = controlRoomArea;
		this.stretcherRoomArea = stretcherRoomArea;
		this.distanceSlidingDoorStopper = distanceSlidingDoorStopper;
		this.distanceLavMountingbkt = distanceLavMountingbkt;
		this.distanceAuxWatertankbkt = distanceAuxWatertankbkt;
		this.heightBktcompleteRoofflange = heightBktcompleteRoofflange;
		this.distancePowerpanelmountingCenterline = distancePowerpanelmountingCenterline;
		this.distanceCoachcenterlineAuxiliarybkt = distanceCoachcenterlineAuxiliarybkt;
		this.heightLowerberthUpperberth = heightLowerberthUpperberth;
		this.distancePullboxPullbox = distancePullboxPullbox;
		this.distanceLuggagerackRoofflangetop = distanceLuggagerackRoofflangetop;
		this.distanceDoorAttachmentbkt = distanceDoorAttachmentbkt;
		this.distancePullboxCarlinearch = distancePullboxCarlinearch;
		this.heightCrossbraceRoofflange = heightCrossbraceRoofflange;
		this.mountingangleLowerluggagerackBottomsidewall = mountingangleLowerluggagerackBottomsidewall;
		this.fitmentCrossBraces = fitmentCrossBraces;
		this.fitmentStiffeningPlate = fitmentStiffeningPlate;
		this.fitmentPowerPanelFrame = fitmentPowerPanelFrame;
		this.fitmentWeldingPartitionFrame = fitmentWeldingPartitionFrame;
		this.roofbktWireclamping = roofbktWireclamping;
		this.detailsModification = detailsModification;
		this.detailsTrialItem = detailsTrialItem;
		this.remarks = remarks;
		this.stage4TestingStatus = stage4TestingStatus;
		this.shellAssembly4ObervationRmk=shellAssembly4ObervationRmk;
		this.entryBy = entryBy;
		this.entryTime = entryTime;
	}

	public int getShellAssetId() {
		return this.shellAssetId;
	}

	public void setShellAssetId(int shellAssetId) {
		this.shellAssetId = shellAssetId;
	}

	public String getStage4SipDocNo() {
		return this.stage4SipDocNo;
	}

	public void setStage4SipDocNo(String stage4SipDocNo) {
		this.stage4SipDocNo = stage4SipDocNo;
	}

	public String getStage4SipShift() {
		return this.stage4SipShift;
	}

	public void setStage4SipShift(String stage4SipShift) {
		this.stage4SipShift = stage4SipShift;
	}

	public Date getStage4SipDate() {
		return this.stage4SipDate;
	}

	public void setStage4SipDate(Date stage4SipDate) {
		this.stage4SipDate = stage4SipDate;
	}

	public String getStage4WorkBy() {
		return this.stage4WorkBy;
	}

	public void setStage4WorkBy(String stage4WorkBy) {
		this.stage4WorkBy = stage4WorkBy;
	}

	public String getStage4DrawingNo() {
		return this.stage4DrawingNo;
	}

	public void setStage4DrawingNo(String stage4DrawingNo) {
		this.stage4DrawingNo = stage4DrawingNo;
	}

	public String getStage4WiNo() {
		return this.stage4WiNo;
	}

	public void setStage4WiNo(String stage4WiNo) {
		this.stage4WiNo = stage4WiNo;
	}

	public String getDistancePartitionFrameSingleLh() {
		return this.distancePartitionFrameSingleLh;
	}

	public void setDistancePartitionFrameSingleLh(String distancePartitionFrameSingleLh) {
		this.distancePartitionFrameSingleLh = distancePartitionFrameSingleLh;
	}

	public String getDistancePartitionFrameCabinRh() {
		return this.distancePartitionFrameCabinRh;
	}

	public void setDistancePartitionFrameCabinRh(String distancePartitionFrameCabinRh) {
		this.distancePartitionFrameCabinRh = distancePartitionFrameCabinRh;
	}

	public String getWidthCorridorPartitionFrame() {
		return this.widthCorridorPartitionFrame;
	}

	public void setWidthCorridorPartitionFrame(String widthCorridorPartitionFrame) {
		this.widthCorridorPartitionFrame = widthCorridorPartitionFrame;
	}

	public String getDistanceDoorcutoutSlidingdoor() {
		return this.distanceDoorcutoutSlidingdoor;
	}

	public void setDistanceDoorcutoutSlidingdoor(String distanceDoorcutoutSlidingdoor) {
		this.distanceDoorcutoutSlidingdoor = distanceDoorcutoutSlidingdoor;
	}

	public String getDistanceMiddleDoorPullboxbkt() {
		return this.distanceMiddleDoorPullboxbkt;
	}

	public void setDistanceMiddleDoorPullboxbkt(String distanceMiddleDoorPullboxbkt) {
		this.distanceMiddleDoorPullboxbkt = distanceMiddleDoorPullboxbkt;
	}

	public String getDistancePullboxbktCenterlinePp() {
		return this.distancePullboxbktCenterlinePp;
	}

	public void setDistancePullboxbktCenterlinePp(String distancePullboxbktCenterlinePp) {
		this.distancePullboxbktCenterlinePp = distancePullboxbktCenterlinePp;
	}

	public String getDistancePullboxbktCenterlineNpp() {
		return this.distancePullboxbktCenterlineNpp;
	}

	public void setDistancePullboxbktCenterlineNpp(String distancePullboxbktCenterlineNpp) {
		this.distancePullboxbktCenterlineNpp = distancePullboxbktCenterlineNpp;
	}

	public String getFitmentWatertankbracketBothside() {
		return this.fitmentWatertankbracketBothside;
	}

	public void setFitmentWatertankbracketBothside(String fitmentWatertankbracketBothside) {
		this.fitmentWatertankbracketBothside = fitmentWatertankbracketBothside;
	}

	public String getHeightChannelcomplete() {
		return this.heightChannelcomplete;
	}

	public void setHeightChannelcomplete(String heightChannelcomplete) {
		this.heightChannelcomplete = heightChannelcomplete;
	}

	public String getDistanceSidewallPartitionpillar() {
		return this.distanceSidewallPartitionpillar;
	}

	public void setDistanceSidewallPartitionpillar(String distanceSidewallPartitionpillar) {
		this.distanceSidewallPartitionpillar = distanceSidewallPartitionpillar;
	}

	public String getHeightBackpieceLuggageracke() {
		return this.heightBackpieceLuggageracke;
	}

	public void setHeightBackpieceLuggageracke(String heightBackpieceLuggageracke) {
		this.heightBackpieceLuggageracke = heightBackpieceLuggageracke;
	}

	public String getDistanceDestinationBoard() {
		return this.distanceDestinationBoard;
	}

	public void setDistanceDestinationBoard(String distanceDestinationBoard) {
		this.distanceDestinationBoard = distanceDestinationBoard;
	}

	public String getDiatanceSidewallpillarPrtmember() {
		return this.diatanceSidewallpillarPrtmember;
	}

	public void setDiatanceSidewallpillarPrtmember(String diatanceSidewallpillarPrtmember) {
		this.diatanceSidewallpillarPrtmember = diatanceSidewallpillarPrtmember;
	}

	public String getHeightRoofflangeFramepart() {
		return this.heightRoofflangeFramepart;
	}

	public void setHeightRoofflangeFramepart(String heightRoofflangeFramepart) {
		this.heightRoofflangeFramepart = heightRoofflangeFramepart;
	}

	public String getDuctInternallogitudinalLateral() {
		return this.ductInternallogitudinalLateral;
	}

	public void setDuctInternallogitudinalLateral(String ductInternallogitudinalLateral) {
		this.ductInternallogitudinalLateral = ductInternallogitudinalLateral;
	}

	public String getDistanceDoorwayCrewcompGenroom() {
		return this.distanceDoorwayCrewcompGenroom;
	}

	public void setDistanceDoorwayCrewcompGenroom(String distanceDoorwayCrewcompGenroom) {
		this.distanceDoorwayCrewcompGenroom = distanceDoorwayCrewcompGenroom;
	}

	public String getDistanceAuxWatertankbktCentre() {
		return this.distanceAuxWatertankbktCentre;
	}

	public void setDistanceAuxWatertankbktCentre(String distanceAuxWatertankbktCentre) {
		this.distanceAuxWatertankbktCentre = distanceAuxWatertankbktCentre;
	}

	public String getDisableLavDoor() {
		return this.disableLavDoor;
	}

	public void setDisableLavDoor(String disableLavDoor) {
		this.disableLavDoor = disableLavDoor;
	}

	public String getDisableLavDoorWidth() {
		return this.disableLavDoorWidth;
	}

	public void setDisableLavDoorWidth(String disableLavDoorWidth) {
		this.disableLavDoorWidth = disableLavDoorWidth;
	}

	public String getHeightBottomroofCrossbracesbottom() {
		return this.heightBottomroofCrossbracesbottom;
	}

	public void setHeightBottomroofCrossbracesbottom(String heightBottomroofCrossbracesbottom) {
		this.heightBottomroofCrossbracesbottom = heightBottomroofCrossbracesbottom;
	}

	public String getPassengerLavArea() {
		return this.passengerLavArea;
	}

	public void setPassengerLavArea(String passengerLavArea) {
		this.passengerLavArea = passengerLavArea;
	}

	public String getDistanceLavPrtframeEnd() {
		return this.distanceLavPrtframeEnd;
	}

	public void setDistanceLavPrtframeEnd(String distanceLavPrtframeEnd) {
		this.distanceLavPrtframeEnd = distanceLavPrtframeEnd;
	}

	public String getDistanceLavPrtframeLavPrtframe() {
		return this.distanceLavPrtframeLavPrtframe;
	}

	public void setDistanceLavPrtframeLavPrtframe(String distanceLavPrtframeLavPrtframe) {
		this.distanceLavPrtframeLavPrtframe = distanceLavPrtframeLavPrtframe;
	}

	public Integer getBerthbktLowerLh() {
		return this.berthbktLowerLh;
	}

	public void setBerthbktLowerLh(Integer berthbktLowerLh) {
		this.berthbktLowerLh = berthbktLowerLh;
	}

	public Integer getBerthbktMiddleLh() {
		return this.berthbktMiddleLh;
	}

	public void setBerthbktMiddleLh(Integer berthbktMiddleLh) {
		this.berthbktMiddleLh = berthbktMiddleLh;
	}

	public Integer getBerthbktUpperLh() {
		return this.berthbktUpperLh;
	}

	public void setBerthbktUpperLh(Integer berthbktUpperLh) {
		this.berthbktUpperLh = berthbktUpperLh;
	}

	public Integer getBerthbktLowerRh() {
		return this.berthbktLowerRh;
	}

	public void setBerthbktLowerRh(Integer berthbktLowerRh) {
		this.berthbktLowerRh = berthbktLowerRh;
	}

	public Integer getBerthbktUpperRh() {
		return this.berthbktUpperRh;
	}

	public void setBerthbktUpperRh(Integer berthbktUpperRh) {
		this.berthbktUpperRh = berthbktUpperRh;
	}

	public String getDogBoxArea() {
		return this.dogBoxArea;
	}

	public void setDogBoxArea(String dogBoxArea) {
		this.dogBoxArea = dogBoxArea;
	}

	public String getControlRoomArea() {
		return this.controlRoomArea;
	}

	public void setControlRoomArea(String controlRoomArea) {
		this.controlRoomArea = controlRoomArea;
	}

	public String getStretcherRoomArea() {
		return this.stretcherRoomArea;
	}

	public void setStretcherRoomArea(String stretcherRoomArea) {
		this.stretcherRoomArea = stretcherRoomArea;
	}

	public String getDistanceSlidingDoorStopper() {
		return this.distanceSlidingDoorStopper;
	}

	public void setDistanceSlidingDoorStopper(String distanceSlidingDoorStopper) {
		this.distanceSlidingDoorStopper = distanceSlidingDoorStopper;
	}

	public String getDistanceLavMountingbkt() {
		return this.distanceLavMountingbkt;
	}

	public void setDistanceLavMountingbkt(String distanceLavMountingbkt) {
		this.distanceLavMountingbkt = distanceLavMountingbkt;
	}

	public String getDistanceAuxWatertankbkt() {
		return this.distanceAuxWatertankbkt;
	}

	public void setDistanceAuxWatertankbkt(String distanceAuxWatertankbkt) {
		this.distanceAuxWatertankbkt = distanceAuxWatertankbkt;
	}

	public String getHeightBktcompleteRoofflange() {
		return this.heightBktcompleteRoofflange;
	}

	public void setHeightBktcompleteRoofflange(String heightBktcompleteRoofflange) {
		this.heightBktcompleteRoofflange = heightBktcompleteRoofflange;
	}

	public String getDistancePowerpanelmountingCenterline() {
		return this.distancePowerpanelmountingCenterline;
	}

	public void setDistancePowerpanelmountingCenterline(String distancePowerpanelmountingCenterline) {
		this.distancePowerpanelmountingCenterline = distancePowerpanelmountingCenterline;
	}

	public String getDistanceCoachcenterlineAuxiliarybkt() {
		return this.distanceCoachcenterlineAuxiliarybkt;
	}

	public void setDistanceCoachcenterlineAuxiliarybkt(String distanceCoachcenterlineAuxiliarybkt) {
		this.distanceCoachcenterlineAuxiliarybkt = distanceCoachcenterlineAuxiliarybkt;
	}

	public String getHeightLowerberthUpperberth() {
		return this.heightLowerberthUpperberth;
	}

	public void setHeightLowerberthUpperberth(String heightLowerberthUpperberth) {
		this.heightLowerberthUpperberth = heightLowerberthUpperberth;
	}

	public String getDistancePullboxPullbox() {
		return this.distancePullboxPullbox;
	}

	public void setDistancePullboxPullbox(String distancePullboxPullbox) {
		this.distancePullboxPullbox = distancePullboxPullbox;
	}

	public String getDistanceLuggagerackRoofflangetop() {
		return this.distanceLuggagerackRoofflangetop;
	}

	public void setDistanceLuggagerackRoofflangetop(String distanceLuggagerackRoofflangetop) {
		this.distanceLuggagerackRoofflangetop = distanceLuggagerackRoofflangetop;
	}

	public String getDistanceDoorAttachmentbkt() {
		return this.distanceDoorAttachmentbkt;
	}

	public void setDistanceDoorAttachmentbkt(String distanceDoorAttachmentbkt) {
		this.distanceDoorAttachmentbkt = distanceDoorAttachmentbkt;
	}

	public String getDistancePullboxCarlinearch() {
		return this.distancePullboxCarlinearch;
	}

	public void setDistancePullboxCarlinearch(String distancePullboxCarlinearch) {
		this.distancePullboxCarlinearch = distancePullboxCarlinearch;
	}

	public String getHeightCrossbraceRoofflange() {
		return this.heightCrossbraceRoofflange;
	}

	public void setHeightCrossbraceRoofflange(String heightCrossbraceRoofflange) {
		this.heightCrossbraceRoofflange = heightCrossbraceRoofflange;
	}

	public String getMountingangleLowerluggagerackBottomsidewall() {
		return this.mountingangleLowerluggagerackBottomsidewall;
	}

	public void setMountingangleLowerluggagerackBottomsidewall(String mountingangleLowerluggagerackBottomsidewall) {
		this.mountingangleLowerluggagerackBottomsidewall = mountingangleLowerluggagerackBottomsidewall;
	}

	public String getFitmentCrossBraces() {
		return this.fitmentCrossBraces;
	}

	public void setFitmentCrossBraces(String fitmentCrossBraces) {
		this.fitmentCrossBraces = fitmentCrossBraces;
	}

	public String getFitmentStiffeningPlate() {
		return this.fitmentStiffeningPlate;
	}

	public void setFitmentStiffeningPlate(String fitmentStiffeningPlate) {
		this.fitmentStiffeningPlate = fitmentStiffeningPlate;
	}

	public String getFitmentPowerPanelFrame() {
		return this.fitmentPowerPanelFrame;
	}

	public void setFitmentPowerPanelFrame(String fitmentPowerPanelFrame) {
		this.fitmentPowerPanelFrame = fitmentPowerPanelFrame;
	}

	public String getFitmentWeldingPartitionFrame() {
		return this.fitmentWeldingPartitionFrame;
	}

	public void setFitmentWeldingPartitionFrame(String fitmentWeldingPartitionFrame) {
		this.fitmentWeldingPartitionFrame = fitmentWeldingPartitionFrame;
	}

	public String getRoofbktWireclamping() {
		return this.roofbktWireclamping;
	}

	public void setRoofbktWireclamping(String roofbktWireclamping) {
		this.roofbktWireclamping = roofbktWireclamping;
	}

	public String getDetailsModification() {
		return this.detailsModification;
	}

	public void setDetailsModification(String detailsModification) {
		this.detailsModification = detailsModification;
	}

	public String getDetailsTrialItem() {
		return this.detailsTrialItem;
	}

	public void setDetailsTrialItem(String detailsTrialItem) {
		this.detailsTrialItem = detailsTrialItem;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getStage4TestingStatus() {
		return this.stage4TestingStatus;
	}

	public void setStage4TestingStatus(String stage4TestingStatus) {
		this.stage4TestingStatus = stage4TestingStatus;
	}

	public String getShellAssembly4ObervationRmk() {
		return shellAssembly4ObervationRmk;
	}

	public void setShellAssembly4ObervationRmk(String shellAssembly4ObervationRmk) {
		this.shellAssembly4ObervationRmk = shellAssembly4ObervationRmk;
	}

	public String getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(String entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

}
