package beans;
// Generated 15 Jan, 2020 6:48:41 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * ShellStage1SipTran generated by hbm2java
 */
public class ShellStage1SipTran implements java.io.Serializable {

	private int shellAssetId;
	private String stage1SipDocNo;
	private String stage1SipShift;
	private Date stage1SipDate;
	private String stage1WorkBy;
	private String stage1DrawingNo;
	private String stage1WiNo;
	private String itemAsPerDrawingFlag;
	private String complianceWiFlag;
	private String weldingThroatLengthFlag;
	private Integer noOfLevelTrestle;
	private String levelingCenteringUnderframeFlag;
	private String grindingCleaningSolebarFlag;
	private String weildablePrimerSolebarFlag;
	private Integer lengthOverBodyLh;
	private Integer lengthOverBodyRh;
	private Integer shellWidthPp;
	private Integer shellWidthNpp;
	private Integer shellWidthCenter;
	private Integer lateralWidthAcTroughPp;
	private Integer lateralWidthAcTroughNpp;
	private Integer longitudinalWidthAcTroughPp;
	private Integer longitudinalWidthAcTroughNpp;
	private Integer diagonalWidthEntranceDoor1;
	private Integer diagonalWidthEntranceDoor2;
	private Integer diagonalWidthEntranceDoor3;
	private Integer diagonalWidthEntranceDoor4;
	private Integer diagonalWidthEntranceDoor5;
	private Integer diagonalWidthEntranceDoor6;
	private Integer heightEntranceDoor1;
	private Integer heightEntranceDoor2;
	private Integer heightEntranceDoor3;
	private Integer heightEntranceDoor4;
	private Integer heightEntranceDoor5;
	private Integer heightEntranceDoor6;
	private Integer widthEntranceDoor1;
	private Integer widthEntranceDoor2;
	private Integer widthEntranceDoor3;
	private Integer widthEntranceDoor4;
	private Integer widthEntranceDoor5;
	private Integer widthEntranceDoor6;
	
	private Integer heightTopTroughfloorToRoofsheetBottomPp;
	private Integer heightTopTroughfloorToRoofsheetBottomNpp;
	private Integer heightTopPillarsupportToBottomCrossbraceSingleside1;
	private Integer heightTopPillarsupportToBottomCrossbraceSingleside2;
	private Integer heightTopPillarsupportToBottomCrossbraceSingleside3;
	private Integer heightTopPillarsupportToBottomCrossbraceSingleside4;
	private Integer heightTopPillarsupportToBottomCrossbraceSingleside5;
	private Integer heightTopPillarsupportToBottomCrossbraceSingleside6;
	private Integer heightTopPillarsupportToBottomCrossbraceCabinside1;
	private Integer heightTopPillarsupportToBottomCrossbraceCabinside2;
	private Integer heightTopPillarsupportToBottomCrossbraceCabinside3;
	private Integer heightTopPillarsupportToBottomCrossbraceCabinside4;
	private Integer heightTopPillarsupportToBottomCrossbraceCabinside5;
	private Integer heightTopPillarsupportToBottomCrossbraceCabinside6;
	private Integer heightCrossbracePartitionpillerSingelside1;
	private Integer heightCrossbracePartitionpillerSingelside2;
	private Integer heightCrossbracePartitionpillerSingelside3;
	private Integer heightCrossbracePartitionpillerSingelside4;
	private Integer heightCrossbracePartitionpillerSingelside5;
	private Integer heightCrossbracePartitionpillerSingelside6;
	private Integer heightCrossbracePartitionpillerCabinside1;
	private Integer heightCrossbracePartitionpillerCabinside2;
	private Integer heightCrossbracePartitionpillerCabinside3;
	private Integer heightCrossbracePartitionpillerCabinside4;
	private Integer heightCrossbracePartitionpillerCabinside5;
	private Integer heightCrossbracePartitionpillerCabinside6;
	private Integer heightVestibuleplateEndwallPp;
	private Integer heightVestibuleplateEndwallNpp;
	private Integer heightWtccPp;
	private Integer heightWtccNpp;
	private Integer widthWtccPp;
	private Integer widthWtccNpp;
	private Integer heightTopThroughfloorBottomRoofArchPp;
	private Integer heightTopThroughfloorBottomRoofArchNpp;
	private Integer heightFloorpillerbracketToRoofSingle1;
	private Integer heightFloorpillerbracketToRoofSingle2;
	private Integer heightFloorpillerbracketToRoofSingle3;
	private Integer heightFloorpillerbracketToRoofSingle4;
	private Integer heightFloorpillerbracketToRoofSingle5;
	private Integer heightFloorpillerbracketToRoofSingle6;
	private Integer heightFloorpillerbracketToRoofSingle7;
	private Integer heightFloorpillerbracketToRoofSingle8;
	private Integer heightFloorpillerbracketToRoofSingle9;
	private Integer heightFloorpillerbracketToRoofSingle10;
	private Integer heightFloorpillerbracketToRoofSingle11;
	private Integer heightFloorpillerbracketToRoofCabin1;
	private Integer heightFloorpillerbracketToRoofCabin2;
	private Integer heightFloorpillerbracketToRoofCabin3;
	private Integer heightFloorpillerbracketToRoofCabin4;
	private Integer heightFloorpillerbracketToRoofCabin5;
	private Integer heightFloorpillerbracketToRoofCabin6;
	private Integer heightFloorpillerbracketToRoofCabin7;
	private Integer heightFloorpillerbracketToRoofCabin8;
	private Integer heightFloorpillerbracketToRoofCabin9;
	private Integer heightFloorpillerbracketToRoofCabin10;
	private Integer heightFloorpillerbracketToRoofCabin11;
	private Integer slidingDoorHeightLh;
	private Integer slidingDoorHeightRh;
	private Integer slidingDoorWidthLh;
	private Integer slidingDoorWidthRh;
	private Integer distanceRoofEndwallPp;
	private Integer distanceRoofEndwallNpp;
	private Integer roofElementShellSocketHoleDiePp;
	private Integer roofElementShellSocketHoleDieNpp;
	private String roofElementStudDiagonalPp;
	private String roofElementStudDiagonalNpp;
	private String checkedDimenRemarks;
	private String alignmentSidewallRoofarchFlag;
	private String weldingSidewallLavsidewallFlag;
	private String weldingRoofarchSidewallCarlineFlag;
	private String weldingCompletedoorframeFlag;
	private String weldingCompleteendwallFinalroofelementFlag;
	private String weldingRoofSidewallCarlineFlag;
	private String grindHorizontalVerticalJointFlag;
	private String alignmentBothSidewallUnderframeFlag;
	private String detailsOfModification;
	private String detailsOfTrial;
	private String remarks;
	private String stage1TestingStatus;
	private String entryBy;
	private Date entryTime;

	public ShellStage1SipTran() {
	}

	public ShellStage1SipTran(int shellAssetId) {
		this.shellAssetId = shellAssetId;
	}

	public ShellStage1SipTran(int shellAssetId, String stage1SipDocNo, String stage1SipShift, Date stage1SipDate,
			String stage1WorkBy, String stage1DrawingNo, String stage1WiNo, String itemAsPerDrawingFlag,
			String complianceWiFlag, String weldingThroatLengthFlag, Integer noOfLevelTrestle,
			String levelingCenteringUnderframeFlag, String grindingCleaningSolebarFlag,
			String weildablePrimerSolebarFlag, Integer lengthOverBodyLh, Integer lengthOverBodyRh, Integer shellWidthPp,
			Integer shellWidthNpp, Integer shellWidthCenter, Integer lateralWidthAcTroughPp,
			Integer lateralWidthAcTroughNpp, Integer longitudinalWidthAcTroughPp, Integer longitudinalWidthAcTroughNpp,
			Integer diagonalWidthEntranceDoor1, Integer diagonalWidthEntranceDoor2, Integer diagonalWidthEntranceDoor3,
			Integer diagonalWidthEntranceDoor4, Integer diagonalWidthEntranceDoor5, Integer diagonalWidthEntranceDoor6,
			Integer heightEntranceDoor1, Integer heightEntranceDoor2, Integer heightEntranceDoor3,
			Integer heightEntranceDoor4, Integer heightEntranceDoor5, Integer heightEntranceDoor6,
			Integer widthEntranceDoor1, Integer widthEntranceDoor2, Integer widthEntranceDoor3,
			Integer widthEntranceDoor4, Integer widthEntranceDoor5, Integer widthEntranceDoor6,
			Integer heightTopTroughfloorToRoofsheetBottomPp, Integer heightTopTroughfloorToRoofsheetBottomNpp,
			Integer heightTopPillarsupportToBottomCrossbraceSingleside1,
			Integer heightTopPillarsupportToBottomCrossbraceSingleside2,
			Integer heightTopPillarsupportToBottomCrossbraceSingleside3,
			Integer heightTopPillarsupportToBottomCrossbraceSingleside4,
			Integer heightTopPillarsupportToBottomCrossbraceSingleside5,
			Integer heightTopPillarsupportToBottomCrossbraceSingleside6,
			Integer heightTopPillarsupportToBottomCrossbraceCabinside1,
			Integer heightTopPillarsupportToBottomCrossbraceCabinside2,
			Integer heightTopPillarsupportToBottomCrossbraceCabinside3,
			Integer heightTopPillarsupportToBottomCrossbraceCabinside4,
			Integer heightTopPillarsupportToBottomCrossbraceCabinside5,
			Integer heightTopPillarsupportToBottomCrossbraceCabinside6,
			Integer heightCrossbracePartitionpillerSingelside1, Integer heightCrossbracePartitionpillerSingelside2,
			Integer heightCrossbracePartitionpillerSingelside3, Integer heightCrossbracePartitionpillerSingelside4,
			Integer heightCrossbracePartitionpillerSingelside5, Integer heightCrossbracePartitionpillerSingelside6,
			Integer heightCrossbracePartitionpillerCabinside1, Integer heightCrossbracePartitionpillerCabinside2,
			Integer heightCrossbracePartitionpillerCabinside3, Integer heightCrossbracePartitionpillerCabinside4,
			Integer heightCrossbracePartitionpillerCabinside5, Integer heightCrossbracePartitionpillerCabinside6,
			Integer heightVestibuleplateEndwallPp, Integer heightVestibuleplateEndwallNpp, 
			Integer heightWtccPp, Integer heightWtccNpp, Integer widthWtccPp, Integer widthWtccNpp,
			Integer heightTopThroughfloorBottomRoofArchPp, Integer heightTopThroughfloorBottomRoofArchNpp,
			Integer heightFloorpillerbracketToRoofSingle1, Integer heightFloorpillerbracketToRoofSingle2,
			Integer heightFloorpillerbracketToRoofSingle3, Integer heightFloorpillerbracketToRoofSingle4,
			Integer heightFloorpillerbracketToRoofSingle5, Integer heightFloorpillerbracketToRoofSingle6,
			Integer heightFloorpillerbracketToRoofSingle7, Integer heightFloorpillerbracketToRoofSingle8,
			Integer heightFloorpillerbracketToRoofSingle9, Integer heightFloorpillerbracketToRoofSingle10,
			Integer heightFloorpillerbracketToRoofSingle11, Integer heightFloorpillerbracketToRoofCabin1,
			Integer heightFloorpillerbracketToRoofCabin2, Integer heightFloorpillerbracketToRoofCabin3,
			Integer heightFloorpillerbracketToRoofCabin4, Integer heightFloorpillerbracketToRoofCabin5,
			Integer heightFloorpillerbracketToRoofCabin6, Integer heightFloorpillerbracketToRoofCabin7,
			Integer heightFloorpillerbracketToRoofCabin8, Integer heightFloorpillerbracketToRoofCabin9,
			Integer heightFloorpillerbracketToRoofCabin10, Integer heightFloorpillerbracketToRoofCabin11,
			Integer slidingDoorHeightLh, Integer slidingDoorHeightRh, Integer slidingDoorWidthLh,
			Integer slidingDoorWidthRh, Integer distanceRoofEndwallPp, Integer distanceRoofEndwallNpp,
			Integer roofElementShellSocketHoleDiePp, Integer roofElementShellSocketHoleDieNpp,
			String roofElementStudDiagonalPp, String roofElementStudDiagonalNpp,String checkedDimenRemarks, String alignmentSidewallRoofarchFlag,
			String weldingSidewallLavsidewallFlag,String weldingRoofarchSidewallCarlineFlag, String weldingCompletedoorframeFlag,
			String weldingCompleteendwallFinalroofelementFlag,String weldingRoofSidewallCarlineFlag, String grindHorizontalVerticalJointFlag,
			String alignmentBothSidewallUnderframeFlag, String detailsOfModification, String detailsOfTrial,
			String remarks, String stage1TestingStatus, String entryBy, Date entryTime) {
		this.shellAssetId = shellAssetId;
		this.stage1SipDocNo = stage1SipDocNo;
		this.stage1SipShift = stage1SipShift;
		this.stage1SipDate = stage1SipDate;
		this.stage1WorkBy = stage1WorkBy;
		this.stage1DrawingNo = stage1DrawingNo;
		this.stage1WiNo = stage1WiNo;
		this.itemAsPerDrawingFlag = itemAsPerDrawingFlag;
		this.complianceWiFlag = complianceWiFlag;
		this.weldingThroatLengthFlag = weldingThroatLengthFlag;
		this.noOfLevelTrestle = noOfLevelTrestle;
		this.levelingCenteringUnderframeFlag = levelingCenteringUnderframeFlag;
		this.grindingCleaningSolebarFlag = grindingCleaningSolebarFlag;
		this.weildablePrimerSolebarFlag = weildablePrimerSolebarFlag;
		this.lengthOverBodyLh = lengthOverBodyLh;
		this.lengthOverBodyRh = lengthOverBodyRh;
		this.shellWidthPp = shellWidthPp;
		this.shellWidthNpp = shellWidthNpp;
		this.shellWidthCenter = shellWidthCenter;
		this.lateralWidthAcTroughPp = lateralWidthAcTroughPp;
		this.lateralWidthAcTroughNpp = lateralWidthAcTroughNpp;
		this.longitudinalWidthAcTroughPp = longitudinalWidthAcTroughPp;
		this.longitudinalWidthAcTroughNpp = longitudinalWidthAcTroughNpp;
		this.diagonalWidthEntranceDoor1 = diagonalWidthEntranceDoor1;
		this.diagonalWidthEntranceDoor2 = diagonalWidthEntranceDoor2;
		this.diagonalWidthEntranceDoor3 = diagonalWidthEntranceDoor3;
		this.diagonalWidthEntranceDoor4 = diagonalWidthEntranceDoor4;
		this.diagonalWidthEntranceDoor5 = diagonalWidthEntranceDoor5;
		this.diagonalWidthEntranceDoor6 = diagonalWidthEntranceDoor6;
		this.heightEntranceDoor1 = heightEntranceDoor1;
		this.heightEntranceDoor2 = heightEntranceDoor2;
		this.heightEntranceDoor3 = heightEntranceDoor3;
		this.heightEntranceDoor4 = heightEntranceDoor4;
		this.heightEntranceDoor5 = heightEntranceDoor5;
		this.heightEntranceDoor6 = heightEntranceDoor6;
		this.widthEntranceDoor1 = widthEntranceDoor1;
		this.widthEntranceDoor2 = widthEntranceDoor2;
		this.widthEntranceDoor3 = widthEntranceDoor3;
		this.widthEntranceDoor4 = widthEntranceDoor4;
		this.widthEntranceDoor5 = widthEntranceDoor5;
		this.widthEntranceDoor6 = widthEntranceDoor6;
		this.heightTopTroughfloorToRoofsheetBottomPp = heightTopTroughfloorToRoofsheetBottomPp;
		this.heightTopTroughfloorToRoofsheetBottomNpp = heightTopTroughfloorToRoofsheetBottomNpp;
		this.heightTopPillarsupportToBottomCrossbraceSingleside1 = heightTopPillarsupportToBottomCrossbraceSingleside1;
		this.heightTopPillarsupportToBottomCrossbraceSingleside2 = heightTopPillarsupportToBottomCrossbraceSingleside2;
		this.heightTopPillarsupportToBottomCrossbraceSingleside3 = heightTopPillarsupportToBottomCrossbraceSingleside3;
		this.heightTopPillarsupportToBottomCrossbraceSingleside4 = heightTopPillarsupportToBottomCrossbraceSingleside4;
		this.heightTopPillarsupportToBottomCrossbraceSingleside5 = heightTopPillarsupportToBottomCrossbraceSingleside5;
		this.heightTopPillarsupportToBottomCrossbraceSingleside6 = heightTopPillarsupportToBottomCrossbraceSingleside6;
		this.heightTopPillarsupportToBottomCrossbraceCabinside1 = heightTopPillarsupportToBottomCrossbraceCabinside1;
		this.heightTopPillarsupportToBottomCrossbraceCabinside2 = heightTopPillarsupportToBottomCrossbraceCabinside2;
		this.heightTopPillarsupportToBottomCrossbraceCabinside3 = heightTopPillarsupportToBottomCrossbraceCabinside3;
		this.heightTopPillarsupportToBottomCrossbraceCabinside4 = heightTopPillarsupportToBottomCrossbraceCabinside4;
		this.heightTopPillarsupportToBottomCrossbraceCabinside5 = heightTopPillarsupportToBottomCrossbraceCabinside5;
		this.heightTopPillarsupportToBottomCrossbraceCabinside6 = heightTopPillarsupportToBottomCrossbraceCabinside6;
		this.heightCrossbracePartitionpillerSingelside1 = heightCrossbracePartitionpillerSingelside1;
		this.heightCrossbracePartitionpillerSingelside2 = heightCrossbracePartitionpillerSingelside2;
		this.heightCrossbracePartitionpillerSingelside3 = heightCrossbracePartitionpillerSingelside3;
		this.heightCrossbracePartitionpillerSingelside4 = heightCrossbracePartitionpillerSingelside4;
		this.heightCrossbracePartitionpillerSingelside5 = heightCrossbracePartitionpillerSingelside5;
		this.heightCrossbracePartitionpillerSingelside6 = heightCrossbracePartitionpillerSingelside6;
		this.heightCrossbracePartitionpillerCabinside1 = heightCrossbracePartitionpillerCabinside1;
		this.heightCrossbracePartitionpillerCabinside2 = heightCrossbracePartitionpillerCabinside2;
		this.heightCrossbracePartitionpillerCabinside3 = heightCrossbracePartitionpillerCabinside3;
		this.heightCrossbracePartitionpillerCabinside4 = heightCrossbracePartitionpillerCabinside4;
		this.heightCrossbracePartitionpillerCabinside5 = heightCrossbracePartitionpillerCabinside5;
		this.heightCrossbracePartitionpillerCabinside6 = heightCrossbracePartitionpillerCabinside6;
		this.heightVestibuleplateEndwallPp=heightVestibuleplateEndwallPp;
		this.heightVestibuleplateEndwallNpp=heightVestibuleplateEndwallNpp;
		this.heightWtccPp = heightWtccPp;
		this.heightWtccNpp = heightWtccNpp;
		this.widthWtccPp = widthWtccPp;
		this.widthWtccNpp = widthWtccNpp;
		this.heightTopThroughfloorBottomRoofArchPp = heightTopThroughfloorBottomRoofArchPp;
		this.heightTopThroughfloorBottomRoofArchNpp = heightTopThroughfloorBottomRoofArchNpp;
		this.heightFloorpillerbracketToRoofSingle1 = heightFloorpillerbracketToRoofSingle1;
		this.heightFloorpillerbracketToRoofSingle2 = heightFloorpillerbracketToRoofSingle2;
		this.heightFloorpillerbracketToRoofSingle3 = heightFloorpillerbracketToRoofSingle3;
		this.heightFloorpillerbracketToRoofSingle4 = heightFloorpillerbracketToRoofSingle4;
		this.heightFloorpillerbracketToRoofSingle5 = heightFloorpillerbracketToRoofSingle5;
		this.heightFloorpillerbracketToRoofSingle6 = heightFloorpillerbracketToRoofSingle6;
		this.heightFloorpillerbracketToRoofSingle7 = heightFloorpillerbracketToRoofSingle7;
		this.heightFloorpillerbracketToRoofSingle8 = heightFloorpillerbracketToRoofSingle8;
		this.heightFloorpillerbracketToRoofSingle9 = heightFloorpillerbracketToRoofSingle9;
		this.heightFloorpillerbracketToRoofSingle10 = heightFloorpillerbracketToRoofSingle10;
		this.heightFloorpillerbracketToRoofSingle11 = heightFloorpillerbracketToRoofSingle11;
		this.heightFloorpillerbracketToRoofCabin1 = heightFloorpillerbracketToRoofCabin1;
		this.heightFloorpillerbracketToRoofCabin2 = heightFloorpillerbracketToRoofCabin2;
		this.heightFloorpillerbracketToRoofCabin3 = heightFloorpillerbracketToRoofCabin3;
		this.heightFloorpillerbracketToRoofCabin4 = heightFloorpillerbracketToRoofCabin4;
		this.heightFloorpillerbracketToRoofCabin5 = heightFloorpillerbracketToRoofCabin5;
		this.heightFloorpillerbracketToRoofCabin6 = heightFloorpillerbracketToRoofCabin6;
		this.heightFloorpillerbracketToRoofCabin7 = heightFloorpillerbracketToRoofCabin7;
		this.heightFloorpillerbracketToRoofCabin8 = heightFloorpillerbracketToRoofCabin8;
		this.heightFloorpillerbracketToRoofCabin9 = heightFloorpillerbracketToRoofCabin9;
		this.heightFloorpillerbracketToRoofCabin10 = heightFloorpillerbracketToRoofCabin10;
		this.heightFloorpillerbracketToRoofCabin11 = heightFloorpillerbracketToRoofCabin11;
		this.slidingDoorHeightLh = slidingDoorHeightLh;
		this.slidingDoorHeightRh = slidingDoorHeightRh;
		this.slidingDoorWidthLh = slidingDoorWidthLh;
		this.slidingDoorWidthRh = slidingDoorWidthRh;
		this.distanceRoofEndwallPp = distanceRoofEndwallPp;
		this.distanceRoofEndwallNpp = distanceRoofEndwallNpp;
		this.roofElementShellSocketHoleDiePp = roofElementShellSocketHoleDiePp;
		this.roofElementShellSocketHoleDieNpp = roofElementShellSocketHoleDieNpp;
		this.roofElementStudDiagonalPp = roofElementStudDiagonalPp;
		this.roofElementStudDiagonalNpp = roofElementStudDiagonalNpp;
		this.checkedDimenRemarks=checkedDimenRemarks;
		this.alignmentSidewallRoofarchFlag = alignmentSidewallRoofarchFlag;
		this.weldingSidewallLavsidewallFlag = weldingSidewallLavsidewallFlag;
		this.weldingRoofarchSidewallCarlineFlag=weldingRoofarchSidewallCarlineFlag;
		this.weldingCompletedoorframeFlag = weldingCompletedoorframeFlag;
		this.weldingCompleteendwallFinalroofelementFlag = weldingCompleteendwallFinalroofelementFlag;
		this.weldingRoofarchSidewallCarlineFlag=weldingRoofSidewallCarlineFlag;
		this.grindHorizontalVerticalJointFlag = grindHorizontalVerticalJointFlag;
		this.alignmentBothSidewallUnderframeFlag = alignmentBothSidewallUnderframeFlag;
		this.detailsOfModification = detailsOfModification;
		this.detailsOfTrial = detailsOfTrial;
		this.remarks = remarks;
		this.stage1TestingStatus = stage1TestingStatus;
		this.entryBy = entryBy;
		this.entryTime = entryTime;
	}

	public int getShellAssetId() {
		return this.shellAssetId;
	}

	public void setShellAssetId(int shellAssetId) {
		this.shellAssetId = shellAssetId;
	}

	public String getStage1SipDocNo() {
		return this.stage1SipDocNo;
	}

	public void setStage1SipDocNo(String stage1SipDocNo) {
		this.stage1SipDocNo = stage1SipDocNo;
	}

	public String getStage1SipShift() {
		return this.stage1SipShift;
	}

	public void setStage1SipShift(String stage1SipShift) {
		this.stage1SipShift = stage1SipShift;
	}

	public Date getStage1SipDate() {
		return this.stage1SipDate;
	}

	public void setStage1SipDate(Date stage1SipDate) {
		this.stage1SipDate = stage1SipDate;
	}

	public String getStage1WorkBy() {
		return this.stage1WorkBy;
	}

	public void setStage1WorkBy(String stage1WorkBy) {
		this.stage1WorkBy = stage1WorkBy;
	}

	public String getStage1DrawingNo() {
		return this.stage1DrawingNo;
	}

	public void setStage1DrawingNo(String stage1DrawingNo) {
		this.stage1DrawingNo = stage1DrawingNo;
	}

	public String getStage1WiNo() {
		return this.stage1WiNo;
	}

	public void setStage1WiNo(String stage1WiNo) {
		this.stage1WiNo = stage1WiNo;
	}

	public String getItemAsPerDrawingFlag() {
		return this.itemAsPerDrawingFlag;
	}

	public void setItemAsPerDrawingFlag(String itemAsPerDrawingFlag) {
		this.itemAsPerDrawingFlag = itemAsPerDrawingFlag;
	}

	public String getComplianceWiFlag() {
		return this.complianceWiFlag;
	}

	public void setComplianceWiFlag(String complianceWiFlag) {
		this.complianceWiFlag = complianceWiFlag;
	}

	public String getWeldingThroatLengthFlag() {
		return this.weldingThroatLengthFlag;
	}

	public void setWeldingThroatLengthFlag(String weldingThroatLengthFlag) {
		this.weldingThroatLengthFlag = weldingThroatLengthFlag;
	}

	public Integer getNoOfLevelTrestle() {
		return this.noOfLevelTrestle;
	}

	public void setNoOfLevelTrestle(Integer noOfLevelTrestle) {
		this.noOfLevelTrestle = noOfLevelTrestle;
	}

	public String getLevelingCenteringUnderframeFlag() {
		return this.levelingCenteringUnderframeFlag;
	}

	public void setLevelingCenteringUnderframeFlag(String levelingCenteringUnderframeFlag) {
		this.levelingCenteringUnderframeFlag = levelingCenteringUnderframeFlag;
	}

	public String getGrindingCleaningSolebarFlag() {
		return this.grindingCleaningSolebarFlag;
	}

	public void setGrindingCleaningSolebarFlag(String grindingCleaningSolebarFlag) {
		this.grindingCleaningSolebarFlag = grindingCleaningSolebarFlag;
	}

	public String getWeildablePrimerSolebarFlag() {
		return this.weildablePrimerSolebarFlag;
	}

	public void setWeildablePrimerSolebarFlag(String weildablePrimerSolebarFlag) {
		this.weildablePrimerSolebarFlag = weildablePrimerSolebarFlag;
	}

	public Integer getLengthOverBodyLh() {
		return this.lengthOverBodyLh;
	}

	public void setLengthOverBodyLh(Integer lengthOverBodyLh) {
		this.lengthOverBodyLh = lengthOverBodyLh;
	}

	public Integer getLengthOverBodyRh() {
		return this.lengthOverBodyRh;
	}

	public void setLengthOverBodyRh(Integer lengthOverBodyRh) {
		this.lengthOverBodyRh = lengthOverBodyRh;
	}

	public Integer getShellWidthPp() {
		return this.shellWidthPp;
	}

	public void setShellWidthPp(Integer shellWidthPp) {
		this.shellWidthPp = shellWidthPp;
	}

	public Integer getShellWidthNpp() {
		return this.shellWidthNpp;
	}

	public void setShellWidthNpp(Integer shellWidthNpp) {
		this.shellWidthNpp = shellWidthNpp;
	}

	public Integer getShellWidthCenter() {
		return this.shellWidthCenter;
	}

	public void setShellWidthCenter(Integer shellWidthCenter) {
		this.shellWidthCenter = shellWidthCenter;
	}

	public Integer getLateralWidthAcTroughPp() {
		return this.lateralWidthAcTroughPp;
	}

	public void setLateralWidthAcTroughPp(Integer lateralWidthAcTroughPp) {
		this.lateralWidthAcTroughPp = lateralWidthAcTroughPp;
	}

	public Integer getLateralWidthAcTroughNpp() {
		return this.lateralWidthAcTroughNpp;
	}

	public void setLateralWidthAcTroughNpp(Integer lateralWidthAcTroughNpp) {
		this.lateralWidthAcTroughNpp = lateralWidthAcTroughNpp;
	}

	public Integer getLongitudinalWidthAcTroughPp() {
		return this.longitudinalWidthAcTroughPp;
	}

	public void setLongitudinalWidthAcTroughPp(Integer longitudinalWidthAcTroughPp) {
		this.longitudinalWidthAcTroughPp = longitudinalWidthAcTroughPp;
	}

	public Integer getLongitudinalWidthAcTroughNpp() {
		return this.longitudinalWidthAcTroughNpp;
	}

	public void setLongitudinalWidthAcTroughNpp(Integer longitudinalWidthAcTroughNpp) {
		this.longitudinalWidthAcTroughNpp = longitudinalWidthAcTroughNpp;
	}

	public Integer getDiagonalWidthEntranceDoor1() {
		return this.diagonalWidthEntranceDoor1;
	}

	public void setDiagonalWidthEntranceDoor1(Integer diagonalWidthEntranceDoor1) {
		this.diagonalWidthEntranceDoor1 = diagonalWidthEntranceDoor1;
	}

	public Integer getDiagonalWidthEntranceDoor2() {
		return this.diagonalWidthEntranceDoor2;
	}

	public void setDiagonalWidthEntranceDoor2(Integer diagonalWidthEntranceDoor2) {
		this.diagonalWidthEntranceDoor2 = diagonalWidthEntranceDoor2;
	}

	public Integer getDiagonalWidthEntranceDoor3() {
		return this.diagonalWidthEntranceDoor3;
	}

	public void setDiagonalWidthEntranceDoor3(Integer diagonalWidthEntranceDoor3) {
		this.diagonalWidthEntranceDoor3 = diagonalWidthEntranceDoor3;
	}

	public Integer getDiagonalWidthEntranceDoor4() {
		return this.diagonalWidthEntranceDoor4;
	}

	public void setDiagonalWidthEntranceDoor4(Integer diagonalWidthEntranceDoor4) {
		this.diagonalWidthEntranceDoor4 = diagonalWidthEntranceDoor4;
	}

	public Integer getDiagonalWidthEntranceDoor5() {
		return this.diagonalWidthEntranceDoor5;
	}

	public void setDiagonalWidthEntranceDoor5(Integer diagonalWidthEntranceDoor5) {
		this.diagonalWidthEntranceDoor5 = diagonalWidthEntranceDoor5;
	}

	public Integer getDiagonalWidthEntranceDoor6() {
		return this.diagonalWidthEntranceDoor6;
	}

	public void setDiagonalWidthEntranceDoor6(Integer diagonalWidthEntranceDoor6) {
		this.diagonalWidthEntranceDoor6 = diagonalWidthEntranceDoor6;
	}

	public Integer getHeightEntranceDoor1() {
		return this.heightEntranceDoor1;
	}

	public void setHeightEntranceDoor1(Integer heightEntranceDoor1) {
		this.heightEntranceDoor1 = heightEntranceDoor1;
	}

	public Integer getHeightEntranceDoor2() {
		return this.heightEntranceDoor2;
	}

	public void setHeightEntranceDoor2(Integer heightEntranceDoor2) {
		this.heightEntranceDoor2 = heightEntranceDoor2;
	}

	public Integer getHeightEntranceDoor3() {
		return this.heightEntranceDoor3;
	}

	public void setHeightEntranceDoor3(Integer heightEntranceDoor3) {
		this.heightEntranceDoor3 = heightEntranceDoor3;
	}

	public Integer getHeightEntranceDoor4() {
		return this.heightEntranceDoor4;
	}

	public void setHeightEntranceDoor4(Integer heightEntranceDoor4) {
		this.heightEntranceDoor4 = heightEntranceDoor4;
	}

	public Integer getHeightEntranceDoor5() {
		return this.heightEntranceDoor5;
	}

	public void setHeightEntranceDoor5(Integer heightEntranceDoor5) {
		this.heightEntranceDoor5 = heightEntranceDoor5;
	}

	public Integer getHeightEntranceDoor6() {
		return this.heightEntranceDoor6;
	}

	public void setHeightEntranceDoor6(Integer heightEntranceDoor6) {
		this.heightEntranceDoor6 = heightEntranceDoor6;
	}

	public Integer getWidthEntranceDoor1() {
		return this.widthEntranceDoor1;
	}

	public void setWidthEntranceDoor1(Integer widthEntranceDoor1) {
		this.widthEntranceDoor1 = widthEntranceDoor1;
	}

	public Integer getWidthEntranceDoor2() {
		return this.widthEntranceDoor2;
	}

	public void setWidthEntranceDoor2(Integer widthEntranceDoor2) {
		this.widthEntranceDoor2 = widthEntranceDoor2;
	}

	public Integer getWidthEntranceDoor3() {
		return this.widthEntranceDoor3;
	}

	public void setWidthEntranceDoor3(Integer widthEntranceDoor3) {
		this.widthEntranceDoor3 = widthEntranceDoor3;
	}

	public Integer getWidthEntranceDoor4() {
		return this.widthEntranceDoor4;
	}

	public void setWidthEntranceDoor4(Integer widthEntranceDoor4) {
		this.widthEntranceDoor4 = widthEntranceDoor4;
	}

	public Integer getWidthEntranceDoor5() {
		return this.widthEntranceDoor5;
	}

	public void setWidthEntranceDoor5(Integer widthEntranceDoor5) {
		this.widthEntranceDoor5 = widthEntranceDoor5;
	}

	public Integer getWidthEntranceDoor6() {
		return this.widthEntranceDoor6;
	}

	public void setWidthEntranceDoor6(Integer widthEntranceDoor6) {
		this.widthEntranceDoor6 = widthEntranceDoor6;
	}

	public Integer getHeightTopTroughfloorToRoofsheetBottomPp() {
		return this.heightTopTroughfloorToRoofsheetBottomPp;
	}

	public void setHeightTopTroughfloorToRoofsheetBottomPp(Integer heightTopTroughfloorToRoofsheetBottomPp) {
		this.heightTopTroughfloorToRoofsheetBottomPp = heightTopTroughfloorToRoofsheetBottomPp;
	}

	public Integer getHeightTopTroughfloorToRoofsheetBottomNpp() {
		return this.heightTopTroughfloorToRoofsheetBottomNpp;
	}

	public void setHeightTopTroughfloorToRoofsheetBottomNpp(Integer heightTopTroughfloorToRoofsheetBottomNpp) {
		this.heightTopTroughfloorToRoofsheetBottomNpp = heightTopTroughfloorToRoofsheetBottomNpp;
	}

	public Integer getHeightTopPillarsupportToBottomCrossbraceSingleside1() {
		return this.heightTopPillarsupportToBottomCrossbraceSingleside1;
	}

	public void setHeightTopPillarsupportToBottomCrossbraceSingleside1(
			Integer heightTopPillarsupportToBottomCrossbraceSingleside1) {
		this.heightTopPillarsupportToBottomCrossbraceSingleside1 = heightTopPillarsupportToBottomCrossbraceSingleside1;
	}

	public Integer getHeightTopPillarsupportToBottomCrossbraceSingleside2() {
		return this.heightTopPillarsupportToBottomCrossbraceSingleside2;
	}

	public void setHeightTopPillarsupportToBottomCrossbraceSingleside2(
			Integer heightTopPillarsupportToBottomCrossbraceSingleside2) {
		this.heightTopPillarsupportToBottomCrossbraceSingleside2 = heightTopPillarsupportToBottomCrossbraceSingleside2;
	}

	public Integer getHeightTopPillarsupportToBottomCrossbraceSingleside3() {
		return this.heightTopPillarsupportToBottomCrossbraceSingleside3;
	}

	public void setHeightTopPillarsupportToBottomCrossbraceSingleside3(
			Integer heightTopPillarsupportToBottomCrossbraceSingleside3) {
		this.heightTopPillarsupportToBottomCrossbraceSingleside3 = heightTopPillarsupportToBottomCrossbraceSingleside3;
	}

	public Integer getHeightTopPillarsupportToBottomCrossbraceSingleside4() {
		return this.heightTopPillarsupportToBottomCrossbraceSingleside4;
	}

	public void setHeightTopPillarsupportToBottomCrossbraceSingleside4(
			Integer heightTopPillarsupportToBottomCrossbraceSingleside4) {
		this.heightTopPillarsupportToBottomCrossbraceSingleside4 = heightTopPillarsupportToBottomCrossbraceSingleside4;
	}

	public Integer getHeightTopPillarsupportToBottomCrossbraceSingleside5() {
		return this.heightTopPillarsupportToBottomCrossbraceSingleside5;
	}

	public void setHeightTopPillarsupportToBottomCrossbraceSingleside5(
			Integer heightTopPillarsupportToBottomCrossbraceSingleside5) {
		this.heightTopPillarsupportToBottomCrossbraceSingleside5 = heightTopPillarsupportToBottomCrossbraceSingleside5;
	}

	public Integer getHeightTopPillarsupportToBottomCrossbraceSingleside6() {
		return this.heightTopPillarsupportToBottomCrossbraceSingleside6;
	}

	public void setHeightTopPillarsupportToBottomCrossbraceSingleside6(
			Integer heightTopPillarsupportToBottomCrossbraceSingleside6) {
		this.heightTopPillarsupportToBottomCrossbraceSingleside6 = heightTopPillarsupportToBottomCrossbraceSingleside6;
	}

	public Integer getHeightTopPillarsupportToBottomCrossbraceCabinside1() {
		return this.heightTopPillarsupportToBottomCrossbraceCabinside1;
	}

	public void setHeightTopPillarsupportToBottomCrossbraceCabinside1(
			Integer heightTopPillarsupportToBottomCrossbraceCabinside1) {
		this.heightTopPillarsupportToBottomCrossbraceCabinside1 = heightTopPillarsupportToBottomCrossbraceCabinside1;
	}

	public Integer getHeightTopPillarsupportToBottomCrossbraceCabinside2() {
		return this.heightTopPillarsupportToBottomCrossbraceCabinside2;
	}

	public void setHeightTopPillarsupportToBottomCrossbraceCabinside2(
			Integer heightTopPillarsupportToBottomCrossbraceCabinside2) {
		this.heightTopPillarsupportToBottomCrossbraceCabinside2 = heightTopPillarsupportToBottomCrossbraceCabinside2;
	}

	public Integer getHeightTopPillarsupportToBottomCrossbraceCabinside3() {
		return this.heightTopPillarsupportToBottomCrossbraceCabinside3;
	}

	public void setHeightTopPillarsupportToBottomCrossbraceCabinside3(
			Integer heightTopPillarsupportToBottomCrossbraceCabinside3) {
		this.heightTopPillarsupportToBottomCrossbraceCabinside3 = heightTopPillarsupportToBottomCrossbraceCabinside3;
	}

	public Integer getHeightTopPillarsupportToBottomCrossbraceCabinside4() {
		return this.heightTopPillarsupportToBottomCrossbraceCabinside4;
	}

	public void setHeightTopPillarsupportToBottomCrossbraceCabinside4(
			Integer heightTopPillarsupportToBottomCrossbraceCabinside4) {
		this.heightTopPillarsupportToBottomCrossbraceCabinside4 = heightTopPillarsupportToBottomCrossbraceCabinside4;
	}

	public Integer getHeightTopPillarsupportToBottomCrossbraceCabinside5() {
		return this.heightTopPillarsupportToBottomCrossbraceCabinside5;
	}

	public void setHeightTopPillarsupportToBottomCrossbraceCabinside5(
			Integer heightTopPillarsupportToBottomCrossbraceCabinside5) {
		this.heightTopPillarsupportToBottomCrossbraceCabinside5 = heightTopPillarsupportToBottomCrossbraceCabinside5;
	}

	public Integer getHeightTopPillarsupportToBottomCrossbraceCabinside6() {
		return this.heightTopPillarsupportToBottomCrossbraceCabinside6;
	}

	public void setHeightTopPillarsupportToBottomCrossbraceCabinside6(
			Integer heightTopPillarsupportToBottomCrossbraceCabinside6) {
		this.heightTopPillarsupportToBottomCrossbraceCabinside6 = heightTopPillarsupportToBottomCrossbraceCabinside6;
	}

	public Integer getHeightCrossbracePartitionpillerSingelside1() {
		return this.heightCrossbracePartitionpillerSingelside1;
	}

	public void setHeightCrossbracePartitionpillerSingelside1(Integer heightCrossbracePartitionpillerSingelside1) {
		this.heightCrossbracePartitionpillerSingelside1 = heightCrossbracePartitionpillerSingelside1;
	}

	public Integer getHeightCrossbracePartitionpillerSingelside2() {
		return this.heightCrossbracePartitionpillerSingelside2;
	}

	public void setHeightCrossbracePartitionpillerSingelside2(Integer heightCrossbracePartitionpillerSingelside2) {
		this.heightCrossbracePartitionpillerSingelside2 = heightCrossbracePartitionpillerSingelside2;
	}

	public Integer getHeightCrossbracePartitionpillerSingelside3() {
		return this.heightCrossbracePartitionpillerSingelside3;
	}

	public void setHeightCrossbracePartitionpillerSingelside3(Integer heightCrossbracePartitionpillerSingelside3) {
		this.heightCrossbracePartitionpillerSingelside3 = heightCrossbracePartitionpillerSingelside3;
	}

	public Integer getHeightCrossbracePartitionpillerSingelside4() {
		return this.heightCrossbracePartitionpillerSingelside4;
	}

	public void setHeightCrossbracePartitionpillerSingelside4(Integer heightCrossbracePartitionpillerSingelside4) {
		this.heightCrossbracePartitionpillerSingelside4 = heightCrossbracePartitionpillerSingelside4;
	}

	public Integer getHeightCrossbracePartitionpillerSingelside5() {
		return this.heightCrossbracePartitionpillerSingelside5;
	}

	public void setHeightCrossbracePartitionpillerSingelside5(Integer heightCrossbracePartitionpillerSingelside5) {
		this.heightCrossbracePartitionpillerSingelside5 = heightCrossbracePartitionpillerSingelside5;
	}

	public Integer getHeightCrossbracePartitionpillerSingelside6() {
		return this.heightCrossbracePartitionpillerSingelside6;
	}

	public void setHeightCrossbracePartitionpillerSingelside6(Integer heightCrossbracePartitionpillerSingelside6) {
		this.heightCrossbracePartitionpillerSingelside6 = heightCrossbracePartitionpillerSingelside6;
	}

	public Integer getHeightCrossbracePartitionpillerCabinside1() {
		return this.heightCrossbracePartitionpillerCabinside1;
	}

	public void setHeightCrossbracePartitionpillerCabinside1(Integer heightCrossbracePartitionpillerCabinside1) {
		this.heightCrossbracePartitionpillerCabinside1 = heightCrossbracePartitionpillerCabinside1;
	}

	public Integer getHeightCrossbracePartitionpillerCabinside2() {
		return this.heightCrossbracePartitionpillerCabinside2;
	}

	public void setHeightCrossbracePartitionpillerCabinside2(Integer heightCrossbracePartitionpillerCabinside2) {
		this.heightCrossbracePartitionpillerCabinside2 = heightCrossbracePartitionpillerCabinside2;
	}

	public Integer getHeightCrossbracePartitionpillerCabinside3() {
		return this.heightCrossbracePartitionpillerCabinside3;
	}

	public void setHeightCrossbracePartitionpillerCabinside3(Integer heightCrossbracePartitionpillerCabinside3) {
		this.heightCrossbracePartitionpillerCabinside3 = heightCrossbracePartitionpillerCabinside3;
	}

	public Integer getHeightCrossbracePartitionpillerCabinside4() {
		return this.heightCrossbracePartitionpillerCabinside4;
	}

	public void setHeightCrossbracePartitionpillerCabinside4(Integer heightCrossbracePartitionpillerCabinside4) {
		this.heightCrossbracePartitionpillerCabinside4 = heightCrossbracePartitionpillerCabinside4;
	}

	public Integer getHeightCrossbracePartitionpillerCabinside5() {
		return this.heightCrossbracePartitionpillerCabinside5;
	}

	public void setHeightCrossbracePartitionpillerCabinside5(Integer heightCrossbracePartitionpillerCabinside5) {
		this.heightCrossbracePartitionpillerCabinside5 = heightCrossbracePartitionpillerCabinside5;
	}

	public Integer getHeightCrossbracePartitionpillerCabinside6() {
		return this.heightCrossbracePartitionpillerCabinside6;
	}

	public void setHeightCrossbracePartitionpillerCabinside6(Integer heightCrossbracePartitionpillerCabinside6) {
		this.heightCrossbracePartitionpillerCabinside6 = heightCrossbracePartitionpillerCabinside6;
	}

	public Integer getHeightVestibuleplateEndwallPp() {
		return heightVestibuleplateEndwallPp;
	}

	public void setHeightVestibuleplateEndwallPp(Integer heightVestibuleplateEndwallPp) {
		this.heightVestibuleplateEndwallPp = heightVestibuleplateEndwallPp;
	}

	public Integer getHeightVestibuleplateEndwallNpp() {
		return heightVestibuleplateEndwallNpp;
	}

	public void setHeightVestibuleplateEndwallNpp(Integer heightVestibuleplateEndwallNpp) {
		this.heightVestibuleplateEndwallNpp = heightVestibuleplateEndwallNpp;
	}

	public Integer getHeightWtccPp() {
		return this.heightWtccPp;
	}

	public void setHeightWtccPp(Integer heightWtccPp) {
		this.heightWtccPp = heightWtccPp;
	}

	public Integer getHeightWtccNpp() {
		return this.heightWtccNpp;
	}

	public void setHeightWtccNpp(Integer heightWtccNpp) {
		this.heightWtccNpp = heightWtccNpp;
	}

	public Integer getWidthWtccPp() {
		return this.widthWtccPp;
	}

	public void setWidthWtccPp(Integer widthWtccPp) {
		this.widthWtccPp = widthWtccPp;
	}

	public Integer getWidthWtccNpp() {
		return this.widthWtccNpp;
	}

	public void setWidthWtccNpp(Integer widthWtccNpp) {
		this.widthWtccNpp = widthWtccNpp;
	}

	public Integer getHeightTopThroughfloorBottomRoofArchPp() {
		return this.heightTopThroughfloorBottomRoofArchPp;
	}

	public void setHeightTopThroughfloorBottomRoofArchPp(Integer heightTopThroughfloorBottomRoofArchPp) {
		this.heightTopThroughfloorBottomRoofArchPp = heightTopThroughfloorBottomRoofArchPp;
	}

	public Integer getHeightTopThroughfloorBottomRoofArchNpp() {
		return this.heightTopThroughfloorBottomRoofArchNpp;
	}

	public void setHeightTopThroughfloorBottomRoofArchNpp(Integer heightTopThroughfloorBottomRoofArchNpp) {
		this.heightTopThroughfloorBottomRoofArchNpp = heightTopThroughfloorBottomRoofArchNpp;
	}

	public Integer getHeightFloorpillerbracketToRoofSingle1() {
		return this.heightFloorpillerbracketToRoofSingle1;
	}

	public void setHeightFloorpillerbracketToRoofSingle1(Integer heightFloorpillerbracketToRoofSingle1) {
		this.heightFloorpillerbracketToRoofSingle1 = heightFloorpillerbracketToRoofSingle1;
	}

	public Integer getHeightFloorpillerbracketToRoofSingle2() {
		return this.heightFloorpillerbracketToRoofSingle2;
	}

	public void setHeightFloorpillerbracketToRoofSingle2(Integer heightFloorpillerbracketToRoofSingle2) {
		this.heightFloorpillerbracketToRoofSingle2 = heightFloorpillerbracketToRoofSingle2;
	}

	public Integer getHeightFloorpillerbracketToRoofSingle3() {
		return this.heightFloorpillerbracketToRoofSingle3;
	}

	public void setHeightFloorpillerbracketToRoofSingle3(Integer heightFloorpillerbracketToRoofSingle3) {
		this.heightFloorpillerbracketToRoofSingle3 = heightFloorpillerbracketToRoofSingle3;
	}

	public Integer getHeightFloorpillerbracketToRoofSingle4() {
		return this.heightFloorpillerbracketToRoofSingle4;
	}

	public void setHeightFloorpillerbracketToRoofSingle4(Integer heightFloorpillerbracketToRoofSingle4) {
		this.heightFloorpillerbracketToRoofSingle4 = heightFloorpillerbracketToRoofSingle4;
	}

	public Integer getHeightFloorpillerbracketToRoofSingle5() {
		return this.heightFloorpillerbracketToRoofSingle5;
	}

	public void setHeightFloorpillerbracketToRoofSingle5(Integer heightFloorpillerbracketToRoofSingle5) {
		this.heightFloorpillerbracketToRoofSingle5 = heightFloorpillerbracketToRoofSingle5;
	}

	public Integer getHeightFloorpillerbracketToRoofSingle6() {
		return this.heightFloorpillerbracketToRoofSingle6;
	}

	public void setHeightFloorpillerbracketToRoofSingle6(Integer heightFloorpillerbracketToRoofSingle6) {
		this.heightFloorpillerbracketToRoofSingle6 = heightFloorpillerbracketToRoofSingle6;
	}

	public Integer getHeightFloorpillerbracketToRoofSingle7() {
		return this.heightFloorpillerbracketToRoofSingle7;
	}

	public void setHeightFloorpillerbracketToRoofSingle7(Integer heightFloorpillerbracketToRoofSingle7) {
		this.heightFloorpillerbracketToRoofSingle7 = heightFloorpillerbracketToRoofSingle7;
	}

	public Integer getHeightFloorpillerbracketToRoofSingle8() {
		return this.heightFloorpillerbracketToRoofSingle8;
	}

	public void setHeightFloorpillerbracketToRoofSingle8(Integer heightFloorpillerbracketToRoofSingle8) {
		this.heightFloorpillerbracketToRoofSingle8 = heightFloorpillerbracketToRoofSingle8;
	}

	public Integer getHeightFloorpillerbracketToRoofSingle9() {
		return this.heightFloorpillerbracketToRoofSingle9;
	}

	public void setHeightFloorpillerbracketToRoofSingle9(Integer heightFloorpillerbracketToRoofSingle9) {
		this.heightFloorpillerbracketToRoofSingle9 = heightFloorpillerbracketToRoofSingle9;
	}

	public Integer getHeightFloorpillerbracketToRoofSingle10() {
		return this.heightFloorpillerbracketToRoofSingle10;
	}

	public void setHeightFloorpillerbracketToRoofSingle10(Integer heightFloorpillerbracketToRoofSingle10) {
		this.heightFloorpillerbracketToRoofSingle10 = heightFloorpillerbracketToRoofSingle10;
	}

	public Integer getHeightFloorpillerbracketToRoofSingle11() {
		return this.heightFloorpillerbracketToRoofSingle11;
	}

	public void setHeightFloorpillerbracketToRoofSingle11(Integer heightFloorpillerbracketToRoofSingle11) {
		this.heightFloorpillerbracketToRoofSingle11 = heightFloorpillerbracketToRoofSingle11;
	}

	public Integer getHeightFloorpillerbracketToRoofCabin1() {
		return this.heightFloorpillerbracketToRoofCabin1;
	}

	public void setHeightFloorpillerbracketToRoofCabin1(Integer heightFloorpillerbracketToRoofCabin1) {
		this.heightFloorpillerbracketToRoofCabin1 = heightFloorpillerbracketToRoofCabin1;
	}

	public Integer getHeightFloorpillerbracketToRoofCabin2() {
		return this.heightFloorpillerbracketToRoofCabin2;
	}

	public void setHeightFloorpillerbracketToRoofCabin2(Integer heightFloorpillerbracketToRoofCabin2) {
		this.heightFloorpillerbracketToRoofCabin2 = heightFloorpillerbracketToRoofCabin2;
	}

	public Integer getHeightFloorpillerbracketToRoofCabin3() {
		return this.heightFloorpillerbracketToRoofCabin3;
	}

	public void setHeightFloorpillerbracketToRoofCabin3(Integer heightFloorpillerbracketToRoofCabin3) {
		this.heightFloorpillerbracketToRoofCabin3 = heightFloorpillerbracketToRoofCabin3;
	}

	public Integer getHeightFloorpillerbracketToRoofCabin4() {
		return this.heightFloorpillerbracketToRoofCabin4;
	}

	public void setHeightFloorpillerbracketToRoofCabin4(Integer heightFloorpillerbracketToRoofCabin4) {
		this.heightFloorpillerbracketToRoofCabin4 = heightFloorpillerbracketToRoofCabin4;
	}

	public Integer getHeightFloorpillerbracketToRoofCabin5() {
		return this.heightFloorpillerbracketToRoofCabin5;
	}

	public void setHeightFloorpillerbracketToRoofCabin5(Integer heightFloorpillerbracketToRoofCabin5) {
		this.heightFloorpillerbracketToRoofCabin5 = heightFloorpillerbracketToRoofCabin5;
	}

	public Integer getHeightFloorpillerbracketToRoofCabin6() {
		return this.heightFloorpillerbracketToRoofCabin6;
	}

	public void setHeightFloorpillerbracketToRoofCabin6(Integer heightFloorpillerbracketToRoofCabin6) {
		this.heightFloorpillerbracketToRoofCabin6 = heightFloorpillerbracketToRoofCabin6;
	}

	public Integer getHeightFloorpillerbracketToRoofCabin7() {
		return this.heightFloorpillerbracketToRoofCabin7;
	}

	public void setHeightFloorpillerbracketToRoofCabin7(Integer heightFloorpillerbracketToRoofCabin7) {
		this.heightFloorpillerbracketToRoofCabin7 = heightFloorpillerbracketToRoofCabin7;
	}

	public Integer getHeightFloorpillerbracketToRoofCabin8() {
		return this.heightFloorpillerbracketToRoofCabin8;
	}

	public void setHeightFloorpillerbracketToRoofCabin8(Integer heightFloorpillerbracketToRoofCabin8) {
		this.heightFloorpillerbracketToRoofCabin8 = heightFloorpillerbracketToRoofCabin8;
	}

	public Integer getHeightFloorpillerbracketToRoofCabin9() {
		return this.heightFloorpillerbracketToRoofCabin9;
	}

	public void setHeightFloorpillerbracketToRoofCabin9(Integer heightFloorpillerbracketToRoofCabin9) {
		this.heightFloorpillerbracketToRoofCabin9 = heightFloorpillerbracketToRoofCabin9;
	}

	public Integer getHeightFloorpillerbracketToRoofCabin10() {
		return this.heightFloorpillerbracketToRoofCabin10;
	}

	public void setHeightFloorpillerbracketToRoofCabin10(Integer heightFloorpillerbracketToRoofCabin10) {
		this.heightFloorpillerbracketToRoofCabin10 = heightFloorpillerbracketToRoofCabin10;
	}

	public Integer getHeightFloorpillerbracketToRoofCabin11() {
		return this.heightFloorpillerbracketToRoofCabin11;
	}

	public void setHeightFloorpillerbracketToRoofCabin11(Integer heightFloorpillerbracketToRoofCabin11) {
		this.heightFloorpillerbracketToRoofCabin11 = heightFloorpillerbracketToRoofCabin11;
	}

	public Integer getSlidingDoorHeightLh() {
		return this.slidingDoorHeightLh;
	}

	public void setSlidingDoorHeightLh(Integer slidingDoorHeightLh) {
		this.slidingDoorHeightLh = slidingDoorHeightLh;
	}

	public Integer getSlidingDoorHeightRh() {
		return this.slidingDoorHeightRh;
	}

	public void setSlidingDoorHeightRh(Integer slidingDoorHeightRh) {
		this.slidingDoorHeightRh = slidingDoorHeightRh;
	}

	public Integer getSlidingDoorWidthLh() {
		return this.slidingDoorWidthLh;
	}

	public void setSlidingDoorWidthLh(Integer slidingDoorWidthLh) {
		this.slidingDoorWidthLh = slidingDoorWidthLh;
	}

	public Integer getSlidingDoorWidthRh() {
		return this.slidingDoorWidthRh;
	}

	public void setSlidingDoorWidthRh(Integer slidingDoorWidthRh) {
		this.slidingDoorWidthRh = slidingDoorWidthRh;
	}

	public Integer getDistanceRoofEndwallPp() {
		return this.distanceRoofEndwallPp;
	}

	public void setDistanceRoofEndwallPp(Integer distanceRoofEndwallPp) {
		this.distanceRoofEndwallPp = distanceRoofEndwallPp;
	}

	public Integer getDistanceRoofEndwallNpp() {
		return this.distanceRoofEndwallNpp;
	}

	public void setDistanceRoofEndwallNpp(Integer distanceRoofEndwallNpp) {
		this.distanceRoofEndwallNpp = distanceRoofEndwallNpp;
	}

	public Integer getRoofElementShellSocketHoleDiePp() {
		return this.roofElementShellSocketHoleDiePp;
	}

	public void setRoofElementShellSocketHoleDiePp(Integer roofElementShellSocketHoleDiePp) {
		this.roofElementShellSocketHoleDiePp = roofElementShellSocketHoleDiePp;
	}

	public Integer getRoofElementShellSocketHoleDieNpp() {
		return this.roofElementShellSocketHoleDieNpp;
	}

	public void setRoofElementShellSocketHoleDieNpp(Integer roofElementShellSocketHoleDieNpp) {
		this.roofElementShellSocketHoleDieNpp = roofElementShellSocketHoleDieNpp;
	}

	public String getRoofElementStudDiagonalPp() {
		return this.roofElementStudDiagonalPp;
	}

	public void setRoofElementStudDiagonalPp(String roofElementStudDiagonalPp) {
		this.roofElementStudDiagonalPp = roofElementStudDiagonalPp;
	}

	public String getRoofElementStudDiagonalNpp() {
		return this.roofElementStudDiagonalNpp;
	}

	public void setRoofElementStudDiagonalNpp(String roofElementStudDiagonalNpp) {
		this.roofElementStudDiagonalNpp = roofElementStudDiagonalNpp;
	}

	public String getCheckedDimenRemarks() {
		return checkedDimenRemarks;
	}

	public void setCheckedDimenRemarks(String checkedDimenRemarks) {
		this.checkedDimenRemarks = checkedDimenRemarks;
	}

	public String getAlignmentSidewallRoofarchFlag() {
		return this.alignmentSidewallRoofarchFlag;
	}

	public void setAlignmentSidewallRoofarchFlag(String alignmentSidewallRoofarchFlag) {
		this.alignmentSidewallRoofarchFlag = alignmentSidewallRoofarchFlag;
	}

	public String getWeldingSidewallLavsidewallFlag() {
		return this.weldingSidewallLavsidewallFlag;
	}

	public void setWeldingSidewallLavsidewallFlag(String weldingSidewallLavsidewallFlag) {
		this.weldingSidewallLavsidewallFlag = weldingSidewallLavsidewallFlag;
	}
  
	public String getWeldingRoofarchSidewallCarlineFlag() {
		return weldingRoofarchSidewallCarlineFlag;
	}

	public void setWeldingRoofarchSidewallCarlineFlag(String weldingRoofarchSidewallCarlineFlag) {
		this.weldingRoofarchSidewallCarlineFlag = weldingRoofarchSidewallCarlineFlag;
	}

	public String getWeldingCompletedoorframeFlag() {
		return this.weldingCompletedoorframeFlag;
	}

	public void setWeldingCompletedoorframeFlag(String weldingCompletedoorframeFlag) {
		this.weldingCompletedoorframeFlag = weldingCompletedoorframeFlag;
	}

	public String getWeldingCompleteendwallFinalroofelementFlag() {
		return this.weldingCompleteendwallFinalroofelementFlag;
	}

	public void setWeldingCompleteendwallFinalroofelementFlag(String weldingCompleteendwallFinalroofelementFlag) {
		this.weldingCompleteendwallFinalroofelementFlag = weldingCompleteendwallFinalroofelementFlag;
	}
	public String getWeldingRoofSidewallCarlineFlag() {
		return weldingRoofSidewallCarlineFlag;
	}

	public void setWeldingRoofSidewallCarlineFlag(String weldingRoofSidewallCarlineFlag) {
		this.weldingRoofSidewallCarlineFlag = weldingRoofSidewallCarlineFlag;
	}

	public String getGrindHorizontalVerticalJointFlag() {
		return this.grindHorizontalVerticalJointFlag;
	}

	public void setGrindHorizontalVerticalJointFlag(String grindHorizontalVerticalJointFlag) {
		this.grindHorizontalVerticalJointFlag = grindHorizontalVerticalJointFlag;
	}

	public String getAlignmentBothSidewallUnderframeFlag() {
		return this.alignmentBothSidewallUnderframeFlag;
	}

	public void setAlignmentBothSidewallUnderframeFlag(String alignmentBothSidewallUnderframeFlag) {
		this.alignmentBothSidewallUnderframeFlag = alignmentBothSidewallUnderframeFlag;
	}

	public String getDetailsOfModification() {
		return this.detailsOfModification;
	}

	public void setDetailsOfModification(String detailsOfModification) {
		this.detailsOfModification = detailsOfModification;
	}

	public String getDetailsOfTrial() {
		return this.detailsOfTrial;
	}

	public void setDetailsOfTrial(String detailsOfTrial) {
		this.detailsOfTrial = detailsOfTrial;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getStage1TestingStatus() {
		return this.stage1TestingStatus;
	}

	public void setStage1TestingStatus(String stage1TestingStatus) {
		this.stage1TestingStatus = stage1TestingStatus;
	}

	public String getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(String entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryTime() {
		return this.entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

}
